-- HPS_QSYS_intel_agilex_5_soc_0.vhd

-- Generated using ACDS version 25.3.1 100

library IEEE;
library intel_agilex_5_soc_1300;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity HPS_QSYS_intel_agilex_5_soc_0 is
	port (
		h2f_reset_reset            : out   std_logic;                                         --            h2f_reset.reset,   Active high reset from the HPS Reset Manager.
		hps2fpga_axi_clock_clk     : in    std_logic                      := '0';             --   hps2fpga_axi_clock.clk,     Clock from a single source in the FPGA.
		hps2fpga_axi_reset_reset   : in    std_logic                      := '0';             --   hps2fpga_axi_reset.reset,   Async reset to the Bridge logic. This signal is active-HIGH.
		hps2fpga_awid              : out   std_logic_vector(3 downto 0);                      --             hps2fpga.awid,    Identification tag for a write transaction.
		hps2fpga_awaddr            : out   std_logic_vector(27 downto 0);                     --                     .awaddr,  The address of the first transfer in a write transaction.
		hps2fpga_awlen             : out   std_logic_vector(7 downto 0);                      --                     .awlen,   The exact number of data transfers in a write transaction.
		hps2fpga_awsize            : out   std_logic_vector(2 downto 0);                      --                     .awsize,  The number of bytes in each data transfer in a write transaction.
		hps2fpga_awburst           : out   std_logic_vector(1 downto 0);                      --                     .awburst, Indicates how address changes between each transfer in a write transaction.
		hps2fpga_awlock            : out   std_logic;                                         --                     .awlock,  Provides information about the atomic characteristics of a write transaction.
		hps2fpga_awcache           : out   std_logic_vector(3 downto 0);                      --                     .awcache, Indicates how a write transaction is required to progress through a system.
		hps2fpga_awprot            : out   std_logic_vector(2 downto 0);                      --                     .awprot,  Protection attributes of a write transaction: privilege, security level, and access type.
		hps2fpga_awvalid           : out   std_logic;                                         --                     .awvalid, Indicates that the write address channel signals are valid.
		hps2fpga_awready           : in    std_logic                      := '0';             --                     .awready, Indicates that a transfer on the write address channel can be accepted.
		hps2fpga_wdata             : out   std_logic_vector(127 downto 0);                    --                     .wdata,   Write data.
		hps2fpga_wstrb             : out   std_logic_vector(15 downto 0);                     --                     .wstrb,   Write strobes, indicate which byte lanes hold valid data.
		hps2fpga_wlast             : out   std_logic;                                         --                     .wlast,   User-defined extension for the write data channel.
		hps2fpga_wvalid            : out   std_logic;                                         --                     .wvalid,  Indicates that the write data channel signals are valid.
		hps2fpga_wready            : in    std_logic                      := '0';             --                     .wready,  Indicates that a transfer on the write data channel can be accepted.
		hps2fpga_bid               : in    std_logic_vector(3 downto 0)   := (others => '0'); --                     .bid,     Transaction identifier for the write response.
		hps2fpga_bresp             : in    std_logic_vector(1 downto 0)   := (others => '0'); --                     .bresp,   Write response, indicates the status of a write transaction.
		hps2fpga_bvalid            : in    std_logic                      := '0';             --                     .bvalid,  Indicates that the write response channel signals are valid.
		hps2fpga_bready            : out   std_logic;                                         --                     .bready,  Indicates that a transfer on the write response channel can be accepted.
		hps2fpga_arid              : out   std_logic_vector(3 downto 0);                      --                     .arid,    Transaction identifier for the read transaction.
		hps2fpga_araddr            : out   std_logic_vector(27 downto 0);                     --                     .araddr,  The address of the first transfer in a read transaction.
		hps2fpga_arlen             : out   std_logic_vector(7 downto 0);                      --                     .arlen,   The exact number of data transfers in a read transaction.
		hps2fpga_arsize            : out   std_logic_vector(2 downto 0);                      --                     .arsize,  The number of bytes in each data transfer in a read transaction.
		hps2fpga_arburst           : out   std_logic_vector(1 downto 0);                      --                     .arburst, Indicates how address changes between each transfer in a read transaction.
		hps2fpga_arlock            : out   std_logic;                                         --                     .arlock,  Provides information about the atomic characteristics of a read transaction.
		hps2fpga_arcache           : out   std_logic_vector(3 downto 0);                      --                     .arcache, Indicates how a read transaction is required to progress through a system.
		hps2fpga_arprot            : out   std_logic_vector(2 downto 0);                      --                     .arprot,  Protection attributes of a read transaction: privilege, security level, and access type.
		hps2fpga_arvalid           : out   std_logic;                                         --                     .arvalid, Indicates that the read address channel signals are valid.
		hps2fpga_arready           : in    std_logic                      := '0';             --                     .arready, Indicates that a transfer on the read address channel can be accepted.
		hps2fpga_rid               : in    std_logic_vector(3 downto 0)   := (others => '0'); --                     .rid,     Identification tag for read data and response.
		hps2fpga_rdata             : in    std_logic_vector(127 downto 0) := (others => '0'); --                     .rdata,   Read data.
		hps2fpga_rresp             : in    std_logic_vector(1 downto 0)   := (others => '0'); --                     .rresp,   Read response, indicates the status of a read transfer.
		hps2fpga_rlast             : in    std_logic                      := '0';             --                     .rlast,   Indicates whether this is the last data transfer in a read transaction.
		hps2fpga_rvalid            : in    std_logic                      := '0';             --                     .rvalid,  Indicates that the read data channel signals are valid.
		hps2fpga_rready            : out   std_logic;                                         --                     .rready,  Indicates that a transfer on the read data channel can be accepted.
		lwhps2fpga_axi_clock_clk   : in    std_logic                      := '0';             -- lwhps2fpga_axi_clock.clk,     clock from a single source in the FPGA.
		lwhps2fpga_axi_reset_reset : in    std_logic                      := '0';             -- lwhps2fpga_axi_reset.reset,   Async reset to the Bridge logic. This signal is active-HIGH.
		lwhps2fpga_awid            : out   std_logic_vector(3 downto 0);                      --           lwhps2fpga.awid,    Identification tag for a write transaction.
		lwhps2fpga_awaddr          : out   std_logic_vector(23 downto 0);                     --                     .awaddr,  The address of the first transfer in a write transaction.
		lwhps2fpga_awlen           : out   std_logic_vector(7 downto 0);                      --                     .awlen,   The exact number of data transfers in a write transaction.
		lwhps2fpga_awsize          : out   std_logic_vector(2 downto 0);                      --                     .awsize,  The number of bytes in each data transfer in a write transaction.
		lwhps2fpga_awburst         : out   std_logic_vector(1 downto 0);                      --                     .awburst, Indicates how address changes between each transfer in a write transaction.
		lwhps2fpga_awlock          : out   std_logic;                                         --                     .awlock,  Provides information about the atomic characteristics of a write transaction.
		lwhps2fpga_awcache         : out   std_logic_vector(3 downto 0);                      --                     .awcache, Indicates how a write transaction is required to progress through a system.
		lwhps2fpga_awprot          : out   std_logic_vector(2 downto 0);                      --                     .awprot,  Protection attributes of a write transaction: privilege, security level, and access type.
		lwhps2fpga_awvalid         : out   std_logic;                                         --                     .awvalid, Indicates that the write address channel signals are valid.
		lwhps2fpga_awready         : in    std_logic                      := '0';             --                     .awready, Indicates that a transfer on the write address channel can be accepted.
		lwhps2fpga_wdata           : out   std_logic_vector(31 downto 0);                     --                     .wdata,   Write data.
		lwhps2fpga_wstrb           : out   std_logic_vector(3 downto 0);                      --                     .wstrb,   Write strobes, indicate which byte lanes hold valid data.
		lwhps2fpga_wlast           : out   std_logic;                                         --                     .wlast,   User-defined extension for the write data channel.
		lwhps2fpga_wvalid          : out   std_logic;                                         --                     .wvalid,  Indicates that the write data channel signals are valid.
		lwhps2fpga_wready          : in    std_logic                      := '0';             --                     .wready,  Indicates that a transfer on the write data channel can be accepted.
		lwhps2fpga_bid             : in    std_logic_vector(3 downto 0)   := (others => '0'); --                     .bid,     Transaction identifier for the write response.
		lwhps2fpga_bresp           : in    std_logic_vector(1 downto 0)   := (others => '0'); --                     .bresp,   Write response, indicates the status of a write transaction.
		lwhps2fpga_bvalid          : in    std_logic                      := '0';             --                     .bvalid,  Indicates that the write response channel signals are valid.
		lwhps2fpga_bready          : out   std_logic;                                         --                     .bready,  Indicates that a transfer on the write response channel can be accepted.
		lwhps2fpga_arid            : out   std_logic_vector(3 downto 0);                      --                     .arid,    Transaction identifier for the read transaction.
		lwhps2fpga_araddr          : out   std_logic_vector(23 downto 0);                     --                     .araddr,  The address of the first transfer in a read transaction.
		lwhps2fpga_arlen           : out   std_logic_vector(7 downto 0);                      --                     .arlen,   The exact number of data transfers in a read transaction.
		lwhps2fpga_arsize          : out   std_logic_vector(2 downto 0);                      --                     .arsize,  The number of bytes in each data transfer in a read transaction.
		lwhps2fpga_arburst         : out   std_logic_vector(1 downto 0);                      --                     .arburst, Indicates how address changes between each transfer in a read transaction.
		lwhps2fpga_arlock          : out   std_logic;                                         --                     .arlock,  Provides information about the atomic characteristics of a read transaction.
		lwhps2fpga_arcache         : out   std_logic_vector(3 downto 0);                      --                     .arcache, Indicates how a read transaction is required to progress through a system.
		lwhps2fpga_arprot          : out   std_logic_vector(2 downto 0);                      --                     .arprot,  Protection attributes of a read transaction: privilege, security level, and access type.
		lwhps2fpga_arvalid         : out   std_logic;                                         --                     .arvalid, Indicates that the read address channel signals are valid.
		lwhps2fpga_arready         : in    std_logic                      := '0';             --                     .arready, Indicates that a transfer on the read address channel can be accepted.
		lwhps2fpga_rid             : in    std_logic_vector(3 downto 0)   := (others => '0'); --                     .rid,     Identification tag for read data and response.
		lwhps2fpga_rdata           : in    std_logic_vector(31 downto 0)  := (others => '0'); --                     .rdata,   Read data.
		lwhps2fpga_rresp           : in    std_logic_vector(1 downto 0)   := (others => '0'); --                     .rresp,   Read response, indicates the status of a read transfer.
		lwhps2fpga_rlast           : in    std_logic                      := '0';             --                     .rlast,   Indicates whether this is the last data transfer in a read transaction.
		lwhps2fpga_rvalid          : in    std_logic                      := '0';             --                     .rvalid,  Indicates that the read data channel signals are valid.
		lwhps2fpga_rready          : out   std_logic;                                         --                     .rready,  Indicates that a transfer on the read data channel can be accepted.
		hps_io_gpio41              : inout std_logic                      := '0'              --               hps_io.gpio41,  GPIO1 IO17
	);
end entity HPS_QSYS_intel_agilex_5_soc_0;

architecture rtl of HPS_QSYS_intel_agilex_5_soc_0 is
	component HPS_QSYS_intel_agilex_5_soc_0_intel_agilex_5_soc_1300_qrfuhsi_cmp is
		port (
			h2f_reset_reset            : out   std_logic;                                         -- reset
			hps2fpga_axi_clock_clk     : in    std_logic                      := 'X';             -- clk
			hps2fpga_axi_reset_reset   : in    std_logic                      := 'X';             -- reset
			hps2fpga_awid              : out   std_logic_vector(3 downto 0);                      -- awid
			hps2fpga_awaddr            : out   std_logic_vector(27 downto 0);                     -- awaddr
			hps2fpga_awlen             : out   std_logic_vector(7 downto 0);                      -- awlen
			hps2fpga_awsize            : out   std_logic_vector(2 downto 0);                      -- awsize
			hps2fpga_awburst           : out   std_logic_vector(1 downto 0);                      -- awburst
			hps2fpga_awlock            : out   std_logic;                                         -- awlock
			hps2fpga_awcache           : out   std_logic_vector(3 downto 0);                      -- awcache
			hps2fpga_awprot            : out   std_logic_vector(2 downto 0);                      -- awprot
			hps2fpga_awvalid           : out   std_logic;                                         -- awvalid
			hps2fpga_awready           : in    std_logic                      := 'X';             -- awready
			hps2fpga_wdata             : out   std_logic_vector(127 downto 0);                    -- wdata
			hps2fpga_wstrb             : out   std_logic_vector(15 downto 0);                     -- wstrb
			hps2fpga_wlast             : out   std_logic;                                         -- wlast
			hps2fpga_wvalid            : out   std_logic;                                         -- wvalid
			hps2fpga_wready            : in    std_logic                      := 'X';             -- wready
			hps2fpga_bid               : in    std_logic_vector(3 downto 0)   := (others => 'X'); -- bid
			hps2fpga_bresp             : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- bresp
			hps2fpga_bvalid            : in    std_logic                      := 'X';             -- bvalid
			hps2fpga_bready            : out   std_logic;                                         -- bready
			hps2fpga_arid              : out   std_logic_vector(3 downto 0);                      -- arid
			hps2fpga_araddr            : out   std_logic_vector(27 downto 0);                     -- araddr
			hps2fpga_arlen             : out   std_logic_vector(7 downto 0);                      -- arlen
			hps2fpga_arsize            : out   std_logic_vector(2 downto 0);                      -- arsize
			hps2fpga_arburst           : out   std_logic_vector(1 downto 0);                      -- arburst
			hps2fpga_arlock            : out   std_logic;                                         -- arlock
			hps2fpga_arcache           : out   std_logic_vector(3 downto 0);                      -- arcache
			hps2fpga_arprot            : out   std_logic_vector(2 downto 0);                      -- arprot
			hps2fpga_arvalid           : out   std_logic;                                         -- arvalid
			hps2fpga_arready           : in    std_logic                      := 'X';             -- arready
			hps2fpga_rid               : in    std_logic_vector(3 downto 0)   := (others => 'X'); -- rid
			hps2fpga_rdata             : in    std_logic_vector(127 downto 0) := (others => 'X'); -- rdata
			hps2fpga_rresp             : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- rresp
			hps2fpga_rlast             : in    std_logic                      := 'X';             -- rlast
			hps2fpga_rvalid            : in    std_logic                      := 'X';             -- rvalid
			hps2fpga_rready            : out   std_logic;                                         -- rready
			lwhps2fpga_axi_clock_clk   : in    std_logic                      := 'X';             -- clk
			lwhps2fpga_axi_reset_reset : in    std_logic                      := 'X';             -- reset
			lwhps2fpga_awid            : out   std_logic_vector(3 downto 0);                      -- awid
			lwhps2fpga_awaddr          : out   std_logic_vector(23 downto 0);                     -- awaddr
			lwhps2fpga_awlen           : out   std_logic_vector(7 downto 0);                      -- awlen
			lwhps2fpga_awsize          : out   std_logic_vector(2 downto 0);                      -- awsize
			lwhps2fpga_awburst         : out   std_logic_vector(1 downto 0);                      -- awburst
			lwhps2fpga_awlock          : out   std_logic;                                         -- awlock
			lwhps2fpga_awcache         : out   std_logic_vector(3 downto 0);                      -- awcache
			lwhps2fpga_awprot          : out   std_logic_vector(2 downto 0);                      -- awprot
			lwhps2fpga_awvalid         : out   std_logic;                                         -- awvalid
			lwhps2fpga_awready         : in    std_logic                      := 'X';             -- awready
			lwhps2fpga_wdata           : out   std_logic_vector(31 downto 0);                     -- wdata
			lwhps2fpga_wstrb           : out   std_logic_vector(3 downto 0);                      -- wstrb
			lwhps2fpga_wlast           : out   std_logic;                                         -- wlast
			lwhps2fpga_wvalid          : out   std_logic;                                         -- wvalid
			lwhps2fpga_wready          : in    std_logic                      := 'X';             -- wready
			lwhps2fpga_bid             : in    std_logic_vector(3 downto 0)   := (others => 'X'); -- bid
			lwhps2fpga_bresp           : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- bresp
			lwhps2fpga_bvalid          : in    std_logic                      := 'X';             -- bvalid
			lwhps2fpga_bready          : out   std_logic;                                         -- bready
			lwhps2fpga_arid            : out   std_logic_vector(3 downto 0);                      -- arid
			lwhps2fpga_araddr          : out   std_logic_vector(23 downto 0);                     -- araddr
			lwhps2fpga_arlen           : out   std_logic_vector(7 downto 0);                      -- arlen
			lwhps2fpga_arsize          : out   std_logic_vector(2 downto 0);                      -- arsize
			lwhps2fpga_arburst         : out   std_logic_vector(1 downto 0);                      -- arburst
			lwhps2fpga_arlock          : out   std_logic;                                         -- arlock
			lwhps2fpga_arcache         : out   std_logic_vector(3 downto 0);                      -- arcache
			lwhps2fpga_arprot          : out   std_logic_vector(2 downto 0);                      -- arprot
			lwhps2fpga_arvalid         : out   std_logic;                                         -- arvalid
			lwhps2fpga_arready         : in    std_logic                      := 'X';             -- arready
			lwhps2fpga_rid             : in    std_logic_vector(3 downto 0)   := (others => 'X'); -- rid
			lwhps2fpga_rdata           : in    std_logic_vector(31 downto 0)  := (others => 'X'); -- rdata
			lwhps2fpga_rresp           : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- rresp
			lwhps2fpga_rlast           : in    std_logic                      := 'X';             -- rlast
			lwhps2fpga_rvalid          : in    std_logic                      := 'X';             -- rvalid
			lwhps2fpga_rready          : out   std_logic;                                         -- rready
			hps_io_gpio41              : inout std_logic                      := 'X'              -- gpio41
		);
	end component HPS_QSYS_intel_agilex_5_soc_0_intel_agilex_5_soc_1300_qrfuhsi_cmp;

	for intel_agilex_5_soc_0 : HPS_QSYS_intel_agilex_5_soc_0_intel_agilex_5_soc_1300_qrfuhsi_cmp
		use entity intel_agilex_5_soc_1300.HPS_QSYS_intel_agilex_5_soc_0_intel_agilex_5_soc_1300_qrfuhsi;
begin

	intel_agilex_5_soc_0 : component HPS_QSYS_intel_agilex_5_soc_0_intel_agilex_5_soc_1300_qrfuhsi_cmp
		port map (
			h2f_reset_reset            => h2f_reset_reset,            --            h2f_reset.reset
			hps2fpga_axi_clock_clk     => hps2fpga_axi_clock_clk,     --   hps2fpga_axi_clock.clk
			hps2fpga_axi_reset_reset   => hps2fpga_axi_reset_reset,   --   hps2fpga_axi_reset.reset
			hps2fpga_awid              => hps2fpga_awid,              --             hps2fpga.awid
			hps2fpga_awaddr            => hps2fpga_awaddr,            --                     .awaddr
			hps2fpga_awlen             => hps2fpga_awlen,             --                     .awlen
			hps2fpga_awsize            => hps2fpga_awsize,            --                     .awsize
			hps2fpga_awburst           => hps2fpga_awburst,           --                     .awburst
			hps2fpga_awlock            => hps2fpga_awlock,            --                     .awlock
			hps2fpga_awcache           => hps2fpga_awcache,           --                     .awcache
			hps2fpga_awprot            => hps2fpga_awprot,            --                     .awprot
			hps2fpga_awvalid           => hps2fpga_awvalid,           --                     .awvalid
			hps2fpga_awready           => hps2fpga_awready,           --                     .awready
			hps2fpga_wdata             => hps2fpga_wdata,             --                     .wdata
			hps2fpga_wstrb             => hps2fpga_wstrb,             --                     .wstrb
			hps2fpga_wlast             => hps2fpga_wlast,             --                     .wlast
			hps2fpga_wvalid            => hps2fpga_wvalid,            --                     .wvalid
			hps2fpga_wready            => hps2fpga_wready,            --                     .wready
			hps2fpga_bid               => hps2fpga_bid,               --                     .bid
			hps2fpga_bresp             => hps2fpga_bresp,             --                     .bresp
			hps2fpga_bvalid            => hps2fpga_bvalid,            --                     .bvalid
			hps2fpga_bready            => hps2fpga_bready,            --                     .bready
			hps2fpga_arid              => hps2fpga_arid,              --                     .arid
			hps2fpga_araddr            => hps2fpga_araddr,            --                     .araddr
			hps2fpga_arlen             => hps2fpga_arlen,             --                     .arlen
			hps2fpga_arsize            => hps2fpga_arsize,            --                     .arsize
			hps2fpga_arburst           => hps2fpga_arburst,           --                     .arburst
			hps2fpga_arlock            => hps2fpga_arlock,            --                     .arlock
			hps2fpga_arcache           => hps2fpga_arcache,           --                     .arcache
			hps2fpga_arprot            => hps2fpga_arprot,            --                     .arprot
			hps2fpga_arvalid           => hps2fpga_arvalid,           --                     .arvalid
			hps2fpga_arready           => hps2fpga_arready,           --                     .arready
			hps2fpga_rid               => hps2fpga_rid,               --                     .rid
			hps2fpga_rdata             => hps2fpga_rdata,             --                     .rdata
			hps2fpga_rresp             => hps2fpga_rresp,             --                     .rresp
			hps2fpga_rlast             => hps2fpga_rlast,             --                     .rlast
			hps2fpga_rvalid            => hps2fpga_rvalid,            --                     .rvalid
			hps2fpga_rready            => hps2fpga_rready,            --                     .rready
			lwhps2fpga_axi_clock_clk   => lwhps2fpga_axi_clock_clk,   -- lwhps2fpga_axi_clock.clk
			lwhps2fpga_axi_reset_reset => lwhps2fpga_axi_reset_reset, -- lwhps2fpga_axi_reset.reset
			lwhps2fpga_awid            => lwhps2fpga_awid,            --           lwhps2fpga.awid
			lwhps2fpga_awaddr          => lwhps2fpga_awaddr,          --                     .awaddr
			lwhps2fpga_awlen           => lwhps2fpga_awlen,           --                     .awlen
			lwhps2fpga_awsize          => lwhps2fpga_awsize,          --                     .awsize
			lwhps2fpga_awburst         => lwhps2fpga_awburst,         --                     .awburst
			lwhps2fpga_awlock          => lwhps2fpga_awlock,          --                     .awlock
			lwhps2fpga_awcache         => lwhps2fpga_awcache,         --                     .awcache
			lwhps2fpga_awprot          => lwhps2fpga_awprot,          --                     .awprot
			lwhps2fpga_awvalid         => lwhps2fpga_awvalid,         --                     .awvalid
			lwhps2fpga_awready         => lwhps2fpga_awready,         --                     .awready
			lwhps2fpga_wdata           => lwhps2fpga_wdata,           --                     .wdata
			lwhps2fpga_wstrb           => lwhps2fpga_wstrb,           --                     .wstrb
			lwhps2fpga_wlast           => lwhps2fpga_wlast,           --                     .wlast
			lwhps2fpga_wvalid          => lwhps2fpga_wvalid,          --                     .wvalid
			lwhps2fpga_wready          => lwhps2fpga_wready,          --                     .wready
			lwhps2fpga_bid             => lwhps2fpga_bid,             --                     .bid
			lwhps2fpga_bresp           => lwhps2fpga_bresp,           --                     .bresp
			lwhps2fpga_bvalid          => lwhps2fpga_bvalid,          --                     .bvalid
			lwhps2fpga_bready          => lwhps2fpga_bready,          --                     .bready
			lwhps2fpga_arid            => lwhps2fpga_arid,            --                     .arid
			lwhps2fpga_araddr          => lwhps2fpga_araddr,          --                     .araddr
			lwhps2fpga_arlen           => lwhps2fpga_arlen,           --                     .arlen
			lwhps2fpga_arsize          => lwhps2fpga_arsize,          --                     .arsize
			lwhps2fpga_arburst         => lwhps2fpga_arburst,         --                     .arburst
			lwhps2fpga_arlock          => lwhps2fpga_arlock,          --                     .arlock
			lwhps2fpga_arcache         => lwhps2fpga_arcache,         --                     .arcache
			lwhps2fpga_arprot          => lwhps2fpga_arprot,          --                     .arprot
			lwhps2fpga_arvalid         => lwhps2fpga_arvalid,         --                     .arvalid
			lwhps2fpga_arready         => lwhps2fpga_arready,         --                     .arready
			lwhps2fpga_rid             => lwhps2fpga_rid,             --                     .rid
			lwhps2fpga_rdata           => lwhps2fpga_rdata,           --                     .rdata
			lwhps2fpga_rresp           => lwhps2fpga_rresp,           --                     .rresp
			lwhps2fpga_rlast           => lwhps2fpga_rlast,           --                     .rlast
			lwhps2fpga_rvalid          => lwhps2fpga_rvalid,          --                     .rvalid
			lwhps2fpga_rready          => lwhps2fpga_rready,          --                     .rready
			hps_io_gpio41              => hps_io_gpio41               --               hps_io.gpio41
		);

end architecture rtl; -- of HPS_QSYS_intel_agilex_5_soc_0
