-- HPS_QSYS.vhd

-- Generated using ACDS version 25.3.1 100

library IEEE;
library HPS_QSYS_intel_agilex_5_soc_0;
library HPS_QSYS_intel_onchip_memory_0;
library HPS_QSYS_iopll_0;
library HPS_QSYS_reset_bridge_0;
library altera_mm_interconnect_1920;
library altera_reset_controller_1924;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity HPS_QSYS is
	port (
		hps2fpga_awid    : out   std_logic_vector(3 downto 0);                      -- hps2fpga.awid
		hps2fpga_awaddr  : out   std_logic_vector(27 downto 0);                     --         .awaddr
		hps2fpga_awlen   : out   std_logic_vector(7 downto 0);                      --         .awlen
		hps2fpga_awsize  : out   std_logic_vector(2 downto 0);                      --         .awsize
		hps2fpga_awburst : out   std_logic_vector(1 downto 0);                      --         .awburst
		hps2fpga_awlock  : out   std_logic;                                         --         .awlock
		hps2fpga_awcache : out   std_logic_vector(3 downto 0);                      --         .awcache
		hps2fpga_awprot  : out   std_logic_vector(2 downto 0);                      --         .awprot
		hps2fpga_awvalid : out   std_logic;                                         --         .awvalid
		hps2fpga_awready : in    std_logic                      := '0';             --         .awready
		hps2fpga_wdata   : out   std_logic_vector(127 downto 0);                    --         .wdata
		hps2fpga_wstrb   : out   std_logic_vector(15 downto 0);                     --         .wstrb
		hps2fpga_wlast   : out   std_logic;                                         --         .wlast
		hps2fpga_wvalid  : out   std_logic;                                         --         .wvalid
		hps2fpga_wready  : in    std_logic                      := '0';             --         .wready
		hps2fpga_bid     : in    std_logic_vector(3 downto 0)   := (others => '0'); --         .bid
		hps2fpga_bresp   : in    std_logic_vector(1 downto 0)   := (others => '0'); --         .bresp
		hps2fpga_bvalid  : in    std_logic                      := '0';             --         .bvalid
		hps2fpga_bready  : out   std_logic;                                         --         .bready
		hps2fpga_arid    : out   std_logic_vector(3 downto 0);                      --         .arid
		hps2fpga_araddr  : out   std_logic_vector(27 downto 0);                     --         .araddr
		hps2fpga_arlen   : out   std_logic_vector(7 downto 0);                      --         .arlen
		hps2fpga_arsize  : out   std_logic_vector(2 downto 0);                      --         .arsize
		hps2fpga_arburst : out   std_logic_vector(1 downto 0);                      --         .arburst
		hps2fpga_arlock  : out   std_logic;                                         --         .arlock
		hps2fpga_arcache : out   std_logic_vector(3 downto 0);                      --         .arcache
		hps2fpga_arprot  : out   std_logic_vector(2 downto 0);                      --         .arprot
		hps2fpga_arvalid : out   std_logic;                                         --         .arvalid
		hps2fpga_arready : in    std_logic                      := '0';             --         .arready
		hps2fpga_rid     : in    std_logic_vector(3 downto 0)   := (others => '0'); --         .rid
		hps2fpga_rdata   : in    std_logic_vector(127 downto 0) := (others => '0'); --         .rdata
		hps2fpga_rresp   : in    std_logic_vector(1 downto 0)   := (others => '0'); --         .rresp
		hps2fpga_rlast   : in    std_logic                      := '0';             --         .rlast
		hps2fpga_rvalid  : in    std_logic                      := '0';             --         .rvalid
		hps2fpga_rready  : out   std_logic;                                         --         .rready
		hps_io_gpio41    : inout std_logic                      := '0';             --   hps_io.gpio41
		refclk_clk       : in    std_logic                      := '0';             --   refclk.clk
		locked_export    : out   std_logic;                                         --   locked.export
		reset_reset      : in    std_logic                      := '0';             --    reset.reset
		in_reset_reset_n : in    std_logic                      := '0'              -- in_reset.reset_n
	);
end entity HPS_QSYS;

architecture rtl of HPS_QSYS is
	component HPS_QSYS_intel_agilex_5_soc_0_cmp is
		port (
			h2f_reset_reset            : out   std_logic;                                         -- reset
			hps2fpga_axi_clock_clk     : in    std_logic                      := 'X';             -- clk
			hps2fpga_axi_reset_reset   : in    std_logic                      := 'X';             -- reset
			hps2fpga_awid              : out   std_logic_vector(3 downto 0);                      -- awid
			hps2fpga_awaddr            : out   std_logic_vector(27 downto 0);                     -- awaddr
			hps2fpga_awlen             : out   std_logic_vector(7 downto 0);                      -- awlen
			hps2fpga_awsize            : out   std_logic_vector(2 downto 0);                      -- awsize
			hps2fpga_awburst           : out   std_logic_vector(1 downto 0);                      -- awburst
			hps2fpga_awlock            : out   std_logic;                                         -- awlock
			hps2fpga_awcache           : out   std_logic_vector(3 downto 0);                      -- awcache
			hps2fpga_awprot            : out   std_logic_vector(2 downto 0);                      -- awprot
			hps2fpga_awvalid           : out   std_logic;                                         -- awvalid
			hps2fpga_awready           : in    std_logic                      := 'X';             -- awready
			hps2fpga_wdata             : out   std_logic_vector(127 downto 0);                    -- wdata
			hps2fpga_wstrb             : out   std_logic_vector(15 downto 0);                     -- wstrb
			hps2fpga_wlast             : out   std_logic;                                         -- wlast
			hps2fpga_wvalid            : out   std_logic;                                         -- wvalid
			hps2fpga_wready            : in    std_logic                      := 'X';             -- wready
			hps2fpga_bid               : in    std_logic_vector(3 downto 0)   := (others => 'X'); -- bid
			hps2fpga_bresp             : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- bresp
			hps2fpga_bvalid            : in    std_logic                      := 'X';             -- bvalid
			hps2fpga_bready            : out   std_logic;                                         -- bready
			hps2fpga_arid              : out   std_logic_vector(3 downto 0);                      -- arid
			hps2fpga_araddr            : out   std_logic_vector(27 downto 0);                     -- araddr
			hps2fpga_arlen             : out   std_logic_vector(7 downto 0);                      -- arlen
			hps2fpga_arsize            : out   std_logic_vector(2 downto 0);                      -- arsize
			hps2fpga_arburst           : out   std_logic_vector(1 downto 0);                      -- arburst
			hps2fpga_arlock            : out   std_logic;                                         -- arlock
			hps2fpga_arcache           : out   std_logic_vector(3 downto 0);                      -- arcache
			hps2fpga_arprot            : out   std_logic_vector(2 downto 0);                      -- arprot
			hps2fpga_arvalid           : out   std_logic;                                         -- arvalid
			hps2fpga_arready           : in    std_logic                      := 'X';             -- arready
			hps2fpga_rid               : in    std_logic_vector(3 downto 0)   := (others => 'X'); -- rid
			hps2fpga_rdata             : in    std_logic_vector(127 downto 0) := (others => 'X'); -- rdata
			hps2fpga_rresp             : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- rresp
			hps2fpga_rlast             : in    std_logic                      := 'X';             -- rlast
			hps2fpga_rvalid            : in    std_logic                      := 'X';             -- rvalid
			hps2fpga_rready            : out   std_logic;                                         -- rready
			lwhps2fpga_axi_clock_clk   : in    std_logic                      := 'X';             -- clk
			lwhps2fpga_axi_reset_reset : in    std_logic                      := 'X';             -- reset
			lwhps2fpga_awid            : out   std_logic_vector(3 downto 0);                      -- awid
			lwhps2fpga_awaddr          : out   std_logic_vector(23 downto 0);                     -- awaddr
			lwhps2fpga_awlen           : out   std_logic_vector(7 downto 0);                      -- awlen
			lwhps2fpga_awsize          : out   std_logic_vector(2 downto 0);                      -- awsize
			lwhps2fpga_awburst         : out   std_logic_vector(1 downto 0);                      -- awburst
			lwhps2fpga_awlock          : out   std_logic;                                         -- awlock
			lwhps2fpga_awcache         : out   std_logic_vector(3 downto 0);                      -- awcache
			lwhps2fpga_awprot          : out   std_logic_vector(2 downto 0);                      -- awprot
			lwhps2fpga_awvalid         : out   std_logic;                                         -- awvalid
			lwhps2fpga_awready         : in    std_logic                      := 'X';             -- awready
			lwhps2fpga_wdata           : out   std_logic_vector(31 downto 0);                     -- wdata
			lwhps2fpga_wstrb           : out   std_logic_vector(3 downto 0);                      -- wstrb
			lwhps2fpga_wlast           : out   std_logic;                                         -- wlast
			lwhps2fpga_wvalid          : out   std_logic;                                         -- wvalid
			lwhps2fpga_wready          : in    std_logic                      := 'X';             -- wready
			lwhps2fpga_bid             : in    std_logic_vector(3 downto 0)   := (others => 'X'); -- bid
			lwhps2fpga_bresp           : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- bresp
			lwhps2fpga_bvalid          : in    std_logic                      := 'X';             -- bvalid
			lwhps2fpga_bready          : out   std_logic;                                         -- bready
			lwhps2fpga_arid            : out   std_logic_vector(3 downto 0);                      -- arid
			lwhps2fpga_araddr          : out   std_logic_vector(23 downto 0);                     -- araddr
			lwhps2fpga_arlen           : out   std_logic_vector(7 downto 0);                      -- arlen
			lwhps2fpga_arsize          : out   std_logic_vector(2 downto 0);                      -- arsize
			lwhps2fpga_arburst         : out   std_logic_vector(1 downto 0);                      -- arburst
			lwhps2fpga_arlock          : out   std_logic;                                         -- arlock
			lwhps2fpga_arcache         : out   std_logic_vector(3 downto 0);                      -- arcache
			lwhps2fpga_arprot          : out   std_logic_vector(2 downto 0);                      -- arprot
			lwhps2fpga_arvalid         : out   std_logic;                                         -- arvalid
			lwhps2fpga_arready         : in    std_logic                      := 'X';             -- arready
			lwhps2fpga_rid             : in    std_logic_vector(3 downto 0)   := (others => 'X'); -- rid
			lwhps2fpga_rdata           : in    std_logic_vector(31 downto 0)  := (others => 'X'); -- rdata
			lwhps2fpga_rresp           : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- rresp
			lwhps2fpga_rlast           : in    std_logic                      := 'X';             -- rlast
			lwhps2fpga_rvalid          : in    std_logic                      := 'X';             -- rvalid
			lwhps2fpga_rready          : out   std_logic;                                         -- rready
			hps_io_gpio41              : inout std_logic                      := 'X'              -- gpio41
		);
	end component HPS_QSYS_intel_agilex_5_soc_0_cmp;

	component HPS_QSYS_intel_onchip_memory_0_cmp is
		port (
			clk        : in  std_logic                     := 'X';             -- clk
			s1_arid    : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- arid
			s1_araddr  : in  std_logic_vector(11 downto 0) := (others => 'X'); -- araddr
			s1_arlen   : in  std_logic_vector(7 downto 0)  := (others => 'X'); -- arlen
			s1_arsize  : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- arsize
			s1_arburst : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- arburst
			s1_arready : out std_logic;                                        -- arready
			s1_arvalid : in  std_logic                     := 'X';             -- arvalid
			s1_awid    : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- awid
			s1_awaddr  : in  std_logic_vector(11 downto 0) := (others => 'X'); -- awaddr
			s1_awlen   : in  std_logic_vector(7 downto 0)  := (others => 'X'); -- awlen
			s1_awsize  : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- awsize
			s1_awburst : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- awburst
			s1_awready : out std_logic;                                        -- awready
			s1_awvalid : in  std_logic                     := 'X';             -- awvalid
			s1_rid     : out std_logic_vector(3 downto 0);                     -- rid
			s1_rdata   : out std_logic_vector(31 downto 0);                    -- rdata
			s1_rlast   : out std_logic;                                        -- rlast
			s1_rready  : in  std_logic                     := 'X';             -- rready
			s1_rvalid  : out std_logic;                                        -- rvalid
			s1_rresp   : out std_logic_vector(1 downto 0);                     -- rresp
			s1_wdata   : in  std_logic_vector(31 downto 0) := (others => 'X'); -- wdata
			s1_wstrb   : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- wstrb
			s1_wlast   : in  std_logic                     := 'X';             -- wlast
			s1_wready  : out std_logic;                                        -- wready
			s1_wvalid  : in  std_logic                     := 'X';             -- wvalid
			s1_bid     : out std_logic_vector(3 downto 0);                     -- bid
			s1_bresp   : out std_logic_vector(1 downto 0);                     -- bresp
			s1_bready  : in  std_logic                     := 'X';             -- bready
			s1_bvalid  : out std_logic;                                        -- bvalid
			reset      : in  std_logic                     := 'X'              -- reset
		);
	end component HPS_QSYS_intel_onchip_memory_0_cmp;

	component HPS_QSYS_iopll_0_cmp is
		port (
			refclk   : in  std_logic := 'X'; -- clk
			locked   : out std_logic;        -- export
			rst      : in  std_logic := 'X'; -- reset
			outclk_0 : out std_logic         -- clk
		);
	end component HPS_QSYS_iopll_0_cmp;

	component HPS_QSYS_reset_bridge_0_cmp is
		port (
			clk         : in  std_logic := 'X'; -- clk
			in_reset_n  : in  std_logic := 'X'; -- reset_n
			out_reset_n : out std_logic         -- reset_n
		);
	end component HPS_QSYS_reset_bridge_0_cmp;

	component HPS_QSYS_altera_mm_interconnect_1920_474ciwq_cmp is
		port (
			intel_agilex_5_soc_0_lwhps2fpga_awid                                             : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- awid
			intel_agilex_5_soc_0_lwhps2fpga_awaddr                                           : in  std_logic_vector(23 downto 0) := (others => 'X'); -- awaddr
			intel_agilex_5_soc_0_lwhps2fpga_awlen                                            : in  std_logic_vector(7 downto 0)  := (others => 'X'); -- awlen
			intel_agilex_5_soc_0_lwhps2fpga_awsize                                           : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- awsize
			intel_agilex_5_soc_0_lwhps2fpga_awburst                                          : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- awburst
			intel_agilex_5_soc_0_lwhps2fpga_awlock                                           : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- awlock
			intel_agilex_5_soc_0_lwhps2fpga_awcache                                          : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- awcache
			intel_agilex_5_soc_0_lwhps2fpga_awprot                                           : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- awprot
			intel_agilex_5_soc_0_lwhps2fpga_awvalid                                          : in  std_logic                     := 'X';             -- awvalid
			intel_agilex_5_soc_0_lwhps2fpga_awready                                          : out std_logic;                                        -- awready
			intel_agilex_5_soc_0_lwhps2fpga_wdata                                            : in  std_logic_vector(31 downto 0) := (others => 'X'); -- wdata
			intel_agilex_5_soc_0_lwhps2fpga_wstrb                                            : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- wstrb
			intel_agilex_5_soc_0_lwhps2fpga_wlast                                            : in  std_logic                     := 'X';             -- wlast
			intel_agilex_5_soc_0_lwhps2fpga_wvalid                                           : in  std_logic                     := 'X';             -- wvalid
			intel_agilex_5_soc_0_lwhps2fpga_wready                                           : out std_logic;                                        -- wready
			intel_agilex_5_soc_0_lwhps2fpga_bid                                              : out std_logic_vector(3 downto 0);                     -- bid
			intel_agilex_5_soc_0_lwhps2fpga_bresp                                            : out std_logic_vector(1 downto 0);                     -- bresp
			intel_agilex_5_soc_0_lwhps2fpga_bvalid                                           : out std_logic;                                        -- bvalid
			intel_agilex_5_soc_0_lwhps2fpga_bready                                           : in  std_logic                     := 'X';             -- bready
			intel_agilex_5_soc_0_lwhps2fpga_arid                                             : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- arid
			intel_agilex_5_soc_0_lwhps2fpga_araddr                                           : in  std_logic_vector(23 downto 0) := (others => 'X'); -- araddr
			intel_agilex_5_soc_0_lwhps2fpga_arlen                                            : in  std_logic_vector(7 downto 0)  := (others => 'X'); -- arlen
			intel_agilex_5_soc_0_lwhps2fpga_arsize                                           : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- arsize
			intel_agilex_5_soc_0_lwhps2fpga_arburst                                          : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- arburst
			intel_agilex_5_soc_0_lwhps2fpga_arlock                                           : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- arlock
			intel_agilex_5_soc_0_lwhps2fpga_arcache                                          : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- arcache
			intel_agilex_5_soc_0_lwhps2fpga_arprot                                           : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- arprot
			intel_agilex_5_soc_0_lwhps2fpga_arvalid                                          : in  std_logic                     := 'X';             -- arvalid
			intel_agilex_5_soc_0_lwhps2fpga_arready                                          : out std_logic;                                        -- arready
			intel_agilex_5_soc_0_lwhps2fpga_rid                                              : out std_logic_vector(3 downto 0);                     -- rid
			intel_agilex_5_soc_0_lwhps2fpga_rdata                                            : out std_logic_vector(31 downto 0);                    -- rdata
			intel_agilex_5_soc_0_lwhps2fpga_rresp                                            : out std_logic_vector(1 downto 0);                     -- rresp
			intel_agilex_5_soc_0_lwhps2fpga_rlast                                            : out std_logic;                                        -- rlast
			intel_agilex_5_soc_0_lwhps2fpga_rvalid                                           : out std_logic;                                        -- rvalid
			intel_agilex_5_soc_0_lwhps2fpga_rready                                           : in  std_logic                     := 'X';             -- rready
			intel_onchip_memory_0_axi_s1_awid                                                : out std_logic_vector(3 downto 0);                     -- awid
			intel_onchip_memory_0_axi_s1_awaddr                                              : out std_logic_vector(11 downto 0);                    -- awaddr
			intel_onchip_memory_0_axi_s1_awlen                                               : out std_logic_vector(7 downto 0);                     -- awlen
			intel_onchip_memory_0_axi_s1_awsize                                              : out std_logic_vector(2 downto 0);                     -- awsize
			intel_onchip_memory_0_axi_s1_awburst                                             : out std_logic_vector(1 downto 0);                     -- awburst
			intel_onchip_memory_0_axi_s1_awvalid                                             : out std_logic;                                        -- awvalid
			intel_onchip_memory_0_axi_s1_awready                                             : in  std_logic                     := 'X';             -- awready
			intel_onchip_memory_0_axi_s1_wdata                                               : out std_logic_vector(31 downto 0);                    -- wdata
			intel_onchip_memory_0_axi_s1_wstrb                                               : out std_logic_vector(3 downto 0);                     -- wstrb
			intel_onchip_memory_0_axi_s1_wlast                                               : out std_logic;                                        -- wlast
			intel_onchip_memory_0_axi_s1_wvalid                                              : out std_logic;                                        -- wvalid
			intel_onchip_memory_0_axi_s1_wready                                              : in  std_logic                     := 'X';             -- wready
			intel_onchip_memory_0_axi_s1_bid                                                 : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- bid
			intel_onchip_memory_0_axi_s1_bresp                                               : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- bresp
			intel_onchip_memory_0_axi_s1_bvalid                                              : in  std_logic                     := 'X';             -- bvalid
			intel_onchip_memory_0_axi_s1_bready                                              : out std_logic;                                        -- bready
			intel_onchip_memory_0_axi_s1_arid                                                : out std_logic_vector(3 downto 0);                     -- arid
			intel_onchip_memory_0_axi_s1_araddr                                              : out std_logic_vector(11 downto 0);                    -- araddr
			intel_onchip_memory_0_axi_s1_arlen                                               : out std_logic_vector(7 downto 0);                     -- arlen
			intel_onchip_memory_0_axi_s1_arsize                                              : out std_logic_vector(2 downto 0);                     -- arsize
			intel_onchip_memory_0_axi_s1_arburst                                             : out std_logic_vector(1 downto 0);                     -- arburst
			intel_onchip_memory_0_axi_s1_arvalid                                             : out std_logic;                                        -- arvalid
			intel_onchip_memory_0_axi_s1_arready                                             : in  std_logic                     := 'X';             -- arready
			intel_onchip_memory_0_axi_s1_rid                                                 : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- rid
			intel_onchip_memory_0_axi_s1_rdata                                               : in  std_logic_vector(31 downto 0) := (others => 'X'); -- rdata
			intel_onchip_memory_0_axi_s1_rresp                                               : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- rresp
			intel_onchip_memory_0_axi_s1_rlast                                               : in  std_logic                     := 'X';             -- rlast
			intel_onchip_memory_0_axi_s1_rvalid                                              : in  std_logic                     := 'X';             -- rvalid
			intel_onchip_memory_0_axi_s1_rready                                              : out std_logic;                                        -- rready
			intel_agilex_5_soc_0_lwhps2fpga_translator_clk_reset_reset_bridge_in_reset_reset : in  std_logic                     := 'X';             -- reset
			intel_onchip_memory_0_axi_s1_translator_clk_reset_reset_bridge_in_reset_reset    : in  std_logic                     := 'X';             -- reset
			iopll_0_outclk0_clk                                                              : in  std_logic                     := 'X'              -- clk
		);
	end component HPS_QSYS_altera_mm_interconnect_1920_474ciwq_cmp;

	component altera_reset_controller_cmp is
		generic (
			NUM_RESET_INPUTS          : integer := 6;
			OUTPUT_RESET_SYNC_EDGES   : string  := "deassert";
			SYNC_DEPTH                : integer := 2;
			RESET_REQUEST_PRESENT     : integer := 0;
			RESET_REQ_WAIT_TIME       : integer := 1;
			MIN_RST_ASSERTION_TIME    : integer := 3;
			RESET_REQ_EARLY_DSRT_TIME : integer := 1;
			USE_RESET_REQUEST_IN0     : integer := 0;
			USE_RESET_REQUEST_IN1     : integer := 0;
			USE_RESET_REQUEST_IN2     : integer := 0;
			USE_RESET_REQUEST_IN3     : integer := 0;
			USE_RESET_REQUEST_IN4     : integer := 0;
			USE_RESET_REQUEST_IN5     : integer := 0;
			USE_RESET_REQUEST_IN6     : integer := 0;
			USE_RESET_REQUEST_IN7     : integer := 0;
			USE_RESET_REQUEST_IN8     : integer := 0;
			USE_RESET_REQUEST_IN9     : integer := 0;
			USE_RESET_REQUEST_IN10    : integer := 0;
			USE_RESET_REQUEST_IN11    : integer := 0;
			USE_RESET_REQUEST_IN12    : integer := 0;
			USE_RESET_REQUEST_IN13    : integer := 0;
			USE_RESET_REQUEST_IN14    : integer := 0;
			USE_RESET_REQUEST_IN15    : integer := 0;
			ADAPT_RESET_REQUEST       : integer := 0
		);
		port (
			reset_in0      : in  std_logic := 'X'; -- reset
			clk            : in  std_logic := 'X'; -- clk
			reset_out      : out std_logic;        -- reset
			reset_req      : out std_logic;        -- reset_req
			reset_req_in0  : in  std_logic := 'X'; -- reset_req
			reset_in1      : in  std_logic := 'X'; -- reset
			reset_req_in1  : in  std_logic := 'X'; -- reset_req
			reset_in2      : in  std_logic := 'X'; -- reset
			reset_req_in2  : in  std_logic := 'X'; -- reset_req
			reset_in3      : in  std_logic := 'X'; -- reset
			reset_req_in3  : in  std_logic := 'X'; -- reset_req
			reset_in4      : in  std_logic := 'X'; -- reset
			reset_req_in4  : in  std_logic := 'X'; -- reset_req
			reset_in5      : in  std_logic := 'X'; -- reset
			reset_req_in5  : in  std_logic := 'X'; -- reset_req
			reset_in6      : in  std_logic := 'X'; -- reset
			reset_req_in6  : in  std_logic := 'X'; -- reset_req
			reset_in7      : in  std_logic := 'X'; -- reset
			reset_req_in7  : in  std_logic := 'X'; -- reset_req
			reset_in8      : in  std_logic := 'X'; -- reset
			reset_req_in8  : in  std_logic := 'X'; -- reset_req
			reset_in9      : in  std_logic := 'X'; -- reset
			reset_req_in9  : in  std_logic := 'X'; -- reset_req
			reset_in10     : in  std_logic := 'X'; -- reset
			reset_req_in10 : in  std_logic := 'X'; -- reset_req
			reset_in11     : in  std_logic := 'X'; -- reset
			reset_req_in11 : in  std_logic := 'X'; -- reset_req
			reset_in12     : in  std_logic := 'X'; -- reset
			reset_req_in12 : in  std_logic := 'X'; -- reset_req
			reset_in13     : in  std_logic := 'X'; -- reset
			reset_req_in13 : in  std_logic := 'X'; -- reset_req
			reset_in14     : in  std_logic := 'X'; -- reset
			reset_req_in14 : in  std_logic := 'X'; -- reset_req
			reset_in15     : in  std_logic := 'X'; -- reset
			reset_req_in15 : in  std_logic := 'X'  -- reset_req
		);
	end component altera_reset_controller_cmp;

	signal iopll_0_outclk0_clk                                    : std_logic;                     -- iopll_0:outclk_0 -> [intel_agilex_5_soc_0:hps2fpga_axi_clock_clk, intel_agilex_5_soc_0:lwhps2fpga_axi_clock_clk, intel_onchip_memory_0:clk, mm_interconnect_0:iopll_0_outclk0_clk, reset_bridge_0:clk, rst_controller:clk, rst_controller_001:clk]
	signal intel_agilex_5_soc_0_h2f_reset_reset                   : std_logic;                     -- intel_agilex_5_soc_0:h2f_reset_reset -> [intel_agilex_5_soc_0:hps2fpga_axi_reset_reset, intel_agilex_5_soc_0:lwhps2fpga_axi_reset_reset, rst_controller:reset_in0]
	signal reset_bridge_0_out_reset_reset                         : std_logic;                     -- reset_bridge_0:out_reset_n -> reset_bridge_0_out_reset_reset:in
	signal intel_agilex_5_soc_0_lwhps2fpga_awburst                : std_logic_vector(1 downto 0);  -- intel_agilex_5_soc_0:lwhps2fpga_awburst -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_awburst
	signal intel_agilex_5_soc_0_lwhps2fpga_arlen                  : std_logic_vector(7 downto 0);  -- intel_agilex_5_soc_0:lwhps2fpga_arlen -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_arlen
	signal intel_agilex_5_soc_0_lwhps2fpga_wstrb                  : std_logic_vector(3 downto 0);  -- intel_agilex_5_soc_0:lwhps2fpga_wstrb -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_wstrb
	signal intel_agilex_5_soc_0_lwhps2fpga_wready                 : std_logic;                     -- mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_wready -> intel_agilex_5_soc_0:lwhps2fpga_wready
	signal intel_agilex_5_soc_0_lwhps2fpga_rid                    : std_logic_vector(3 downto 0);  -- mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_rid -> intel_agilex_5_soc_0:lwhps2fpga_rid
	signal intel_agilex_5_soc_0_lwhps2fpga_rready                 : std_logic;                     -- intel_agilex_5_soc_0:lwhps2fpga_rready -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_rready
	signal intel_agilex_5_soc_0_lwhps2fpga_awlen                  : std_logic_vector(7 downto 0);  -- intel_agilex_5_soc_0:lwhps2fpga_awlen -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_awlen
	signal intel_agilex_5_soc_0_lwhps2fpga_arcache                : std_logic_vector(3 downto 0);  -- intel_agilex_5_soc_0:lwhps2fpga_arcache -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_arcache
	signal intel_agilex_5_soc_0_lwhps2fpga_wvalid                 : std_logic;                     -- intel_agilex_5_soc_0:lwhps2fpga_wvalid -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_wvalid
	signal intel_agilex_5_soc_0_lwhps2fpga_araddr                 : std_logic_vector(23 downto 0); -- intel_agilex_5_soc_0:lwhps2fpga_araddr -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_araddr
	signal intel_agilex_5_soc_0_lwhps2fpga_arprot                 : std_logic_vector(2 downto 0);  -- intel_agilex_5_soc_0:lwhps2fpga_arprot -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_arprot
	signal intel_agilex_5_soc_0_lwhps2fpga_awprot                 : std_logic_vector(2 downto 0);  -- intel_agilex_5_soc_0:lwhps2fpga_awprot -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_awprot
	signal intel_agilex_5_soc_0_lwhps2fpga_wdata                  : std_logic_vector(31 downto 0); -- intel_agilex_5_soc_0:lwhps2fpga_wdata -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_wdata
	signal intel_agilex_5_soc_0_lwhps2fpga_arvalid                : std_logic;                     -- intel_agilex_5_soc_0:lwhps2fpga_arvalid -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_arvalid
	signal intel_agilex_5_soc_0_lwhps2fpga_awcache                : std_logic_vector(3 downto 0);  -- intel_agilex_5_soc_0:lwhps2fpga_awcache -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_awcache
	signal intel_agilex_5_soc_0_lwhps2fpga_arid                   : std_logic_vector(3 downto 0);  -- intel_agilex_5_soc_0:lwhps2fpga_arid -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_arid
	signal intel_agilex_5_soc_0_lwhps2fpga_arlock                 : std_logic;                     -- intel_agilex_5_soc_0:lwhps2fpga_arlock -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_arlock
	signal intel_agilex_5_soc_0_lwhps2fpga_awlock                 : std_logic;                     -- intel_agilex_5_soc_0:lwhps2fpga_awlock -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_awlock
	signal intel_agilex_5_soc_0_lwhps2fpga_awaddr                 : std_logic_vector(23 downto 0); -- intel_agilex_5_soc_0:lwhps2fpga_awaddr -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_awaddr
	signal intel_agilex_5_soc_0_lwhps2fpga_bresp                  : std_logic_vector(1 downto 0);  -- mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_bresp -> intel_agilex_5_soc_0:lwhps2fpga_bresp
	signal intel_agilex_5_soc_0_lwhps2fpga_arready                : std_logic;                     -- mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_arready -> intel_agilex_5_soc_0:lwhps2fpga_arready
	signal intel_agilex_5_soc_0_lwhps2fpga_rdata                  : std_logic_vector(31 downto 0); -- mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_rdata -> intel_agilex_5_soc_0:lwhps2fpga_rdata
	signal intel_agilex_5_soc_0_lwhps2fpga_awready                : std_logic;                     -- mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_awready -> intel_agilex_5_soc_0:lwhps2fpga_awready
	signal intel_agilex_5_soc_0_lwhps2fpga_arburst                : std_logic_vector(1 downto 0);  -- intel_agilex_5_soc_0:lwhps2fpga_arburst -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_arburst
	signal intel_agilex_5_soc_0_lwhps2fpga_arsize                 : std_logic_vector(2 downto 0);  -- intel_agilex_5_soc_0:lwhps2fpga_arsize -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_arsize
	signal intel_agilex_5_soc_0_lwhps2fpga_bready                 : std_logic;                     -- intel_agilex_5_soc_0:lwhps2fpga_bready -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_bready
	signal intel_agilex_5_soc_0_lwhps2fpga_rlast                  : std_logic;                     -- mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_rlast -> intel_agilex_5_soc_0:lwhps2fpga_rlast
	signal intel_agilex_5_soc_0_lwhps2fpga_wlast                  : std_logic;                     -- intel_agilex_5_soc_0:lwhps2fpga_wlast -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_wlast
	signal intel_agilex_5_soc_0_lwhps2fpga_rresp                  : std_logic_vector(1 downto 0);  -- mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_rresp -> intel_agilex_5_soc_0:lwhps2fpga_rresp
	signal intel_agilex_5_soc_0_lwhps2fpga_awid                   : std_logic_vector(3 downto 0);  -- intel_agilex_5_soc_0:lwhps2fpga_awid -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_awid
	signal intel_agilex_5_soc_0_lwhps2fpga_bid                    : std_logic_vector(3 downto 0);  -- mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_bid -> intel_agilex_5_soc_0:lwhps2fpga_bid
	signal intel_agilex_5_soc_0_lwhps2fpga_bvalid                 : std_logic;                     -- mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_bvalid -> intel_agilex_5_soc_0:lwhps2fpga_bvalid
	signal intel_agilex_5_soc_0_lwhps2fpga_awsize                 : std_logic_vector(2 downto 0);  -- intel_agilex_5_soc_0:lwhps2fpga_awsize -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_awsize
	signal intel_agilex_5_soc_0_lwhps2fpga_awvalid                : std_logic;                     -- intel_agilex_5_soc_0:lwhps2fpga_awvalid -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_awvalid
	signal intel_agilex_5_soc_0_lwhps2fpga_rvalid                 : std_logic;                     -- mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_rvalid -> intel_agilex_5_soc_0:lwhps2fpga_rvalid
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_awburst : std_logic_vector(1 downto 0);  -- mm_interconnect_0:intel_onchip_memory_0_axi_s1_awburst -> intel_onchip_memory_0:s1_awburst
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_arlen   : std_logic_vector(7 downto 0);  -- mm_interconnect_0:intel_onchip_memory_0_axi_s1_arlen -> intel_onchip_memory_0:s1_arlen
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_wstrb   : std_logic_vector(3 downto 0);  -- mm_interconnect_0:intel_onchip_memory_0_axi_s1_wstrb -> intel_onchip_memory_0:s1_wstrb
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_wready  : std_logic;                     -- intel_onchip_memory_0:s1_wready -> mm_interconnect_0:intel_onchip_memory_0_axi_s1_wready
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_rid     : std_logic_vector(3 downto 0);  -- intel_onchip_memory_0:s1_rid -> mm_interconnect_0:intel_onchip_memory_0_axi_s1_rid
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_rready  : std_logic;                     -- mm_interconnect_0:intel_onchip_memory_0_axi_s1_rready -> intel_onchip_memory_0:s1_rready
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_awlen   : std_logic_vector(7 downto 0);  -- mm_interconnect_0:intel_onchip_memory_0_axi_s1_awlen -> intel_onchip_memory_0:s1_awlen
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_wvalid  : std_logic;                     -- mm_interconnect_0:intel_onchip_memory_0_axi_s1_wvalid -> intel_onchip_memory_0:s1_wvalid
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_araddr  : std_logic_vector(11 downto 0); -- mm_interconnect_0:intel_onchip_memory_0_axi_s1_araddr -> intel_onchip_memory_0:s1_araddr
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_wdata   : std_logic_vector(31 downto 0); -- mm_interconnect_0:intel_onchip_memory_0_axi_s1_wdata -> intel_onchip_memory_0:s1_wdata
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_arvalid : std_logic;                     -- mm_interconnect_0:intel_onchip_memory_0_axi_s1_arvalid -> intel_onchip_memory_0:s1_arvalid
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_arid    : std_logic_vector(3 downto 0);  -- mm_interconnect_0:intel_onchip_memory_0_axi_s1_arid -> intel_onchip_memory_0:s1_arid
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_awaddr  : std_logic_vector(11 downto 0); -- mm_interconnect_0:intel_onchip_memory_0_axi_s1_awaddr -> intel_onchip_memory_0:s1_awaddr
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_bresp   : std_logic_vector(1 downto 0);  -- intel_onchip_memory_0:s1_bresp -> mm_interconnect_0:intel_onchip_memory_0_axi_s1_bresp
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_arready : std_logic;                     -- intel_onchip_memory_0:s1_arready -> mm_interconnect_0:intel_onchip_memory_0_axi_s1_arready
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_rdata   : std_logic_vector(31 downto 0); -- intel_onchip_memory_0:s1_rdata -> mm_interconnect_0:intel_onchip_memory_0_axi_s1_rdata
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_awready : std_logic;                     -- intel_onchip_memory_0:s1_awready -> mm_interconnect_0:intel_onchip_memory_0_axi_s1_awready
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_arburst : std_logic_vector(1 downto 0);  -- mm_interconnect_0:intel_onchip_memory_0_axi_s1_arburst -> intel_onchip_memory_0:s1_arburst
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_arsize  : std_logic_vector(2 downto 0);  -- mm_interconnect_0:intel_onchip_memory_0_axi_s1_arsize -> intel_onchip_memory_0:s1_arsize
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_bready  : std_logic;                     -- mm_interconnect_0:intel_onchip_memory_0_axi_s1_bready -> intel_onchip_memory_0:s1_bready
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_rlast   : std_logic;                     -- intel_onchip_memory_0:s1_rlast -> mm_interconnect_0:intel_onchip_memory_0_axi_s1_rlast
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_wlast   : std_logic;                     -- mm_interconnect_0:intel_onchip_memory_0_axi_s1_wlast -> intel_onchip_memory_0:s1_wlast
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_rresp   : std_logic_vector(1 downto 0);  -- intel_onchip_memory_0:s1_rresp -> mm_interconnect_0:intel_onchip_memory_0_axi_s1_rresp
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_awid    : std_logic_vector(3 downto 0);  -- mm_interconnect_0:intel_onchip_memory_0_axi_s1_awid -> intel_onchip_memory_0:s1_awid
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_bid     : std_logic_vector(3 downto 0);  -- intel_onchip_memory_0:s1_bid -> mm_interconnect_0:intel_onchip_memory_0_axi_s1_bid
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_bvalid  : std_logic;                     -- intel_onchip_memory_0:s1_bvalid -> mm_interconnect_0:intel_onchip_memory_0_axi_s1_bvalid
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_awsize  : std_logic_vector(2 downto 0);  -- mm_interconnect_0:intel_onchip_memory_0_axi_s1_awsize -> intel_onchip_memory_0:s1_awsize
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_awvalid : std_logic;                     -- mm_interconnect_0:intel_onchip_memory_0_axi_s1_awvalid -> intel_onchip_memory_0:s1_awvalid
	signal mm_interconnect_0_intel_onchip_memory_0_axi_s1_rvalid  : std_logic;                     -- intel_onchip_memory_0:s1_rvalid -> mm_interconnect_0:intel_onchip_memory_0_axi_s1_rvalid
	signal rst_controller_reset_out_reset                         : std_logic;                     -- rst_controller:reset_out -> mm_interconnect_0:intel_agilex_5_soc_0_lwhps2fpga_translator_clk_reset_reset_bridge_in_reset_reset
	signal rst_controller_001_reset_out_reset                     : std_logic;                     -- rst_controller_001:reset_out -> mm_interconnect_0:intel_onchip_memory_0_axi_s1_translator_clk_reset_reset_bridge_in_reset_reset
	signal reset_bridge_0_out_reset_reset_ports_inv               : std_logic;                     -- reset_bridge_0_out_reset_reset:inv -> [intel_onchip_memory_0:reset, rst_controller_001:reset_in0]

	for intel_agilex_5_soc_0 : HPS_QSYS_intel_agilex_5_soc_0_cmp
		use entity HPS_QSYS_intel_agilex_5_soc_0.HPS_QSYS_intel_agilex_5_soc_0;
	for intel_onchip_memory_0 : HPS_QSYS_intel_onchip_memory_0_cmp
		use entity HPS_QSYS_intel_onchip_memory_0.HPS_QSYS_intel_onchip_memory_0;
	for iopll_0 : HPS_QSYS_iopll_0_cmp
		use entity HPS_QSYS_iopll_0.HPS_QSYS_iopll_0;
	for reset_bridge_0 : HPS_QSYS_reset_bridge_0_cmp
		use entity HPS_QSYS_reset_bridge_0.HPS_QSYS_reset_bridge_0;
	for mm_interconnect_0 : HPS_QSYS_altera_mm_interconnect_1920_474ciwq_cmp
		use entity altera_mm_interconnect_1920.HPS_QSYS_altera_mm_interconnect_1920_474ciwq;
	for rst_controller : altera_reset_controller_cmp
		use entity altera_reset_controller_1924.altera_reset_controller;
	for rst_controller_001 : altera_reset_controller_cmp
		use entity altera_reset_controller_1924.altera_reset_controller;
begin

	intel_agilex_5_soc_0 : component HPS_QSYS_intel_agilex_5_soc_0_cmp
		port map (
			h2f_reset_reset            => intel_agilex_5_soc_0_h2f_reset_reset,    --            h2f_reset.reset
			hps2fpga_axi_clock_clk     => iopll_0_outclk0_clk,                     --   hps2fpga_axi_clock.clk
			hps2fpga_axi_reset_reset   => intel_agilex_5_soc_0_h2f_reset_reset,    --   hps2fpga_axi_reset.reset
			hps2fpga_awid              => hps2fpga_awid,                           --             hps2fpga.awid
			hps2fpga_awaddr            => hps2fpga_awaddr,                         --                     .awaddr
			hps2fpga_awlen             => hps2fpga_awlen,                          --                     .awlen
			hps2fpga_awsize            => hps2fpga_awsize,                         --                     .awsize
			hps2fpga_awburst           => hps2fpga_awburst,                        --                     .awburst
			hps2fpga_awlock            => hps2fpga_awlock,                         --                     .awlock
			hps2fpga_awcache           => hps2fpga_awcache,                        --                     .awcache
			hps2fpga_awprot            => hps2fpga_awprot,                         --                     .awprot
			hps2fpga_awvalid           => hps2fpga_awvalid,                        --                     .awvalid
			hps2fpga_awready           => hps2fpga_awready,                        --                     .awready
			hps2fpga_wdata             => hps2fpga_wdata,                          --                     .wdata
			hps2fpga_wstrb             => hps2fpga_wstrb,                          --                     .wstrb
			hps2fpga_wlast             => hps2fpga_wlast,                          --                     .wlast
			hps2fpga_wvalid            => hps2fpga_wvalid,                         --                     .wvalid
			hps2fpga_wready            => hps2fpga_wready,                         --                     .wready
			hps2fpga_bid               => hps2fpga_bid,                            --                     .bid
			hps2fpga_bresp             => hps2fpga_bresp,                          --                     .bresp
			hps2fpga_bvalid            => hps2fpga_bvalid,                         --                     .bvalid
			hps2fpga_bready            => hps2fpga_bready,                         --                     .bready
			hps2fpga_arid              => hps2fpga_arid,                           --                     .arid
			hps2fpga_araddr            => hps2fpga_araddr,                         --                     .araddr
			hps2fpga_arlen             => hps2fpga_arlen,                          --                     .arlen
			hps2fpga_arsize            => hps2fpga_arsize,                         --                     .arsize
			hps2fpga_arburst           => hps2fpga_arburst,                        --                     .arburst
			hps2fpga_arlock            => hps2fpga_arlock,                         --                     .arlock
			hps2fpga_arcache           => hps2fpga_arcache,                        --                     .arcache
			hps2fpga_arprot            => hps2fpga_arprot,                         --                     .arprot
			hps2fpga_arvalid           => hps2fpga_arvalid,                        --                     .arvalid
			hps2fpga_arready           => hps2fpga_arready,                        --                     .arready
			hps2fpga_rid               => hps2fpga_rid,                            --                     .rid
			hps2fpga_rdata             => hps2fpga_rdata,                          --                     .rdata
			hps2fpga_rresp             => hps2fpga_rresp,                          --                     .rresp
			hps2fpga_rlast             => hps2fpga_rlast,                          --                     .rlast
			hps2fpga_rvalid            => hps2fpga_rvalid,                         --                     .rvalid
			hps2fpga_rready            => hps2fpga_rready,                         --                     .rready
			lwhps2fpga_axi_clock_clk   => iopll_0_outclk0_clk,                     -- lwhps2fpga_axi_clock.clk
			lwhps2fpga_axi_reset_reset => intel_agilex_5_soc_0_h2f_reset_reset,    -- lwhps2fpga_axi_reset.reset
			lwhps2fpga_awid            => intel_agilex_5_soc_0_lwhps2fpga_awid,    --           lwhps2fpga.awid
			lwhps2fpga_awaddr          => intel_agilex_5_soc_0_lwhps2fpga_awaddr,  --                     .awaddr
			lwhps2fpga_awlen           => intel_agilex_5_soc_0_lwhps2fpga_awlen,   --                     .awlen
			lwhps2fpga_awsize          => intel_agilex_5_soc_0_lwhps2fpga_awsize,  --                     .awsize
			lwhps2fpga_awburst         => intel_agilex_5_soc_0_lwhps2fpga_awburst, --                     .awburst
			lwhps2fpga_awlock          => intel_agilex_5_soc_0_lwhps2fpga_awlock,  --                     .awlock
			lwhps2fpga_awcache         => intel_agilex_5_soc_0_lwhps2fpga_awcache, --                     .awcache
			lwhps2fpga_awprot          => intel_agilex_5_soc_0_lwhps2fpga_awprot,  --                     .awprot
			lwhps2fpga_awvalid         => intel_agilex_5_soc_0_lwhps2fpga_awvalid, --                     .awvalid
			lwhps2fpga_awready         => intel_agilex_5_soc_0_lwhps2fpga_awready, --                     .awready
			lwhps2fpga_wdata           => intel_agilex_5_soc_0_lwhps2fpga_wdata,   --                     .wdata
			lwhps2fpga_wstrb           => intel_agilex_5_soc_0_lwhps2fpga_wstrb,   --                     .wstrb
			lwhps2fpga_wlast           => intel_agilex_5_soc_0_lwhps2fpga_wlast,   --                     .wlast
			lwhps2fpga_wvalid          => intel_agilex_5_soc_0_lwhps2fpga_wvalid,  --                     .wvalid
			lwhps2fpga_wready          => intel_agilex_5_soc_0_lwhps2fpga_wready,  --                     .wready
			lwhps2fpga_bid             => intel_agilex_5_soc_0_lwhps2fpga_bid,     --                     .bid
			lwhps2fpga_bresp           => intel_agilex_5_soc_0_lwhps2fpga_bresp,   --                     .bresp
			lwhps2fpga_bvalid          => intel_agilex_5_soc_0_lwhps2fpga_bvalid,  --                     .bvalid
			lwhps2fpga_bready          => intel_agilex_5_soc_0_lwhps2fpga_bready,  --                     .bready
			lwhps2fpga_arid            => intel_agilex_5_soc_0_lwhps2fpga_arid,    --                     .arid
			lwhps2fpga_araddr          => intel_agilex_5_soc_0_lwhps2fpga_araddr,  --                     .araddr
			lwhps2fpga_arlen           => intel_agilex_5_soc_0_lwhps2fpga_arlen,   --                     .arlen
			lwhps2fpga_arsize          => intel_agilex_5_soc_0_lwhps2fpga_arsize,  --                     .arsize
			lwhps2fpga_arburst         => intel_agilex_5_soc_0_lwhps2fpga_arburst, --                     .arburst
			lwhps2fpga_arlock          => intel_agilex_5_soc_0_lwhps2fpga_arlock,  --                     .arlock
			lwhps2fpga_arcache         => intel_agilex_5_soc_0_lwhps2fpga_arcache, --                     .arcache
			lwhps2fpga_arprot          => intel_agilex_5_soc_0_lwhps2fpga_arprot,  --                     .arprot
			lwhps2fpga_arvalid         => intel_agilex_5_soc_0_lwhps2fpga_arvalid, --                     .arvalid
			lwhps2fpga_arready         => intel_agilex_5_soc_0_lwhps2fpga_arready, --                     .arready
			lwhps2fpga_rid             => intel_agilex_5_soc_0_lwhps2fpga_rid,     --                     .rid
			lwhps2fpga_rdata           => intel_agilex_5_soc_0_lwhps2fpga_rdata,   --                     .rdata
			lwhps2fpga_rresp           => intel_agilex_5_soc_0_lwhps2fpga_rresp,   --                     .rresp
			lwhps2fpga_rlast           => intel_agilex_5_soc_0_lwhps2fpga_rlast,   --                     .rlast
			lwhps2fpga_rvalid          => intel_agilex_5_soc_0_lwhps2fpga_rvalid,  --                     .rvalid
			lwhps2fpga_rready          => intel_agilex_5_soc_0_lwhps2fpga_rready,  --                     .rready
			hps_io_gpio41              => hps_io_gpio41                            --               hps_io.gpio41
		);

	intel_onchip_memory_0 : component HPS_QSYS_intel_onchip_memory_0_cmp
		port map (
			clk        => iopll_0_outclk0_clk,                                    --   clk1.clk
			s1_arid    => mm_interconnect_0_intel_onchip_memory_0_axi_s1_arid,    -- axi_s1.arid
			s1_araddr  => mm_interconnect_0_intel_onchip_memory_0_axi_s1_araddr,  --       .araddr
			s1_arlen   => mm_interconnect_0_intel_onchip_memory_0_axi_s1_arlen,   --       .arlen
			s1_arsize  => mm_interconnect_0_intel_onchip_memory_0_axi_s1_arsize,  --       .arsize
			s1_arburst => mm_interconnect_0_intel_onchip_memory_0_axi_s1_arburst, --       .arburst
			s1_arready => mm_interconnect_0_intel_onchip_memory_0_axi_s1_arready, --       .arready
			s1_arvalid => mm_interconnect_0_intel_onchip_memory_0_axi_s1_arvalid, --       .arvalid
			s1_awid    => mm_interconnect_0_intel_onchip_memory_0_axi_s1_awid,    --       .awid
			s1_awaddr  => mm_interconnect_0_intel_onchip_memory_0_axi_s1_awaddr,  --       .awaddr
			s1_awlen   => mm_interconnect_0_intel_onchip_memory_0_axi_s1_awlen,   --       .awlen
			s1_awsize  => mm_interconnect_0_intel_onchip_memory_0_axi_s1_awsize,  --       .awsize
			s1_awburst => mm_interconnect_0_intel_onchip_memory_0_axi_s1_awburst, --       .awburst
			s1_awready => mm_interconnect_0_intel_onchip_memory_0_axi_s1_awready, --       .awready
			s1_awvalid => mm_interconnect_0_intel_onchip_memory_0_axi_s1_awvalid, --       .awvalid
			s1_rid     => mm_interconnect_0_intel_onchip_memory_0_axi_s1_rid,     --       .rid
			s1_rdata   => mm_interconnect_0_intel_onchip_memory_0_axi_s1_rdata,   --       .rdata
			s1_rlast   => mm_interconnect_0_intel_onchip_memory_0_axi_s1_rlast,   --       .rlast
			s1_rready  => mm_interconnect_0_intel_onchip_memory_0_axi_s1_rready,  --       .rready
			s1_rvalid  => mm_interconnect_0_intel_onchip_memory_0_axi_s1_rvalid,  --       .rvalid
			s1_rresp   => mm_interconnect_0_intel_onchip_memory_0_axi_s1_rresp,   --       .rresp
			s1_wdata   => mm_interconnect_0_intel_onchip_memory_0_axi_s1_wdata,   --       .wdata
			s1_wstrb   => mm_interconnect_0_intel_onchip_memory_0_axi_s1_wstrb,   --       .wstrb
			s1_wlast   => mm_interconnect_0_intel_onchip_memory_0_axi_s1_wlast,   --       .wlast
			s1_wready  => mm_interconnect_0_intel_onchip_memory_0_axi_s1_wready,  --       .wready
			s1_wvalid  => mm_interconnect_0_intel_onchip_memory_0_axi_s1_wvalid,  --       .wvalid
			s1_bid     => mm_interconnect_0_intel_onchip_memory_0_axi_s1_bid,     --       .bid
			s1_bresp   => mm_interconnect_0_intel_onchip_memory_0_axi_s1_bresp,   --       .bresp
			s1_bready  => mm_interconnect_0_intel_onchip_memory_0_axi_s1_bready,  --       .bready
			s1_bvalid  => mm_interconnect_0_intel_onchip_memory_0_axi_s1_bvalid,  --       .bvalid
			reset      => reset_bridge_0_out_reset_reset_ports_inv                -- reset1.reset
		);

	iopll_0 : component HPS_QSYS_iopll_0_cmp
		port map (
			refclk   => refclk_clk,          --  refclk.clk
			locked   => locked_export,       --  locked.export
			rst      => reset_reset,         --   reset.reset
			outclk_0 => iopll_0_outclk0_clk  -- outclk0.clk
		);

	reset_bridge_0 : component HPS_QSYS_reset_bridge_0_cmp
		port map (
			clk         => iopll_0_outclk0_clk,            --       clk.clk
			in_reset_n  => in_reset_reset_n,               --  in_reset.reset_n
			out_reset_n => reset_bridge_0_out_reset_reset  -- out_reset.reset_n
		);

	mm_interconnect_0 : component HPS_QSYS_altera_mm_interconnect_1920_474ciwq_cmp
		port map (
			intel_agilex_5_soc_0_lwhps2fpga_awid                                             => intel_agilex_5_soc_0_lwhps2fpga_awid,                   --                                            intel_agilex_5_soc_0_lwhps2fpga.awid
			intel_agilex_5_soc_0_lwhps2fpga_awaddr                                           => intel_agilex_5_soc_0_lwhps2fpga_awaddr,                 --                                                                           .awaddr
			intel_agilex_5_soc_0_lwhps2fpga_awlen                                            => intel_agilex_5_soc_0_lwhps2fpga_awlen,                  --                                                                           .awlen
			intel_agilex_5_soc_0_lwhps2fpga_awsize                                           => intel_agilex_5_soc_0_lwhps2fpga_awsize,                 --                                                                           .awsize
			intel_agilex_5_soc_0_lwhps2fpga_awburst                                          => intel_agilex_5_soc_0_lwhps2fpga_awburst,                --                                                                           .awburst
			intel_agilex_5_soc_0_lwhps2fpga_awlock(0)                                        => intel_agilex_5_soc_0_lwhps2fpga_awlock,                 --                                                                           .awlock
			intel_agilex_5_soc_0_lwhps2fpga_awcache                                          => intel_agilex_5_soc_0_lwhps2fpga_awcache,                --                                                                           .awcache
			intel_agilex_5_soc_0_lwhps2fpga_awprot                                           => intel_agilex_5_soc_0_lwhps2fpga_awprot,                 --                                                                           .awprot
			intel_agilex_5_soc_0_lwhps2fpga_awvalid                                          => intel_agilex_5_soc_0_lwhps2fpga_awvalid,                --                                                                           .awvalid
			intel_agilex_5_soc_0_lwhps2fpga_awready                                          => intel_agilex_5_soc_0_lwhps2fpga_awready,                --                                                                           .awready
			intel_agilex_5_soc_0_lwhps2fpga_wdata                                            => intel_agilex_5_soc_0_lwhps2fpga_wdata,                  --                                                                           .wdata
			intel_agilex_5_soc_0_lwhps2fpga_wstrb                                            => intel_agilex_5_soc_0_lwhps2fpga_wstrb,                  --                                                                           .wstrb
			intel_agilex_5_soc_0_lwhps2fpga_wlast                                            => intel_agilex_5_soc_0_lwhps2fpga_wlast,                  --                                                                           .wlast
			intel_agilex_5_soc_0_lwhps2fpga_wvalid                                           => intel_agilex_5_soc_0_lwhps2fpga_wvalid,                 --                                                                           .wvalid
			intel_agilex_5_soc_0_lwhps2fpga_wready                                           => intel_agilex_5_soc_0_lwhps2fpga_wready,                 --                                                                           .wready
			intel_agilex_5_soc_0_lwhps2fpga_bid                                              => intel_agilex_5_soc_0_lwhps2fpga_bid,                    --                                                                           .bid
			intel_agilex_5_soc_0_lwhps2fpga_bresp                                            => intel_agilex_5_soc_0_lwhps2fpga_bresp,                  --                                                                           .bresp
			intel_agilex_5_soc_0_lwhps2fpga_bvalid                                           => intel_agilex_5_soc_0_lwhps2fpga_bvalid,                 --                                                                           .bvalid
			intel_agilex_5_soc_0_lwhps2fpga_bready                                           => intel_agilex_5_soc_0_lwhps2fpga_bready,                 --                                                                           .bready
			intel_agilex_5_soc_0_lwhps2fpga_arid                                             => intel_agilex_5_soc_0_lwhps2fpga_arid,                   --                                                                           .arid
			intel_agilex_5_soc_0_lwhps2fpga_araddr                                           => intel_agilex_5_soc_0_lwhps2fpga_araddr,                 --                                                                           .araddr
			intel_agilex_5_soc_0_lwhps2fpga_arlen                                            => intel_agilex_5_soc_0_lwhps2fpga_arlen,                  --                                                                           .arlen
			intel_agilex_5_soc_0_lwhps2fpga_arsize                                           => intel_agilex_5_soc_0_lwhps2fpga_arsize,                 --                                                                           .arsize
			intel_agilex_5_soc_0_lwhps2fpga_arburst                                          => intel_agilex_5_soc_0_lwhps2fpga_arburst,                --                                                                           .arburst
			intel_agilex_5_soc_0_lwhps2fpga_arlock(0)                                        => intel_agilex_5_soc_0_lwhps2fpga_arlock,                 --                                                                           .arlock
			intel_agilex_5_soc_0_lwhps2fpga_arcache                                          => intel_agilex_5_soc_0_lwhps2fpga_arcache,                --                                                                           .arcache
			intel_agilex_5_soc_0_lwhps2fpga_arprot                                           => intel_agilex_5_soc_0_lwhps2fpga_arprot,                 --                                                                           .arprot
			intel_agilex_5_soc_0_lwhps2fpga_arvalid                                          => intel_agilex_5_soc_0_lwhps2fpga_arvalid,                --                                                                           .arvalid
			intel_agilex_5_soc_0_lwhps2fpga_arready                                          => intel_agilex_5_soc_0_lwhps2fpga_arready,                --                                                                           .arready
			intel_agilex_5_soc_0_lwhps2fpga_rid                                              => intel_agilex_5_soc_0_lwhps2fpga_rid,                    --                                                                           .rid
			intel_agilex_5_soc_0_lwhps2fpga_rdata                                            => intel_agilex_5_soc_0_lwhps2fpga_rdata,                  --                                                                           .rdata
			intel_agilex_5_soc_0_lwhps2fpga_rresp                                            => intel_agilex_5_soc_0_lwhps2fpga_rresp,                  --                                                                           .rresp
			intel_agilex_5_soc_0_lwhps2fpga_rlast                                            => intel_agilex_5_soc_0_lwhps2fpga_rlast,                  --                                                                           .rlast
			intel_agilex_5_soc_0_lwhps2fpga_rvalid                                           => intel_agilex_5_soc_0_lwhps2fpga_rvalid,                 --                                                                           .rvalid
			intel_agilex_5_soc_0_lwhps2fpga_rready                                           => intel_agilex_5_soc_0_lwhps2fpga_rready,                 --                                                                           .rready
			intel_onchip_memory_0_axi_s1_awid                                                => mm_interconnect_0_intel_onchip_memory_0_axi_s1_awid,    --                                               intel_onchip_memory_0_axi_s1.awid
			intel_onchip_memory_0_axi_s1_awaddr                                              => mm_interconnect_0_intel_onchip_memory_0_axi_s1_awaddr,  --                                                                           .awaddr
			intel_onchip_memory_0_axi_s1_awlen                                               => mm_interconnect_0_intel_onchip_memory_0_axi_s1_awlen,   --                                                                           .awlen
			intel_onchip_memory_0_axi_s1_awsize                                              => mm_interconnect_0_intel_onchip_memory_0_axi_s1_awsize,  --                                                                           .awsize
			intel_onchip_memory_0_axi_s1_awburst                                             => mm_interconnect_0_intel_onchip_memory_0_axi_s1_awburst, --                                                                           .awburst
			intel_onchip_memory_0_axi_s1_awvalid                                             => mm_interconnect_0_intel_onchip_memory_0_axi_s1_awvalid, --                                                                           .awvalid
			intel_onchip_memory_0_axi_s1_awready                                             => mm_interconnect_0_intel_onchip_memory_0_axi_s1_awready, --                                                                           .awready
			intel_onchip_memory_0_axi_s1_wdata                                               => mm_interconnect_0_intel_onchip_memory_0_axi_s1_wdata,   --                                                                           .wdata
			intel_onchip_memory_0_axi_s1_wstrb                                               => mm_interconnect_0_intel_onchip_memory_0_axi_s1_wstrb,   --                                                                           .wstrb
			intel_onchip_memory_0_axi_s1_wlast                                               => mm_interconnect_0_intel_onchip_memory_0_axi_s1_wlast,   --                                                                           .wlast
			intel_onchip_memory_0_axi_s1_wvalid                                              => mm_interconnect_0_intel_onchip_memory_0_axi_s1_wvalid,  --                                                                           .wvalid
			intel_onchip_memory_0_axi_s1_wready                                              => mm_interconnect_0_intel_onchip_memory_0_axi_s1_wready,  --                                                                           .wready
			intel_onchip_memory_0_axi_s1_bid                                                 => mm_interconnect_0_intel_onchip_memory_0_axi_s1_bid,     --                                                                           .bid
			intel_onchip_memory_0_axi_s1_bresp                                               => mm_interconnect_0_intel_onchip_memory_0_axi_s1_bresp,   --                                                                           .bresp
			intel_onchip_memory_0_axi_s1_bvalid                                              => mm_interconnect_0_intel_onchip_memory_0_axi_s1_bvalid,  --                                                                           .bvalid
			intel_onchip_memory_0_axi_s1_bready                                              => mm_interconnect_0_intel_onchip_memory_0_axi_s1_bready,  --                                                                           .bready
			intel_onchip_memory_0_axi_s1_arid                                                => mm_interconnect_0_intel_onchip_memory_0_axi_s1_arid,    --                                                                           .arid
			intel_onchip_memory_0_axi_s1_araddr                                              => mm_interconnect_0_intel_onchip_memory_0_axi_s1_araddr,  --                                                                           .araddr
			intel_onchip_memory_0_axi_s1_arlen                                               => mm_interconnect_0_intel_onchip_memory_0_axi_s1_arlen,   --                                                                           .arlen
			intel_onchip_memory_0_axi_s1_arsize                                              => mm_interconnect_0_intel_onchip_memory_0_axi_s1_arsize,  --                                                                           .arsize
			intel_onchip_memory_0_axi_s1_arburst                                             => mm_interconnect_0_intel_onchip_memory_0_axi_s1_arburst, --                                                                           .arburst
			intel_onchip_memory_0_axi_s1_arvalid                                             => mm_interconnect_0_intel_onchip_memory_0_axi_s1_arvalid, --                                                                           .arvalid
			intel_onchip_memory_0_axi_s1_arready                                             => mm_interconnect_0_intel_onchip_memory_0_axi_s1_arready, --                                                                           .arready
			intel_onchip_memory_0_axi_s1_rid                                                 => mm_interconnect_0_intel_onchip_memory_0_axi_s1_rid,     --                                                                           .rid
			intel_onchip_memory_0_axi_s1_rdata                                               => mm_interconnect_0_intel_onchip_memory_0_axi_s1_rdata,   --                                                                           .rdata
			intel_onchip_memory_0_axi_s1_rresp                                               => mm_interconnect_0_intel_onchip_memory_0_axi_s1_rresp,   --                                                                           .rresp
			intel_onchip_memory_0_axi_s1_rlast                                               => mm_interconnect_0_intel_onchip_memory_0_axi_s1_rlast,   --                                                                           .rlast
			intel_onchip_memory_0_axi_s1_rvalid                                              => mm_interconnect_0_intel_onchip_memory_0_axi_s1_rvalid,  --                                                                           .rvalid
			intel_onchip_memory_0_axi_s1_rready                                              => mm_interconnect_0_intel_onchip_memory_0_axi_s1_rready,  --                                                                           .rready
			intel_agilex_5_soc_0_lwhps2fpga_translator_clk_reset_reset_bridge_in_reset_reset => rst_controller_reset_out_reset,                         -- intel_agilex_5_soc_0_lwhps2fpga_translator_clk_reset_reset_bridge_in_reset.reset
			intel_onchip_memory_0_axi_s1_translator_clk_reset_reset_bridge_in_reset_reset    => rst_controller_001_reset_out_reset,                     --    intel_onchip_memory_0_axi_s1_translator_clk_reset_reset_bridge_in_reset.reset
			iopll_0_outclk0_clk                                                              => iopll_0_outclk0_clk                                     --                                                            iopll_0_outclk0.clk
		);

	rst_controller : component altera_reset_controller_cmp
		generic map (
			NUM_RESET_INPUTS          => 1,
			OUTPUT_RESET_SYNC_EDGES   => "both",
			SYNC_DEPTH                => 2,
			RESET_REQUEST_PRESENT     => 0,
			RESET_REQ_WAIT_TIME       => 1,
			MIN_RST_ASSERTION_TIME    => 3,
			RESET_REQ_EARLY_DSRT_TIME => 1,
			USE_RESET_REQUEST_IN0     => 0,
			USE_RESET_REQUEST_IN1     => 0,
			USE_RESET_REQUEST_IN2     => 0,
			USE_RESET_REQUEST_IN3     => 0,
			USE_RESET_REQUEST_IN4     => 0,
			USE_RESET_REQUEST_IN5     => 0,
			USE_RESET_REQUEST_IN6     => 0,
			USE_RESET_REQUEST_IN7     => 0,
			USE_RESET_REQUEST_IN8     => 0,
			USE_RESET_REQUEST_IN9     => 0,
			USE_RESET_REQUEST_IN10    => 0,
			USE_RESET_REQUEST_IN11    => 0,
			USE_RESET_REQUEST_IN12    => 0,
			USE_RESET_REQUEST_IN13    => 0,
			USE_RESET_REQUEST_IN14    => 0,
			USE_RESET_REQUEST_IN15    => 0,
			ADAPT_RESET_REQUEST       => 0
		)
		port map (
			reset_in0      => intel_agilex_5_soc_0_h2f_reset_reset, -- reset_in0.reset
			clk            => iopll_0_outclk0_clk,                  --       clk.clk
			reset_out      => rst_controller_reset_out_reset,       -- reset_out.reset
			reset_req      => open,                                 -- (terminated)
			reset_req_in0  => '0',                                  -- (terminated)
			reset_in1      => '0',                                  -- (terminated)
			reset_req_in1  => '0',                                  -- (terminated)
			reset_in2      => '0',                                  -- (terminated)
			reset_req_in2  => '0',                                  -- (terminated)
			reset_in3      => '0',                                  -- (terminated)
			reset_req_in3  => '0',                                  -- (terminated)
			reset_in4      => '0',                                  -- (terminated)
			reset_req_in4  => '0',                                  -- (terminated)
			reset_in5      => '0',                                  -- (terminated)
			reset_req_in5  => '0',                                  -- (terminated)
			reset_in6      => '0',                                  -- (terminated)
			reset_req_in6  => '0',                                  -- (terminated)
			reset_in7      => '0',                                  -- (terminated)
			reset_req_in7  => '0',                                  -- (terminated)
			reset_in8      => '0',                                  -- (terminated)
			reset_req_in8  => '0',                                  -- (terminated)
			reset_in9      => '0',                                  -- (terminated)
			reset_req_in9  => '0',                                  -- (terminated)
			reset_in10     => '0',                                  -- (terminated)
			reset_req_in10 => '0',                                  -- (terminated)
			reset_in11     => '0',                                  -- (terminated)
			reset_req_in11 => '0',                                  -- (terminated)
			reset_in12     => '0',                                  -- (terminated)
			reset_req_in12 => '0',                                  -- (terminated)
			reset_in13     => '0',                                  -- (terminated)
			reset_req_in13 => '0',                                  -- (terminated)
			reset_in14     => '0',                                  -- (terminated)
			reset_req_in14 => '0',                                  -- (terminated)
			reset_in15     => '0',                                  -- (terminated)
			reset_req_in15 => '0'                                   -- (terminated)
		);

	rst_controller_001 : component altera_reset_controller_cmp
		generic map (
			NUM_RESET_INPUTS          => 1,
			OUTPUT_RESET_SYNC_EDGES   => "both",
			SYNC_DEPTH                => 2,
			RESET_REQUEST_PRESENT     => 0,
			RESET_REQ_WAIT_TIME       => 1,
			MIN_RST_ASSERTION_TIME    => 3,
			RESET_REQ_EARLY_DSRT_TIME => 1,
			USE_RESET_REQUEST_IN0     => 0,
			USE_RESET_REQUEST_IN1     => 0,
			USE_RESET_REQUEST_IN2     => 0,
			USE_RESET_REQUEST_IN3     => 0,
			USE_RESET_REQUEST_IN4     => 0,
			USE_RESET_REQUEST_IN5     => 0,
			USE_RESET_REQUEST_IN6     => 0,
			USE_RESET_REQUEST_IN7     => 0,
			USE_RESET_REQUEST_IN8     => 0,
			USE_RESET_REQUEST_IN9     => 0,
			USE_RESET_REQUEST_IN10    => 0,
			USE_RESET_REQUEST_IN11    => 0,
			USE_RESET_REQUEST_IN12    => 0,
			USE_RESET_REQUEST_IN13    => 0,
			USE_RESET_REQUEST_IN14    => 0,
			USE_RESET_REQUEST_IN15    => 0,
			ADAPT_RESET_REQUEST       => 0
		)
		port map (
			reset_in0      => reset_bridge_0_out_reset_reset_ports_inv, -- reset_in0.reset
			clk            => iopll_0_outclk0_clk,                      --       clk.clk
			reset_out      => rst_controller_001_reset_out_reset,       -- reset_out.reset
			reset_req      => open,                                     -- (terminated)
			reset_req_in0  => '0',                                      -- (terminated)
			reset_in1      => '0',                                      -- (terminated)
			reset_req_in1  => '0',                                      -- (terminated)
			reset_in2      => '0',                                      -- (terminated)
			reset_req_in2  => '0',                                      -- (terminated)
			reset_in3      => '0',                                      -- (terminated)
			reset_req_in3  => '0',                                      -- (terminated)
			reset_in4      => '0',                                      -- (terminated)
			reset_req_in4  => '0',                                      -- (terminated)
			reset_in5      => '0',                                      -- (terminated)
			reset_req_in5  => '0',                                      -- (terminated)
			reset_in6      => '0',                                      -- (terminated)
			reset_req_in6  => '0',                                      -- (terminated)
			reset_in7      => '0',                                      -- (terminated)
			reset_req_in7  => '0',                                      -- (terminated)
			reset_in8      => '0',                                      -- (terminated)
			reset_req_in8  => '0',                                      -- (terminated)
			reset_in9      => '0',                                      -- (terminated)
			reset_req_in9  => '0',                                      -- (terminated)
			reset_in10     => '0',                                      -- (terminated)
			reset_req_in10 => '0',                                      -- (terminated)
			reset_in11     => '0',                                      -- (terminated)
			reset_req_in11 => '0',                                      -- (terminated)
			reset_in12     => '0',                                      -- (terminated)
			reset_req_in12 => '0',                                      -- (terminated)
			reset_in13     => '0',                                      -- (terminated)
			reset_req_in13 => '0',                                      -- (terminated)
			reset_in14     => '0',                                      -- (terminated)
			reset_req_in14 => '0',                                      -- (terminated)
			reset_in15     => '0',                                      -- (terminated)
			reset_req_in15 => '0'                                       -- (terminated)
		);

	reset_bridge_0_out_reset_reset_ports_inv <= not reset_bridge_0_out_reset_reset;

end architecture rtl; -- of HPS_QSYS
