-- HPS_QSYS_altera_merlin_axi_slave_ni_altera_avalon_st_pipeline_stage_19128_mdgjkuq.vhd

-- Generated using ACDS version 25.3.1 100

library IEEE;
library altera_avalon_st_pipeline_stage_1930;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity HPS_QSYS_altera_merlin_axi_slave_ni_altera_avalon_st_pipeline_stage_19128_mdgjkuq is
	generic (
		SYMBOLS_PER_BEAT : integer := 1;
		BITS_PER_SYMBOL  : integer := 48;
		USE_PACKETS      : integer := 0;
		USE_EMPTY        : integer := 0;
		EMPTY_WIDTH      : integer := 0;
		CHANNEL_WIDTH    : integer := 0;
		PACKET_WIDTH     : integer := 0;
		ERROR_WIDTH      : integer := 0;
		PIPELINE_READY   : integer := 0;
		SYNC_RESET       : integer := 1
	);
	port (
		clk       : in  std_logic                     := '0';             --       cr0.clk,   Clock input
		reset     : in  std_logic                     := '0';             -- cr0_reset.reset, Reset input
		in_ready  : out std_logic;                                        --     sink0.ready, Ready port of Avalon Streaming Sink Interface; indicates when sink interface is ready to receive data
		in_valid  : in  std_logic                     := '0';             --          .valid, Valid data port of Avalon Streaming Sink Interface; high when input data is valid
		in_data   : in  std_logic_vector(47 downto 0) := (others => '0'); --          .data,  Input Data port of Avalon Streaming Sink Interface
		out_ready : in  std_logic                     := '0';             --   source0.ready, Ready port of Avalon Streaming Source Interface; indicates to source that data can be sent
		out_valid : out std_logic;                                        --          .valid, Valid data port of Avalon Streaming Source Interface; high when output data is valid
		out_data  : out std_logic_vector(47 downto 0)                     --          .data,  Output Data port of Avalon Streaming Source Interface
	);
end entity HPS_QSYS_altera_merlin_axi_slave_ni_altera_avalon_st_pipeline_stage_19128_mdgjkuq;

architecture rtl of HPS_QSYS_altera_merlin_axi_slave_ni_altera_avalon_st_pipeline_stage_19128_mdgjkuq is
	component HPS_QSYS_altera_avalon_st_pipeline_stage_1930_oiupeiq_cmp is
		generic (
			SYMBOLS_PER_BEAT : integer := 1;
			BITS_PER_SYMBOL  : integer := 8;
			USE_PACKETS      : integer := 0;
			USE_EMPTY        : integer := 0;
			EMPTY_WIDTH      : integer := 0;
			CHANNEL_WIDTH    : integer := 0;
			PACKET_WIDTH     : integer := 0;
			ERROR_WIDTH      : integer := 0;
			PIPELINE_READY   : integer := 1;
			SYNC_RESET       : integer := 0
		);
		port (
			clk               : in  std_logic                     := 'X';             -- clk
			reset             : in  std_logic                     := 'X';             -- reset
			in_ready          : out std_logic;                                        -- ready
			in_valid          : in  std_logic                     := 'X';             -- valid
			in_data           : in  std_logic_vector(47 downto 0) := (others => 'X'); -- data
			out_ready         : in  std_logic                     := 'X';             -- ready
			out_valid         : out std_logic;                                        -- valid
			out_data          : out std_logic_vector(47 downto 0);                    -- data
			in_startofpacket  : in  std_logic                     := 'X';             -- startofpacket
			in_endofpacket    : in  std_logic                     := 'X';             -- endofpacket
			out_startofpacket : out std_logic;                                        -- startofpacket
			out_endofpacket   : out std_logic;                                        -- endofpacket
			in_empty          : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- empty
			out_empty         : out std_logic_vector(0 downto 0);                     -- empty
			out_error         : out std_logic_vector(0 downto 0);                     -- error
			in_error          : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- error
			out_channel       : out std_logic_vector(0 downto 0);                     -- channel
			in_channel        : in  std_logic_vector(0 downto 0)  := (others => 'X')  -- channel
		);
	end component HPS_QSYS_altera_avalon_st_pipeline_stage_1930_oiupeiq_cmp;

	for my_altera_avalon_st_pipeline_stage_rd : HPS_QSYS_altera_avalon_st_pipeline_stage_1930_oiupeiq_cmp
		use entity altera_avalon_st_pipeline_stage_1930.HPS_QSYS_altera_avalon_st_pipeline_stage_1930_oiupeiq;
begin

	my_altera_avalon_st_pipeline_stage_rd : component HPS_QSYS_altera_avalon_st_pipeline_stage_1930_oiupeiq_cmp
		generic map (
			SYMBOLS_PER_BEAT => SYMBOLS_PER_BEAT,
			BITS_PER_SYMBOL  => BITS_PER_SYMBOL,
			USE_PACKETS      => USE_PACKETS,
			USE_EMPTY        => USE_EMPTY,
			EMPTY_WIDTH      => EMPTY_WIDTH,
			CHANNEL_WIDTH    => CHANNEL_WIDTH,
			PACKET_WIDTH     => PACKET_WIDTH,
			ERROR_WIDTH      => ERROR_WIDTH,
			PIPELINE_READY   => PIPELINE_READY,
			SYNC_RESET       => SYNC_RESET
		)
		port map (
			clk               => clk,       --       cr0.clk
			reset             => reset,     -- cr0_reset.reset
			in_ready          => in_ready,  --     sink0.ready
			in_valid          => in_valid,  --          .valid
			in_data           => in_data,   --          .data
			out_ready         => out_ready, --   source0.ready
			out_valid         => out_valid, --          .valid
			out_data          => out_data,  --          .data
			in_startofpacket  => '0',       -- (terminated)
			in_endofpacket    => '0',       -- (terminated)
			out_startofpacket => open,      -- (terminated)
			out_endofpacket   => open,      -- (terminated)
			in_empty          => "0",       -- (terminated)
			out_empty         => open,      -- (terminated)
			out_error         => open,      -- (terminated)
			in_error          => "0",       -- (terminated)
			out_channel       => open,      -- (terminated)
			in_channel        => "0"        -- (terminated)
		);

end architecture rtl; -- of HPS_QSYS_altera_merlin_axi_slave_ni_altera_avalon_st_pipeline_stage_19128_mdgjkuq
