// HPS_QSYS_intel_agilex_5_soc_0_intel_agilex_5_soc_1300_qrfuhsi.v

// This file was auto-generated from intel_soc_sundancemesa_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.3.1 100

`timescale 1 ps / 1 ps
module HPS_QSYS_intel_agilex_5_soc_0_intel_agilex_5_soc_1300_qrfuhsi (
		output wire         h2f_reset_reset,            //            h2f_reset.reset,   Active high reset from the HPS Reset Manager.
		input  wire         hps2fpga_axi_clock_clk,     //   hps2fpga_axi_clock.clk,     Clock from a single source in the FPGA.
		input  wire         hps2fpga_axi_reset_reset,   //   hps2fpga_axi_reset.reset,   Async reset to the Bridge logic. This signal is active-HIGH.
		output wire [3:0]   hps2fpga_awid,              //             hps2fpga.awid,    Identification tag for a write transaction.
		output wire [27:0]  hps2fpga_awaddr,            //                     .awaddr,  The address of the first transfer in a write transaction.
		output wire [7:0]   hps2fpga_awlen,             //                     .awlen,   The exact number of data transfers in a write transaction.
		output wire [2:0]   hps2fpga_awsize,            //                     .awsize,  The number of bytes in each data transfer in a write transaction.
		output wire [1:0]   hps2fpga_awburst,           //                     .awburst, Indicates how address changes between each transfer in a write transaction.
		output wire         hps2fpga_awlock,            //                     .awlock,  Provides information about the atomic characteristics of a write transaction.
		output wire [3:0]   hps2fpga_awcache,           //                     .awcache, Indicates how a write transaction is required to progress through a system.
		output wire [2:0]   hps2fpga_awprot,            //                     .awprot,  Protection attributes of a write transaction: privilege, security level, and access type.
		output wire         hps2fpga_awvalid,           //                     .awvalid, Indicates that the write address channel signals are valid.
		input  wire         hps2fpga_awready,           //                     .awready, Indicates that a transfer on the write address channel can be accepted.
		output wire [127:0] hps2fpga_wdata,             //                     .wdata,   Write data.
		output wire [15:0]  hps2fpga_wstrb,             //                     .wstrb,   Write strobes, indicate which byte lanes hold valid data.
		output wire         hps2fpga_wlast,             //                     .wlast,   User-defined extension for the write data channel.
		output wire         hps2fpga_wvalid,            //                     .wvalid,  Indicates that the write data channel signals are valid.
		input  wire         hps2fpga_wready,            //                     .wready,  Indicates that a transfer on the write data channel can be accepted.
		input  wire [3:0]   hps2fpga_bid,               //                     .bid,     Transaction identifier for the write response.
		input  wire [1:0]   hps2fpga_bresp,             //                     .bresp,   Write response, indicates the status of a write transaction.
		input  wire         hps2fpga_bvalid,            //                     .bvalid,  Indicates that the write response channel signals are valid.
		output wire         hps2fpga_bready,            //                     .bready,  Indicates that a transfer on the write response channel can be accepted.
		output wire [3:0]   hps2fpga_arid,              //                     .arid,    Transaction identifier for the read transaction.
		output wire [27:0]  hps2fpga_araddr,            //                     .araddr,  The address of the first transfer in a read transaction.
		output wire [7:0]   hps2fpga_arlen,             //                     .arlen,   The exact number of data transfers in a read transaction.
		output wire [2:0]   hps2fpga_arsize,            //                     .arsize,  The number of bytes in each data transfer in a read transaction.
		output wire [1:0]   hps2fpga_arburst,           //                     .arburst, Indicates how address changes between each transfer in a read transaction.
		output wire         hps2fpga_arlock,            //                     .arlock,  Provides information about the atomic characteristics of a read transaction.
		output wire [3:0]   hps2fpga_arcache,           //                     .arcache, Indicates how a read transaction is required to progress through a system.
		output wire [2:0]   hps2fpga_arprot,            //                     .arprot,  Protection attributes of a read transaction: privilege, security level, and access type.
		output wire         hps2fpga_arvalid,           //                     .arvalid, Indicates that the read address channel signals are valid.
		input  wire         hps2fpga_arready,           //                     .arready, Indicates that a transfer on the read address channel can be accepted.
		input  wire [3:0]   hps2fpga_rid,               //                     .rid,     Identification tag for read data and response.
		input  wire [127:0] hps2fpga_rdata,             //                     .rdata,   Read data.
		input  wire [1:0]   hps2fpga_rresp,             //                     .rresp,   Read response, indicates the status of a read transfer.
		input  wire         hps2fpga_rlast,             //                     .rlast,   Indicates whether this is the last data transfer in a read transaction.
		input  wire         hps2fpga_rvalid,            //                     .rvalid,  Indicates that the read data channel signals are valid.
		output wire         hps2fpga_rready,            //                     .rready,  Indicates that a transfer on the read data channel can be accepted.
		input  wire         lwhps2fpga_axi_clock_clk,   // lwhps2fpga_axi_clock.clk,     clock from a single source in the FPGA.
		input  wire         lwhps2fpga_axi_reset_reset, // lwhps2fpga_axi_reset.reset,   Async reset to the Bridge logic. This signal is active-HIGH.
		output wire [3:0]   lwhps2fpga_awid,            //           lwhps2fpga.awid,    Identification tag for a write transaction.
		output wire [23:0]  lwhps2fpga_awaddr,          //                     .awaddr,  The address of the first transfer in a write transaction.
		output wire [7:0]   lwhps2fpga_awlen,           //                     .awlen,   The exact number of data transfers in a write transaction.
		output wire [2:0]   lwhps2fpga_awsize,          //                     .awsize,  The number of bytes in each data transfer in a write transaction.
		output wire [1:0]   lwhps2fpga_awburst,         //                     .awburst, Indicates how address changes between each transfer in a write transaction.
		output wire         lwhps2fpga_awlock,          //                     .awlock,  Provides information about the atomic characteristics of a write transaction.
		output wire [3:0]   lwhps2fpga_awcache,         //                     .awcache, Indicates how a write transaction is required to progress through a system.
		output wire [2:0]   lwhps2fpga_awprot,          //                     .awprot,  Protection attributes of a write transaction: privilege, security level, and access type.
		output wire         lwhps2fpga_awvalid,         //                     .awvalid, Indicates that the write address channel signals are valid.
		input  wire         lwhps2fpga_awready,         //                     .awready, Indicates that a transfer on the write address channel can be accepted.
		output wire [31:0]  lwhps2fpga_wdata,           //                     .wdata,   Write data.
		output wire [3:0]   lwhps2fpga_wstrb,           //                     .wstrb,   Write strobes, indicate which byte lanes hold valid data.
		output wire         lwhps2fpga_wlast,           //                     .wlast,   User-defined extension for the write data channel.
		output wire         lwhps2fpga_wvalid,          //                     .wvalid,  Indicates that the write data channel signals are valid.
		input  wire         lwhps2fpga_wready,          //                     .wready,  Indicates that a transfer on the write data channel can be accepted.
		input  wire [3:0]   lwhps2fpga_bid,             //                     .bid,     Transaction identifier for the write response.
		input  wire [1:0]   lwhps2fpga_bresp,           //                     .bresp,   Write response, indicates the status of a write transaction.
		input  wire         lwhps2fpga_bvalid,          //                     .bvalid,  Indicates that the write response channel signals are valid.
		output wire         lwhps2fpga_bready,          //                     .bready,  Indicates that a transfer on the write response channel can be accepted.
		output wire [3:0]   lwhps2fpga_arid,            //                     .arid,    Transaction identifier for the read transaction.
		output wire [23:0]  lwhps2fpga_araddr,          //                     .araddr,  The address of the first transfer in a read transaction.
		output wire [7:0]   lwhps2fpga_arlen,           //                     .arlen,   The exact number of data transfers in a read transaction.
		output wire [2:0]   lwhps2fpga_arsize,          //                     .arsize,  The number of bytes in each data transfer in a read transaction.
		output wire [1:0]   lwhps2fpga_arburst,         //                     .arburst, Indicates how address changes between each transfer in a read transaction.
		output wire         lwhps2fpga_arlock,          //                     .arlock,  Provides information about the atomic characteristics of a read transaction.
		output wire [3:0]   lwhps2fpga_arcache,         //                     .arcache, Indicates how a read transaction is required to progress through a system.
		output wire [2:0]   lwhps2fpga_arprot,          //                     .arprot,  Protection attributes of a read transaction: privilege, security level, and access type.
		output wire         lwhps2fpga_arvalid,         //                     .arvalid, Indicates that the read address channel signals are valid.
		input  wire         lwhps2fpga_arready,         //                     .arready, Indicates that a transfer on the read address channel can be accepted.
		input  wire [3:0]   lwhps2fpga_rid,             //                     .rid,     Identification tag for read data and response.
		input  wire [31:0]  lwhps2fpga_rdata,           //                     .rdata,   Read data.
		input  wire [1:0]   lwhps2fpga_rresp,           //                     .rresp,   Read response, indicates the status of a read transfer.
		input  wire         lwhps2fpga_rlast,           //                     .rlast,   Indicates whether this is the last data transfer in a read transaction.
		input  wire         lwhps2fpga_rvalid,          //                     .rvalid,  Indicates that the read data channel signals are valid.
		output wire         lwhps2fpga_rready,          //                     .rready,  Indicates that a transfer on the read data channel can be accepted.
		inout  wire         hps_io_gpio41               //               hps_io.gpio41,  GPIO1 IO17
	);

	HPS_QSYS_intel_agilex_5_soc_0_intel_sundancemesa_hps_100_s3hty6a sm_hps (
		.h2f_reset          (h2f_reset_reset),            //  output,    width = 1,            h2f_reset.reset
		.hps2fpga_clk       (hps2fpga_axi_clock_clk),     //   input,    width = 1,   hps2fpga_axi_clock.clk
		.hps2fpga_rst       (hps2fpga_axi_reset_reset),   //   input,    width = 1,   hps2fpga_axi_reset.reset
		.hps2fpga_awid      (hps2fpga_awid),              //  output,    width = 4,             hps2fpga.awid
		.hps2fpga_awaddr    (hps2fpga_awaddr),            //  output,   width = 28,                     .awaddr
		.hps2fpga_awlen     (hps2fpga_awlen),             //  output,    width = 8,                     .awlen
		.hps2fpga_awsize    (hps2fpga_awsize),            //  output,    width = 3,                     .awsize
		.hps2fpga_awburst   (hps2fpga_awburst),           //  output,    width = 2,                     .awburst
		.hps2fpga_awlock    (hps2fpga_awlock),            //  output,    width = 1,                     .awlock
		.hps2fpga_awcache   (hps2fpga_awcache),           //  output,    width = 4,                     .awcache
		.hps2fpga_awprot    (hps2fpga_awprot),            //  output,    width = 3,                     .awprot
		.hps2fpga_awvalid   (hps2fpga_awvalid),           //  output,    width = 1,                     .awvalid
		.hps2fpga_awready   (hps2fpga_awready),           //   input,    width = 1,                     .awready
		.hps2fpga_wdata     (hps2fpga_wdata),             //  output,  width = 128,                     .wdata
		.hps2fpga_wstrb     (hps2fpga_wstrb),             //  output,   width = 16,                     .wstrb
		.hps2fpga_wlast     (hps2fpga_wlast),             //  output,    width = 1,                     .wlast
		.hps2fpga_wvalid    (hps2fpga_wvalid),            //  output,    width = 1,                     .wvalid
		.hps2fpga_wready    (hps2fpga_wready),            //   input,    width = 1,                     .wready
		.hps2fpga_bid       (hps2fpga_bid),               //   input,    width = 4,                     .bid
		.hps2fpga_bresp     (hps2fpga_bresp),             //   input,    width = 2,                     .bresp
		.hps2fpga_bvalid    (hps2fpga_bvalid),            //   input,    width = 1,                     .bvalid
		.hps2fpga_bready    (hps2fpga_bready),            //  output,    width = 1,                     .bready
		.hps2fpga_arid      (hps2fpga_arid),              //  output,    width = 4,                     .arid
		.hps2fpga_araddr    (hps2fpga_araddr),            //  output,   width = 28,                     .araddr
		.hps2fpga_arlen     (hps2fpga_arlen),             //  output,    width = 8,                     .arlen
		.hps2fpga_arsize    (hps2fpga_arsize),            //  output,    width = 3,                     .arsize
		.hps2fpga_arburst   (hps2fpga_arburst),           //  output,    width = 2,                     .arburst
		.hps2fpga_arlock    (hps2fpga_arlock),            //  output,    width = 1,                     .arlock
		.hps2fpga_arcache   (hps2fpga_arcache),           //  output,    width = 4,                     .arcache
		.hps2fpga_arprot    (hps2fpga_arprot),            //  output,    width = 3,                     .arprot
		.hps2fpga_arvalid   (hps2fpga_arvalid),           //  output,    width = 1,                     .arvalid
		.hps2fpga_arready   (hps2fpga_arready),           //   input,    width = 1,                     .arready
		.hps2fpga_rid       (hps2fpga_rid),               //   input,    width = 4,                     .rid
		.hps2fpga_rdata     (hps2fpga_rdata),             //   input,  width = 128,                     .rdata
		.hps2fpga_rresp     (hps2fpga_rresp),             //   input,    width = 2,                     .rresp
		.hps2fpga_rlast     (hps2fpga_rlast),             //   input,    width = 1,                     .rlast
		.hps2fpga_rvalid    (hps2fpga_rvalid),            //   input,    width = 1,                     .rvalid
		.hps2fpga_rready    (hps2fpga_rready),            //  output,    width = 1,                     .rready
		.lwhps2fpga_clk     (lwhps2fpga_axi_clock_clk),   //   input,    width = 1, lwhps2fpga_axi_clock.clk
		.lwhps2fpga_rst     (lwhps2fpga_axi_reset_reset), //   input,    width = 1, lwhps2fpga_axi_reset.reset
		.lwhps2fpga_awid    (lwhps2fpga_awid),            //  output,    width = 4,           lwhps2fpga.awid
		.lwhps2fpga_awaddr  (lwhps2fpga_awaddr),          //  output,   width = 24,                     .awaddr
		.lwhps2fpga_awlen   (lwhps2fpga_awlen),           //  output,    width = 8,                     .awlen
		.lwhps2fpga_awsize  (lwhps2fpga_awsize),          //  output,    width = 3,                     .awsize
		.lwhps2fpga_awburst (lwhps2fpga_awburst),         //  output,    width = 2,                     .awburst
		.lwhps2fpga_awlock  (lwhps2fpga_awlock),          //  output,    width = 1,                     .awlock
		.lwhps2fpga_awcache (lwhps2fpga_awcache),         //  output,    width = 4,                     .awcache
		.lwhps2fpga_awprot  (lwhps2fpga_awprot),          //  output,    width = 3,                     .awprot
		.lwhps2fpga_awvalid (lwhps2fpga_awvalid),         //  output,    width = 1,                     .awvalid
		.lwhps2fpga_awready (lwhps2fpga_awready),         //   input,    width = 1,                     .awready
		.lwhps2fpga_wdata   (lwhps2fpga_wdata),           //  output,   width = 32,                     .wdata
		.lwhps2fpga_wstrb   (lwhps2fpga_wstrb),           //  output,    width = 4,                     .wstrb
		.lwhps2fpga_wlast   (lwhps2fpga_wlast),           //  output,    width = 1,                     .wlast
		.lwhps2fpga_wvalid  (lwhps2fpga_wvalid),          //  output,    width = 1,                     .wvalid
		.lwhps2fpga_wready  (lwhps2fpga_wready),          //   input,    width = 1,                     .wready
		.lwhps2fpga_bid     (lwhps2fpga_bid),             //   input,    width = 4,                     .bid
		.lwhps2fpga_bresp   (lwhps2fpga_bresp),           //   input,    width = 2,                     .bresp
		.lwhps2fpga_bvalid  (lwhps2fpga_bvalid),          //   input,    width = 1,                     .bvalid
		.lwhps2fpga_bready  (lwhps2fpga_bready),          //  output,    width = 1,                     .bready
		.lwhps2fpga_arid    (lwhps2fpga_arid),            //  output,    width = 4,                     .arid
		.lwhps2fpga_araddr  (lwhps2fpga_araddr),          //  output,   width = 24,                     .araddr
		.lwhps2fpga_arlen   (lwhps2fpga_arlen),           //  output,    width = 8,                     .arlen
		.lwhps2fpga_arsize  (lwhps2fpga_arsize),          //  output,    width = 3,                     .arsize
		.lwhps2fpga_arburst (lwhps2fpga_arburst),         //  output,    width = 2,                     .arburst
		.lwhps2fpga_arlock  (lwhps2fpga_arlock),          //  output,    width = 1,                     .arlock
		.lwhps2fpga_arcache (lwhps2fpga_arcache),         //  output,    width = 4,                     .arcache
		.lwhps2fpga_arprot  (lwhps2fpga_arprot),          //  output,    width = 3,                     .arprot
		.lwhps2fpga_arvalid (lwhps2fpga_arvalid),         //  output,    width = 1,                     .arvalid
		.lwhps2fpga_arready (lwhps2fpga_arready),         //   input,    width = 1,                     .arready
		.lwhps2fpga_rid     (lwhps2fpga_rid),             //   input,    width = 4,                     .rid
		.lwhps2fpga_rdata   (lwhps2fpga_rdata),           //   input,   width = 32,                     .rdata
		.lwhps2fpga_rresp   (lwhps2fpga_rresp),           //   input,    width = 2,                     .rresp
		.lwhps2fpga_rlast   (lwhps2fpga_rlast),           //   input,    width = 1,                     .rlast
		.lwhps2fpga_rvalid  (lwhps2fpga_rvalid),          //   input,    width = 1,                     .rvalid
		.lwhps2fpga_rready  (lwhps2fpga_rready),          //  output,    width = 1,                     .rready
		.gpio41             (hps_io_gpio41)               //   inout,    width = 1,               hps_io.gpio41
	);

endmodule
