-- HPS_QSYS_reset_bridge_0.vhd

-- Generated using ACDS version 25.3.1 100

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity HPS_QSYS_reset_bridge_0 is
	port (
		clk         : in  std_logic := '0'; --       clk.clk,     Clock Input
		in_reset_n  : in  std_logic := '0'; --  in_reset.reset_n, Reset Input
		out_reset_n : out std_logic         -- out_reset.reset_n, Reset Output
	);
end entity HPS_QSYS_reset_bridge_0;

architecture rtl of HPS_QSYS_reset_bridge_0 is
begin

	out_reset_n <= in_reset_n;

end architecture rtl; -- of HPS_QSYS_reset_bridge_0
