// HPS_QSYS_altera_mm_interconnect_1920_474ciwq.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.3.1 100

`timescale 1 ps / 1 ps
module HPS_QSYS_altera_mm_interconnect_1920_474ciwq (
		input  wire [3:0]  intel_agilex_5_soc_0_lwhps2fpga_awid,                                             //                                            intel_agilex_5_soc_0_lwhps2fpga.awid
		input  wire [23:0] intel_agilex_5_soc_0_lwhps2fpga_awaddr,                                           //                                                                           .awaddr
		input  wire [7:0]  intel_agilex_5_soc_0_lwhps2fpga_awlen,                                            //                                                                           .awlen
		input  wire [2:0]  intel_agilex_5_soc_0_lwhps2fpga_awsize,                                           //                                                                           .awsize
		input  wire [1:0]  intel_agilex_5_soc_0_lwhps2fpga_awburst,                                          //                                                                           .awburst
		input  wire [0:0]  intel_agilex_5_soc_0_lwhps2fpga_awlock,                                           //                                                                           .awlock
		input  wire [3:0]  intel_agilex_5_soc_0_lwhps2fpga_awcache,                                          //                                                                           .awcache
		input  wire [2:0]  intel_agilex_5_soc_0_lwhps2fpga_awprot,                                           //                                                                           .awprot
		input  wire        intel_agilex_5_soc_0_lwhps2fpga_awvalid,                                          //                                                                           .awvalid
		output wire        intel_agilex_5_soc_0_lwhps2fpga_awready,                                          //                                                                           .awready
		input  wire [31:0] intel_agilex_5_soc_0_lwhps2fpga_wdata,                                            //                                                                           .wdata
		input  wire [3:0]  intel_agilex_5_soc_0_lwhps2fpga_wstrb,                                            //                                                                           .wstrb
		input  wire        intel_agilex_5_soc_0_lwhps2fpga_wlast,                                            //                                                                           .wlast
		input  wire        intel_agilex_5_soc_0_lwhps2fpga_wvalid,                                           //                                                                           .wvalid
		output wire        intel_agilex_5_soc_0_lwhps2fpga_wready,                                           //                                                                           .wready
		output wire [3:0]  intel_agilex_5_soc_0_lwhps2fpga_bid,                                              //                                                                           .bid
		output wire [1:0]  intel_agilex_5_soc_0_lwhps2fpga_bresp,                                            //                                                                           .bresp
		output wire        intel_agilex_5_soc_0_lwhps2fpga_bvalid,                                           //                                                                           .bvalid
		input  wire        intel_agilex_5_soc_0_lwhps2fpga_bready,                                           //                                                                           .bready
		input  wire [3:0]  intel_agilex_5_soc_0_lwhps2fpga_arid,                                             //                                                                           .arid
		input  wire [23:0] intel_agilex_5_soc_0_lwhps2fpga_araddr,                                           //                                                                           .araddr
		input  wire [7:0]  intel_agilex_5_soc_0_lwhps2fpga_arlen,                                            //                                                                           .arlen
		input  wire [2:0]  intel_agilex_5_soc_0_lwhps2fpga_arsize,                                           //                                                                           .arsize
		input  wire [1:0]  intel_agilex_5_soc_0_lwhps2fpga_arburst,                                          //                                                                           .arburst
		input  wire [0:0]  intel_agilex_5_soc_0_lwhps2fpga_arlock,                                           //                                                                           .arlock
		input  wire [3:0]  intel_agilex_5_soc_0_lwhps2fpga_arcache,                                          //                                                                           .arcache
		input  wire [2:0]  intel_agilex_5_soc_0_lwhps2fpga_arprot,                                           //                                                                           .arprot
		input  wire        intel_agilex_5_soc_0_lwhps2fpga_arvalid,                                          //                                                                           .arvalid
		output wire        intel_agilex_5_soc_0_lwhps2fpga_arready,                                          //                                                                           .arready
		output wire [3:0]  intel_agilex_5_soc_0_lwhps2fpga_rid,                                              //                                                                           .rid
		output wire [31:0] intel_agilex_5_soc_0_lwhps2fpga_rdata,                                            //                                                                           .rdata
		output wire [1:0]  intel_agilex_5_soc_0_lwhps2fpga_rresp,                                            //                                                                           .rresp
		output wire        intel_agilex_5_soc_0_lwhps2fpga_rlast,                                            //                                                                           .rlast
		output wire        intel_agilex_5_soc_0_lwhps2fpga_rvalid,                                           //                                                                           .rvalid
		input  wire        intel_agilex_5_soc_0_lwhps2fpga_rready,                                           //                                                                           .rready
		output wire [3:0]  intel_onchip_memory_0_axi_s1_awid,                                                //                                               intel_onchip_memory_0_axi_s1.awid
		output wire [11:0] intel_onchip_memory_0_axi_s1_awaddr,                                              //                                                                           .awaddr
		output wire [7:0]  intel_onchip_memory_0_axi_s1_awlen,                                               //                                                                           .awlen
		output wire [2:0]  intel_onchip_memory_0_axi_s1_awsize,                                              //                                                                           .awsize
		output wire [1:0]  intel_onchip_memory_0_axi_s1_awburst,                                             //                                                                           .awburst
		output wire        intel_onchip_memory_0_axi_s1_awvalid,                                             //                                                                           .awvalid
		input  wire        intel_onchip_memory_0_axi_s1_awready,                                             //                                                                           .awready
		output wire [31:0] intel_onchip_memory_0_axi_s1_wdata,                                               //                                                                           .wdata
		output wire [3:0]  intel_onchip_memory_0_axi_s1_wstrb,                                               //                                                                           .wstrb
		output wire        intel_onchip_memory_0_axi_s1_wlast,                                               //                                                                           .wlast
		output wire        intel_onchip_memory_0_axi_s1_wvalid,                                              //                                                                           .wvalid
		input  wire        intel_onchip_memory_0_axi_s1_wready,                                              //                                                                           .wready
		input  wire [3:0]  intel_onchip_memory_0_axi_s1_bid,                                                 //                                                                           .bid
		input  wire [1:0]  intel_onchip_memory_0_axi_s1_bresp,                                               //                                                                           .bresp
		input  wire        intel_onchip_memory_0_axi_s1_bvalid,                                              //                                                                           .bvalid
		output wire        intel_onchip_memory_0_axi_s1_bready,                                              //                                                                           .bready
		output wire [3:0]  intel_onchip_memory_0_axi_s1_arid,                                                //                                                                           .arid
		output wire [11:0] intel_onchip_memory_0_axi_s1_araddr,                                              //                                                                           .araddr
		output wire [7:0]  intel_onchip_memory_0_axi_s1_arlen,                                               //                                                                           .arlen
		output wire [2:0]  intel_onchip_memory_0_axi_s1_arsize,                                              //                                                                           .arsize
		output wire [1:0]  intel_onchip_memory_0_axi_s1_arburst,                                             //                                                                           .arburst
		output wire        intel_onchip_memory_0_axi_s1_arvalid,                                             //                                                                           .arvalid
		input  wire        intel_onchip_memory_0_axi_s1_arready,                                             //                                                                           .arready
		input  wire [3:0]  intel_onchip_memory_0_axi_s1_rid,                                                 //                                                                           .rid
		input  wire [31:0] intel_onchip_memory_0_axi_s1_rdata,                                               //                                                                           .rdata
		input  wire [1:0]  intel_onchip_memory_0_axi_s1_rresp,                                               //                                                                           .rresp
		input  wire        intel_onchip_memory_0_axi_s1_rlast,                                               //                                                                           .rlast
		input  wire        intel_onchip_memory_0_axi_s1_rvalid,                                              //                                                                           .rvalid
		output wire        intel_onchip_memory_0_axi_s1_rready,                                              //                                                                           .rready
		input  wire        intel_agilex_5_soc_0_lwhps2fpga_translator_clk_reset_reset_bridge_in_reset_reset, // intel_agilex_5_soc_0_lwhps2fpga_translator_clk_reset_reset_bridge_in_reset.reset,  Reset Input
		input  wire        intel_onchip_memory_0_axi_s1_translator_clk_reset_reset_bridge_in_reset_reset,    //    intel_onchip_memory_0_axi_s1_translator_clk_reset_reset_bridge_in_reset.reset,  Reset Input
		input  wire        iopll_0_outclk0_clk                                                               //                                                            iopll_0_outclk0.clk,    Clock Input
	);

	wire   [0:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_ruser;    // intel_onchip_memory_0_axi_s1_translator:s0_ruser -> intel_agilex_5_soc_0_lwhps2fpga_translator:m0_ruser
	wire   [0:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_wuser;    // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_wuser -> intel_onchip_memory_0_axi_s1_translator:s0_wuser
	wire   [1:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awburst;  // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_awburst -> intel_onchip_memory_0_axi_s1_translator:s0_awburst
	wire   [3:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arregion; // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_arregion -> intel_onchip_memory_0_axi_s1_translator:s0_arregion
	wire   [0:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awuser;   // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_awuser -> intel_onchip_memory_0_axi_s1_translator:s0_awuser
	wire   [7:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arlen;    // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_arlen -> intel_onchip_memory_0_axi_s1_translator:s0_arlen
	wire   [3:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arqos;    // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_arqos -> intel_onchip_memory_0_axi_s1_translator:s0_arqos
	wire   [3:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_wstrb;    // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_wstrb -> intel_onchip_memory_0_axi_s1_translator:s0_wstrb
	wire         intel_agilex_5_soc_0_lwhps2fpga_translator_m0_wready;   // intel_onchip_memory_0_axi_s1_translator:s0_wready -> intel_agilex_5_soc_0_lwhps2fpga_translator:m0_wready
	wire   [3:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_rid;      // intel_onchip_memory_0_axi_s1_translator:s0_rid -> intel_agilex_5_soc_0_lwhps2fpga_translator:m0_rid
	wire         intel_agilex_5_soc_0_lwhps2fpga_translator_m0_rready;   // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_rready -> intel_onchip_memory_0_axi_s1_translator:s0_rready
	wire   [7:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awlen;    // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_awlen -> intel_onchip_memory_0_axi_s1_translator:s0_awlen
	wire   [3:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awqos;    // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_awqos -> intel_onchip_memory_0_axi_s1_translator:s0_awqos
	wire   [3:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arcache;  // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_arcache -> intel_onchip_memory_0_axi_s1_translator:s0_arcache
	wire         intel_agilex_5_soc_0_lwhps2fpga_translator_m0_wvalid;   // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_wvalid -> intel_onchip_memory_0_axi_s1_translator:s0_wvalid
	wire  [23:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_araddr;   // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_araddr -> intel_onchip_memory_0_axi_s1_translator:s0_araddr
	wire   [2:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arprot;   // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_arprot -> intel_onchip_memory_0_axi_s1_translator:s0_arprot
	wire   [2:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awprot;   // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_awprot -> intel_onchip_memory_0_axi_s1_translator:s0_awprot
	wire  [31:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_wdata;    // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_wdata -> intel_onchip_memory_0_axi_s1_translator:s0_wdata
	wire         intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arvalid;  // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_arvalid -> intel_onchip_memory_0_axi_s1_translator:s0_arvalid
	wire   [3:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awcache;  // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_awcache -> intel_onchip_memory_0_axi_s1_translator:s0_awcache
	wire   [3:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arid;     // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_arid -> intel_onchip_memory_0_axi_s1_translator:s0_arid
	wire   [0:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arlock;   // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_arlock -> intel_onchip_memory_0_axi_s1_translator:s0_arlock
	wire   [0:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awlock;   // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_awlock -> intel_onchip_memory_0_axi_s1_translator:s0_awlock
	wire  [23:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awaddr;   // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_awaddr -> intel_onchip_memory_0_axi_s1_translator:s0_awaddr
	wire   [1:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_bresp;    // intel_onchip_memory_0_axi_s1_translator:s0_bresp -> intel_agilex_5_soc_0_lwhps2fpga_translator:m0_bresp
	wire         intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arready;  // intel_onchip_memory_0_axi_s1_translator:s0_arready -> intel_agilex_5_soc_0_lwhps2fpga_translator:m0_arready
	wire  [31:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_rdata;    // intel_onchip_memory_0_axi_s1_translator:s0_rdata -> intel_agilex_5_soc_0_lwhps2fpga_translator:m0_rdata
	wire         intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awready;  // intel_onchip_memory_0_axi_s1_translator:s0_awready -> intel_agilex_5_soc_0_lwhps2fpga_translator:m0_awready
	wire   [1:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arburst;  // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_arburst -> intel_onchip_memory_0_axi_s1_translator:s0_arburst
	wire   [2:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arsize;   // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_arsize -> intel_onchip_memory_0_axi_s1_translator:s0_arsize
	wire         intel_agilex_5_soc_0_lwhps2fpga_translator_m0_bready;   // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_bready -> intel_onchip_memory_0_axi_s1_translator:s0_bready
	wire         intel_agilex_5_soc_0_lwhps2fpga_translator_m0_rlast;    // intel_onchip_memory_0_axi_s1_translator:s0_rlast -> intel_agilex_5_soc_0_lwhps2fpga_translator:m0_rlast
	wire         intel_agilex_5_soc_0_lwhps2fpga_translator_m0_wlast;    // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_wlast -> intel_onchip_memory_0_axi_s1_translator:s0_wlast
	wire   [3:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awregion; // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_awregion -> intel_onchip_memory_0_axi_s1_translator:s0_awregion
	wire   [0:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_buser;    // intel_onchip_memory_0_axi_s1_translator:s0_buser -> intel_agilex_5_soc_0_lwhps2fpga_translator:m0_buser
	wire   [1:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_rresp;    // intel_onchip_memory_0_axi_s1_translator:s0_rresp -> intel_agilex_5_soc_0_lwhps2fpga_translator:m0_rresp
	wire   [3:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awid;     // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_awid -> intel_onchip_memory_0_axi_s1_translator:s0_awid
	wire   [3:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_bid;      // intel_onchip_memory_0_axi_s1_translator:s0_bid -> intel_agilex_5_soc_0_lwhps2fpga_translator:m0_bid
	wire         intel_agilex_5_soc_0_lwhps2fpga_translator_m0_bvalid;   // intel_onchip_memory_0_axi_s1_translator:s0_bvalid -> intel_agilex_5_soc_0_lwhps2fpga_translator:m0_bvalid
	wire   [2:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awsize;   // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_awsize -> intel_onchip_memory_0_axi_s1_translator:s0_awsize
	wire         intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awvalid;  // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_awvalid -> intel_onchip_memory_0_axi_s1_translator:s0_awvalid
	wire   [0:0] intel_agilex_5_soc_0_lwhps2fpga_translator_m0_aruser;   // intel_agilex_5_soc_0_lwhps2fpga_translator:m0_aruser -> intel_onchip_memory_0_axi_s1_translator:s0_aruser
	wire         intel_agilex_5_soc_0_lwhps2fpga_translator_m0_rvalid;   // intel_onchip_memory_0_axi_s1_translator:s0_rvalid -> intel_agilex_5_soc_0_lwhps2fpga_translator:m0_rvalid

	HPS_QSYS_altera_merlin_axi_translator_1986_4khp5ei #(
		.USE_S0_AWID                       (1),
		.USE_S0_AWREGION                   (0),
		.USE_M0_AWREGION                   (1),
		.USE_S0_AWLEN                      (1),
		.USE_S0_AWSIZE                     (1),
		.USE_S0_AWBURST                    (1),
		.USE_S0_AWLOCK                     (1),
		.USE_M0_AWLOCK                     (1),
		.USE_S0_AWCACHE                    (1),
		.USE_M0_AWCACHE                    (1),
		.USE_M0_AWPROT                     (1),
		.USE_S0_AWPROT                     (1),
		.USE_S0_AWQOS                      (0),
		.USE_M0_AWQOS                      (1),
		.USE_S0_WSTRB                      (1),
		.USE_M0_WLAST                      (1),
		.USE_S0_WLAST                      (1),
		.USE_S0_BID                        (1),
		.USE_S0_BRESP                      (1),
		.USE_M0_BRESP                      (1),
		.USE_S0_ARID                       (1),
		.USE_S0_ARREGION                   (0),
		.USE_M0_ARREGION                   (1),
		.USE_S0_ARLEN                      (1),
		.USE_S0_ARSIZE                     (1),
		.USE_S0_ARBURST                    (1),
		.USE_S0_ARLOCK                     (1),
		.USE_M0_ARLOCK                     (1),
		.USE_M0_ARCACHE                    (1),
		.USE_M0_ARQOS                      (1),
		.USE_M0_ARPROT                     (1),
		.USE_S0_ARPROT                     (1),
		.USE_S0_ARCACHE                    (1),
		.USE_S0_ARQOS                      (0),
		.USE_S0_RID                        (1),
		.USE_S0_RRESP                      (1),
		.USE_M0_RRESP                      (1),
		.USE_S0_RLAST                      (1),
		.USE_S0_AWUSER                     (0),
		.USE_S0_ARUSER                     (0),
		.USE_S0_WUSER                      (0),
		.USE_S0_RUSER                      (0),
		.USE_S0_BUSER                      (0),
		.USE_M0_AWUSER                     (1),
		.USE_M0_ARUSER                     (1),
		.USE_M0_WUSER                      (1),
		.USE_M0_RUSER                      (1),
		.USE_M0_BUSER                      (1),
		.USE_M0_AWUSER_ADDRCHK             (1),
		.USE_M0_AWUSER_SAI                 (1),
		.USE_M0_ARUSER_ADDRCHK             (1),
		.USE_M0_ARUSER_SAI                 (1),
		.USE_M0_WUSER_DATACHK              (1),
		.USE_M0_WUSER_POISON               (1),
		.USE_M0_RUSER_DATACHK              (1),
		.USE_M0_RUSER_POISON               (1),
		.USE_M0_WUSER_DATA                 (1),
		.USE_M0_RUSER_DATA                 (1),
		.USE_M0_AWAKEUP                    (0),
		.USE_M0_WPOISON                    (0),
		.USE_M0_RPOISON                    (0),
		.USE_M0_AWTRACE                    (0),
		.USE_M0_ARTRACE                    (0),
		.USE_M0_WTRACE                     (0),
		.USE_M0_BTRACE                     (0),
		.USE_M0_RTRACE                     (0),
		.USE_M0_WDATACHK                   (0),
		.USE_M0_RDATACHK                   (0),
		.USE_M0_AWUNIQUE                   (1),
		.USE_S0_AWAKEUP                    (0),
		.USE_S0_WPOISON                    (0),
		.USE_S0_RPOISON                    (0),
		.USE_S0_AWTRACE                    (0),
		.USE_S0_ARTRACE                    (0),
		.USE_S0_WTRACE                     (0),
		.USE_S0_BTRACE                     (0),
		.USE_S0_RTRACE                     (0),
		.USE_S0_WDATACHK                   (0),
		.USE_S0_RDATACHK                   (0),
		.USE_S0_AWUSER_ADDRCHK             (0),
		.USE_S0_AWUSER_SAI                 (0),
		.USE_S0_ARUSER_ADDRCHK             (0),
		.USE_S0_ARUSER_SAI                 (0),
		.USE_S0_WUSER_DATACHK              (0),
		.USE_S0_WUSER_POISON               (0),
		.USE_S0_RUSER_DATACHK              (0),
		.USE_S0_WUSER_DATA                 (0),
		.USE_S0_RUSER_DATA                 (0),
		.USE_S0_RUSER_POISON               (0),
		.USE_S0_AWUNIQUE                   (0),
		.USE_S0_AWATOP                     (0),
		.USE_S0_AWSTASHNID                 (0),
		.USE_S0_AWSTASHNIDEN               (0),
		.USE_S0_AWSTASHLPID                (0),
		.USE_S0_AWSTASHLPIDEN              (0),
		.USE_S0_AWMMUSECSID                (0),
		.USE_S0_AWMMUSID                   (0),
		.USE_S0_ARMMUSECSID                (0),
		.USE_S0_ARMMUSID                   (0),
		.USE_M0_AWATOP                     (0),
		.USE_M0_AWSTASHNID                 (0),
		.USE_M0_AWSTASHNIDEN               (0),
		.USE_M0_AWSTASHLPID                (0),
		.USE_M0_AWSTASHLPIDEN              (0),
		.USE_M0_AWMMUSECSID                (0),
		.USE_M0_AWMMUSID                   (0),
		.USE_M0_ARMMUSECSID                (0),
		.USE_M0_ARMMUSID                   (0),
		.USE_S0_AWSNOOP                    (1),
		.USE_S0_ARSNOOP                    (1),
		.USE_S0_AWADDRCHK                  (0),
		.USE_S0_ARADDRCHK                  (0),
		.USE_M0_AWADDRCHK                  (0),
		.USE_M0_ARADDRCHK                  (0),
		.M0_ID_WIDTH                       (4),
		.DATA_WIDTH                        (32),
		.M0_SAI_WIDTH                      (1),
		.S0_SAI_WIDTH                      (1),
		.USER_DATA_WIDTH                   (1),
		.M0_USER_ADDRCHK_WIDTH             (1),
		.S0_USER_ADDRCHK_WIDTH             (1),
		.S0_ID_WIDTH                       (4),
		.M0_ADDR_WIDTH                     (24),
		.S0_WRITE_ADDR_USER_WIDTH          (1),
		.S0_READ_ADDR_USER_WIDTH           (1),
		.M0_WRITE_ADDR_USER_WIDTH          (1),
		.M0_READ_ADDR_USER_WIDTH           (1),
		.S0_WRITE_DATA_USER_WIDTH          (1),
		.S0_WRITE_RESPONSE_DATA_USER_WIDTH (1),
		.S0_READ_DATA_USER_WIDTH           (1),
		.M0_WRITE_DATA_USER_WIDTH          (1),
		.M0_WRITE_RESPONSE_DATA_USER_WIDTH (1),
		.M0_READ_DATA_USER_WIDTH           (1),
		.S0_ADDR_WIDTH                     (24),
		.M0_SID_WIDTH                      (16),
		.S0_SID_WIDTH                      (16),
		.M0_AXI_VERSION                    ("AXI4"),
		.M0_BURST_LENGTH_WIDTH             (8),
		.S0_BURST_LENGTH_WIDTH             (8),
		.M0_LOCK_WIDTH                     (1),
		.S0_LOCK_WIDTH                     (1),
		.M0_AWSNOOP_WIDTH                  (3),
		.S0_AWSNOOP_WIDTH                  (3),
		.S0_AXI_VERSION                    ("AXI4"),
		.ACE_LITE_SUPPORT                  (0),
		.ACE5_LITE_SUPPORT                 (0),
		.REGENERATE_ADDRCHK                (0),
		.ROLE_BASED_USER                   (0)
	) intel_agilex_5_soc_0_lwhps2fpga_translator (
		.aclk              (iopll_0_outclk0_clk),                                                               //   input,   width = 1,       clk.clk
		.aresetn           (~intel_agilex_5_soc_0_lwhps2fpga_translator_clk_reset_reset_bridge_in_reset_reset), //   input,   width = 1, clk_reset.reset_n
		.m0_awid           (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awid),                                //  output,   width = 4,        m0.awid
		.m0_awaddr         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awaddr),                              //  output,  width = 24,          .awaddr
		.m0_awlen          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awlen),                               //  output,   width = 8,          .awlen
		.m0_awsize         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awsize),                              //  output,   width = 3,          .awsize
		.m0_awburst        (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awburst),                             //  output,   width = 2,          .awburst
		.m0_awlock         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awlock),                              //  output,   width = 1,          .awlock
		.m0_awcache        (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awcache),                             //  output,   width = 4,          .awcache
		.m0_awprot         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awprot),                              //  output,   width = 3,          .awprot
		.m0_awuser         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awuser),                              //  output,   width = 1,          .awuser
		.m0_awqos          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awqos),                               //  output,   width = 4,          .awqos
		.m0_awregion       (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awregion),                            //  output,   width = 4,          .awregion
		.m0_awvalid        (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awvalid),                             //  output,   width = 1,          .awvalid
		.m0_awready        (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awready),                             //   input,   width = 1,          .awready
		.m0_wdata          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_wdata),                               //  output,  width = 32,          .wdata
		.m0_wstrb          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_wstrb),                               //  output,   width = 4,          .wstrb
		.m0_wlast          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_wlast),                               //  output,   width = 1,          .wlast
		.m0_wvalid         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_wvalid),                              //  output,   width = 1,          .wvalid
		.m0_wuser          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_wuser),                               //  output,   width = 1,          .wuser
		.m0_wready         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_wready),                              //   input,   width = 1,          .wready
		.m0_bid            (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_bid),                                 //   input,   width = 4,          .bid
		.m0_bresp          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_bresp),                               //   input,   width = 2,          .bresp
		.m0_buser          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_buser),                               //   input,   width = 1,          .buser
		.m0_bvalid         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_bvalid),                              //   input,   width = 1,          .bvalid
		.m0_bready         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_bready),                              //  output,   width = 1,          .bready
		.m0_arid           (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arid),                                //  output,   width = 4,          .arid
		.m0_araddr         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_araddr),                              //  output,  width = 24,          .araddr
		.m0_arlen          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arlen),                               //  output,   width = 8,          .arlen
		.m0_arsize         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arsize),                              //  output,   width = 3,          .arsize
		.m0_arburst        (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arburst),                             //  output,   width = 2,          .arburst
		.m0_arlock         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arlock),                              //  output,   width = 1,          .arlock
		.m0_arcache        (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arcache),                             //  output,   width = 4,          .arcache
		.m0_arprot         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arprot),                              //  output,   width = 3,          .arprot
		.m0_aruser         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_aruser),                              //  output,   width = 1,          .aruser
		.m0_arqos          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arqos),                               //  output,   width = 4,          .arqos
		.m0_arregion       (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arregion),                            //  output,   width = 4,          .arregion
		.m0_arvalid        (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arvalid),                             //  output,   width = 1,          .arvalid
		.m0_arready        (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arready),                             //   input,   width = 1,          .arready
		.m0_rid            (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_rid),                                 //   input,   width = 4,          .rid
		.m0_rdata          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_rdata),                               //   input,  width = 32,          .rdata
		.m0_rresp          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_rresp),                               //   input,   width = 2,          .rresp
		.m0_rlast          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_rlast),                               //   input,   width = 1,          .rlast
		.m0_rvalid         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_rvalid),                              //   input,   width = 1,          .rvalid
		.m0_rready         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_rready),                              //  output,   width = 1,          .rready
		.m0_ruser          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_ruser),                               //   input,   width = 1,          .ruser
		.s0_awid           (intel_agilex_5_soc_0_lwhps2fpga_awid),                                              //   input,   width = 4,        s0.awid
		.s0_awaddr         (intel_agilex_5_soc_0_lwhps2fpga_awaddr),                                            //   input,  width = 24,          .awaddr
		.s0_awlen          (intel_agilex_5_soc_0_lwhps2fpga_awlen),                                             //   input,   width = 8,          .awlen
		.s0_awsize         (intel_agilex_5_soc_0_lwhps2fpga_awsize),                                            //   input,   width = 3,          .awsize
		.s0_awburst        (intel_agilex_5_soc_0_lwhps2fpga_awburst),                                           //   input,   width = 2,          .awburst
		.s0_awlock         (intel_agilex_5_soc_0_lwhps2fpga_awlock),                                            //   input,   width = 1,          .awlock
		.s0_awcache        (intel_agilex_5_soc_0_lwhps2fpga_awcache),                                           //   input,   width = 4,          .awcache
		.s0_awprot         (intel_agilex_5_soc_0_lwhps2fpga_awprot),                                            //   input,   width = 3,          .awprot
		.s0_awvalid        (intel_agilex_5_soc_0_lwhps2fpga_awvalid),                                           //   input,   width = 1,          .awvalid
		.s0_awready        (intel_agilex_5_soc_0_lwhps2fpga_awready),                                           //  output,   width = 1,          .awready
		.s0_wdata          (intel_agilex_5_soc_0_lwhps2fpga_wdata),                                             //   input,  width = 32,          .wdata
		.s0_wstrb          (intel_agilex_5_soc_0_lwhps2fpga_wstrb),                                             //   input,   width = 4,          .wstrb
		.s0_wlast          (intel_agilex_5_soc_0_lwhps2fpga_wlast),                                             //   input,   width = 1,          .wlast
		.s0_wvalid         (intel_agilex_5_soc_0_lwhps2fpga_wvalid),                                            //   input,   width = 1,          .wvalid
		.s0_wready         (intel_agilex_5_soc_0_lwhps2fpga_wready),                                            //  output,   width = 1,          .wready
		.s0_bid            (intel_agilex_5_soc_0_lwhps2fpga_bid),                                               //  output,   width = 4,          .bid
		.s0_bresp          (intel_agilex_5_soc_0_lwhps2fpga_bresp),                                             //  output,   width = 2,          .bresp
		.s0_bvalid         (intel_agilex_5_soc_0_lwhps2fpga_bvalid),                                            //  output,   width = 1,          .bvalid
		.s0_bready         (intel_agilex_5_soc_0_lwhps2fpga_bready),                                            //   input,   width = 1,          .bready
		.s0_arid           (intel_agilex_5_soc_0_lwhps2fpga_arid),                                              //   input,   width = 4,          .arid
		.s0_araddr         (intel_agilex_5_soc_0_lwhps2fpga_araddr),                                            //   input,  width = 24,          .araddr
		.s0_arlen          (intel_agilex_5_soc_0_lwhps2fpga_arlen),                                             //   input,   width = 8,          .arlen
		.s0_arsize         (intel_agilex_5_soc_0_lwhps2fpga_arsize),                                            //   input,   width = 3,          .arsize
		.s0_arburst        (intel_agilex_5_soc_0_lwhps2fpga_arburst),                                           //   input,   width = 2,          .arburst
		.s0_arlock         (intel_agilex_5_soc_0_lwhps2fpga_arlock),                                            //   input,   width = 1,          .arlock
		.s0_arcache        (intel_agilex_5_soc_0_lwhps2fpga_arcache),                                           //   input,   width = 4,          .arcache
		.s0_arprot         (intel_agilex_5_soc_0_lwhps2fpga_arprot),                                            //   input,   width = 3,          .arprot
		.s0_arvalid        (intel_agilex_5_soc_0_lwhps2fpga_arvalid),                                           //   input,   width = 1,          .arvalid
		.s0_arready        (intel_agilex_5_soc_0_lwhps2fpga_arready),                                           //  output,   width = 1,          .arready
		.s0_rid            (intel_agilex_5_soc_0_lwhps2fpga_rid),                                               //  output,   width = 4,          .rid
		.s0_rdata          (intel_agilex_5_soc_0_lwhps2fpga_rdata),                                             //  output,  width = 32,          .rdata
		.s0_rresp          (intel_agilex_5_soc_0_lwhps2fpga_rresp),                                             //  output,   width = 2,          .rresp
		.s0_rlast          (intel_agilex_5_soc_0_lwhps2fpga_rlast),                                             //  output,   width = 1,          .rlast
		.s0_rvalid         (intel_agilex_5_soc_0_lwhps2fpga_rvalid),                                            //  output,   width = 1,          .rvalid
		.s0_rready         (intel_agilex_5_soc_0_lwhps2fpga_rready),                                            //   input,   width = 1,          .rready
		.m0_awuser_addrchk (),                                                                                  // (terminated),                        
		.m0_awuser_sai     (),                                                                                  // (terminated),                        
		.m0_wuser_datachk  (),                                                                                  // (terminated),                        
		.m0_wuser_data     (),                                                                                  // (terminated),                        
		.m0_wuser_poison   (),                                                                                  // (terminated),                        
		.m0_aruser_addrchk (),                                                                                  // (terminated),                        
		.m0_aruser_sai     (),                                                                                  // (terminated),                        
		.m0_ruser_datachk  (4'b0000),                                                                           // (terminated),                        
		.m0_ruser_data     (1'b0),                                                                              // (terminated),                        
		.m0_ruser_poison   (1'b0),                                                                              // (terminated),                        
		.s0_awuser         (1'b0),                                                                              // (terminated),                        
		.s0_awuser_addrchk (1'b0),                                                                              // (terminated),                        
		.s0_awuser_sai     (1'b0),                                                                              // (terminated),                        
		.s0_awqos          (4'b0000),                                                                           // (terminated),                        
		.s0_awregion       (4'b0000),                                                                           // (terminated),                        
		.s0_wuser          (1'b0),                                                                              // (terminated),                        
		.s0_wuser_datachk  (4'b0000),                                                                           // (terminated),                        
		.s0_wuser_data     (1'b0),                                                                              // (terminated),                        
		.s0_wuser_poison   (1'b0),                                                                              // (terminated),                        
		.s0_buser          (),                                                                                  // (terminated),                        
		.s0_aruser         (1'b0),                                                                              // (terminated),                        
		.s0_aruser_addrchk (1'b0),                                                                              // (terminated),                        
		.s0_aruser_sai     (1'b0),                                                                              // (terminated),                        
		.s0_arqos          (4'b0000),                                                                           // (terminated),                        
		.s0_arregion       (4'b0000),                                                                           // (terminated),                        
		.s0_ruser          (),                                                                                  // (terminated),                        
		.s0_ruser_datachk  (),                                                                                  // (terminated),                        
		.s0_ruser_data     (),                                                                                  // (terminated),                        
		.s0_ruser_poison   (),                                                                                  // (terminated),                        
		.m0_wid            (),                                                                                  // (terminated),                        
		.m0_arbar          (),                                                                                  // (terminated),                        
		.m0_awbar          (),                                                                                  // (terminated),                        
		.m0_awunique       (),                                                                                  // (terminated),                        
		.m0_ardomain       (),                                                                                  // (terminated),                        
		.m0_awdomain       (),                                                                                  // (terminated),                        
		.m0_arsnoop        (),                                                                                  // (terminated),                        
		.m0_awsnoop        (),                                                                                  // (terminated),                        
		.s0_awakeup        (1'b0),                                                                              // (terminated),                        
		.s0_awtrace        (1'b0),                                                                              // (terminated),                        
		.s0_artrace        (1'b0),                                                                              // (terminated),                        
		.s0_wpoison        (1'b0),                                                                              // (terminated),                        
		.s0_wdatachk       (4'b0000),                                                                           // (terminated),                        
		.s0_wtrace         (1'b0),                                                                              // (terminated),                        
		.s0_btrace         (),                                                                                  // (terminated),                        
		.s0_rpoison        (),                                                                                  // (terminated),                        
		.s0_rdatachk       (),                                                                                  // (terminated),                        
		.s0_rtrace         (),                                                                                  // (terminated),                        
		.s0_awatop         (6'b000000),                                                                         // (terminated),                        
		.s0_awstashnid     (11'b00000000000),                                                                   // (terminated),                        
		.s0_awstashniden   (1'b0),                                                                              // (terminated),                        
		.s0_awstashlpid    (5'b00000),                                                                          // (terminated),                        
		.s0_awstashlpiden  (1'b0),                                                                              // (terminated),                        
		.s0_awmmusecsid    (1'b0),                                                                              // (terminated),                        
		.s0_awmmusid       (16'b0000000000000000),                                                              // (terminated),                        
		.s0_armmusecsid    (1'b0),                                                                              // (terminated),                        
		.s0_armmusid       (16'b0000000000000000),                                                              // (terminated),                        
		.s0_awaddrchk      (1'b0),                                                                              // (terminated),                        
		.s0_araddrchk      (1'b0),                                                                              // (terminated),                        
		.m0_awakeup        (),                                                                                  // (terminated),                        
		.m0_awtrace        (),                                                                                  // (terminated),                        
		.m0_artrace        (),                                                                                  // (terminated),                        
		.m0_wpoison        (),                                                                                  // (terminated),                        
		.m0_wdatachk       (),                                                                                  // (terminated),                        
		.m0_wtrace         (),                                                                                  // (terminated),                        
		.m0_btrace         (1'b0),                                                                              // (terminated),                        
		.m0_rpoison        (1'b0),                                                                              // (terminated),                        
		.m0_rdatachk       (4'b0000),                                                                           // (terminated),                        
		.m0_rtrace         (1'b0),                                                                              // (terminated),                        
		.m0_awatop         (),                                                                                  // (terminated),                        
		.m0_awstashnid     (),                                                                                  // (terminated),                        
		.m0_awstashniden   (),                                                                                  // (terminated),                        
		.m0_awstashlpid    (),                                                                                  // (terminated),                        
		.m0_awstashlpiden  (),                                                                                  // (terminated),                        
		.m0_awmmusecsid    (),                                                                                  // (terminated),                        
		.m0_awmmusid       (),                                                                                  // (terminated),                        
		.m0_armmusecsid    (),                                                                                  // (terminated),                        
		.m0_armmusid       (),                                                                                  // (terminated),                        
		.m0_awaddrchk      (),                                                                                  // (terminated),                        
		.m0_araddrchk      (),                                                                                  // (terminated),                        
		.s0_wid            (4'b0000),                                                                           // (terminated),                        
		.s0_arbar          (2'b00),                                                                             // (terminated),                        
		.s0_awbar          (2'b00),                                                                             // (terminated),                        
		.s0_awunique       (1'b0),                                                                              // (terminated),                        
		.s0_ardomain       (2'b00),                                                                             // (terminated),                        
		.s0_awdomain       (2'b00),                                                                             // (terminated),                        
		.s0_arsnoop        (4'b0000),                                                                           // (terminated),                        
		.s0_awsnoop        (3'b000)                                                                             // (terminated),                        
	);

	HPS_QSYS_altera_merlin_axi_translator_1986_4khp5ei #(
		.USE_S0_AWID                       (1),
		.USE_S0_AWREGION                   (1),
		.USE_M0_AWREGION                   (0),
		.USE_S0_AWLEN                      (1),
		.USE_S0_AWSIZE                     (1),
		.USE_S0_AWBURST                    (1),
		.USE_S0_AWLOCK                     (1),
		.USE_M0_AWLOCK                     (0),
		.USE_S0_AWCACHE                    (1),
		.USE_M0_AWCACHE                    (0),
		.USE_M0_AWPROT                     (0),
		.USE_S0_AWPROT                     (1),
		.USE_S0_AWQOS                      (1),
		.USE_M0_AWQOS                      (0),
		.USE_S0_WSTRB                      (1),
		.USE_M0_WLAST                      (1),
		.USE_S0_WLAST                      (1),
		.USE_S0_BID                        (1),
		.USE_S0_BRESP                      (1),
		.USE_M0_BRESP                      (1),
		.USE_S0_ARID                       (1),
		.USE_S0_ARREGION                   (1),
		.USE_M0_ARREGION                   (0),
		.USE_S0_ARLEN                      (1),
		.USE_S0_ARSIZE                     (1),
		.USE_S0_ARBURST                    (1),
		.USE_S0_ARLOCK                     (1),
		.USE_M0_ARLOCK                     (0),
		.USE_M0_ARCACHE                    (0),
		.USE_M0_ARQOS                      (0),
		.USE_M0_ARPROT                     (0),
		.USE_S0_ARPROT                     (1),
		.USE_S0_ARCACHE                    (1),
		.USE_S0_ARQOS                      (1),
		.USE_S0_RID                        (1),
		.USE_S0_RRESP                      (1),
		.USE_M0_RRESP                      (1),
		.USE_S0_RLAST                      (1),
		.USE_S0_AWUSER                     (1),
		.USE_S0_ARUSER                     (1),
		.USE_S0_WUSER                      (1),
		.USE_S0_RUSER                      (1),
		.USE_S0_BUSER                      (1),
		.USE_M0_AWUSER                     (0),
		.USE_M0_ARUSER                     (0),
		.USE_M0_WUSER                      (0),
		.USE_M0_RUSER                      (0),
		.USE_M0_BUSER                      (0),
		.USE_M0_AWUSER_ADDRCHK             (0),
		.USE_M0_AWUSER_SAI                 (0),
		.USE_M0_ARUSER_ADDRCHK             (0),
		.USE_M0_ARUSER_SAI                 (0),
		.USE_M0_WUSER_DATACHK              (0),
		.USE_M0_WUSER_POISON               (0),
		.USE_M0_RUSER_DATACHK              (0),
		.USE_M0_RUSER_POISON               (0),
		.USE_M0_WUSER_DATA                 (0),
		.USE_M0_RUSER_DATA                 (0),
		.USE_M0_AWAKEUP                    (0),
		.USE_M0_WPOISON                    (0),
		.USE_M0_RPOISON                    (0),
		.USE_M0_AWTRACE                    (0),
		.USE_M0_ARTRACE                    (0),
		.USE_M0_WTRACE                     (0),
		.USE_M0_BTRACE                     (0),
		.USE_M0_RTRACE                     (0),
		.USE_M0_WDATACHK                   (0),
		.USE_M0_RDATACHK                   (0),
		.USE_M0_AWUNIQUE                   (0),
		.USE_S0_AWAKEUP                    (0),
		.USE_S0_WPOISON                    (0),
		.USE_S0_RPOISON                    (0),
		.USE_S0_AWTRACE                    (0),
		.USE_S0_ARTRACE                    (0),
		.USE_S0_WTRACE                     (0),
		.USE_S0_BTRACE                     (0),
		.USE_S0_RTRACE                     (0),
		.USE_S0_WDATACHK                   (0),
		.USE_S0_RDATACHK                   (0),
		.USE_S0_AWUSER_ADDRCHK             (1),
		.USE_S0_AWUSER_SAI                 (1),
		.USE_S0_ARUSER_ADDRCHK             (1),
		.USE_S0_ARUSER_SAI                 (1),
		.USE_S0_WUSER_DATACHK              (1),
		.USE_S0_WUSER_POISON               (1),
		.USE_S0_RUSER_DATACHK              (1),
		.USE_S0_WUSER_DATA                 (1),
		.USE_S0_RUSER_DATA                 (1),
		.USE_S0_RUSER_POISON               (1),
		.USE_S0_AWUNIQUE                   (1),
		.USE_S0_AWATOP                     (0),
		.USE_S0_AWSTASHNID                 (0),
		.USE_S0_AWSTASHNIDEN               (0),
		.USE_S0_AWSTASHLPID                (0),
		.USE_S0_AWSTASHLPIDEN              (0),
		.USE_S0_AWMMUSECSID                (0),
		.USE_S0_AWMMUSID                   (0),
		.USE_S0_ARMMUSECSID                (0),
		.USE_S0_ARMMUSID                   (0),
		.USE_M0_AWATOP                     (0),
		.USE_M0_AWSTASHNID                 (0),
		.USE_M0_AWSTASHNIDEN               (0),
		.USE_M0_AWSTASHLPID                (0),
		.USE_M0_AWSTASHLPIDEN              (0),
		.USE_M0_AWMMUSECSID                (0),
		.USE_M0_AWMMUSID                   (0),
		.USE_M0_ARMMUSECSID                (0),
		.USE_M0_ARMMUSID                   (0),
		.USE_S0_AWSNOOP                    (1),
		.USE_S0_ARSNOOP                    (1),
		.USE_S0_AWADDRCHK                  (0),
		.USE_S0_ARADDRCHK                  (0),
		.USE_M0_AWADDRCHK                  (0),
		.USE_M0_ARADDRCHK                  (0),
		.M0_ID_WIDTH                       (4),
		.DATA_WIDTH                        (32),
		.M0_SAI_WIDTH                      (1),
		.S0_SAI_WIDTH                      (1),
		.USER_DATA_WIDTH                   (1),
		.M0_USER_ADDRCHK_WIDTH             (1),
		.S0_USER_ADDRCHK_WIDTH             (1),
		.S0_ID_WIDTH                       (4),
		.M0_ADDR_WIDTH                     (12),
		.S0_WRITE_ADDR_USER_WIDTH          (1),
		.S0_READ_ADDR_USER_WIDTH           (1),
		.M0_WRITE_ADDR_USER_WIDTH          (1),
		.M0_READ_ADDR_USER_WIDTH           (1),
		.S0_WRITE_DATA_USER_WIDTH          (1),
		.S0_WRITE_RESPONSE_DATA_USER_WIDTH (1),
		.S0_READ_DATA_USER_WIDTH           (1),
		.M0_WRITE_DATA_USER_WIDTH          (1),
		.M0_WRITE_RESPONSE_DATA_USER_WIDTH (1),
		.M0_READ_DATA_USER_WIDTH           (1),
		.S0_ADDR_WIDTH                     (24),
		.M0_SID_WIDTH                      (16),
		.S0_SID_WIDTH                      (16),
		.M0_AXI_VERSION                    ("AXI4"),
		.M0_BURST_LENGTH_WIDTH             (8),
		.S0_BURST_LENGTH_WIDTH             (8),
		.M0_LOCK_WIDTH                     (1),
		.S0_LOCK_WIDTH                     (1),
		.M0_AWSNOOP_WIDTH                  (3),
		.S0_AWSNOOP_WIDTH                  (3),
		.S0_AXI_VERSION                    ("AXI4"),
		.ACE_LITE_SUPPORT                  (0),
		.ACE5_LITE_SUPPORT                 (0),
		.REGENERATE_ADDRCHK                (0),
		.ROLE_BASED_USER                   (0)
	) intel_onchip_memory_0_axi_s1_translator (
		.aclk              (iopll_0_outclk0_clk),                                                            //   input,   width = 1,       clk.clk
		.aresetn           (~intel_onchip_memory_0_axi_s1_translator_clk_reset_reset_bridge_in_reset_reset), //   input,   width = 1, clk_reset.reset_n
		.m0_awid           (intel_onchip_memory_0_axi_s1_awid),                                              //  output,   width = 4,        m0.awid
		.m0_awaddr         (intel_onchip_memory_0_axi_s1_awaddr),                                            //  output,  width = 12,          .awaddr
		.m0_awlen          (intel_onchip_memory_0_axi_s1_awlen),                                             //  output,   width = 8,          .awlen
		.m0_awsize         (intel_onchip_memory_0_axi_s1_awsize),                                            //  output,   width = 3,          .awsize
		.m0_awburst        (intel_onchip_memory_0_axi_s1_awburst),                                           //  output,   width = 2,          .awburst
		.m0_awvalid        (intel_onchip_memory_0_axi_s1_awvalid),                                           //  output,   width = 1,          .awvalid
		.m0_awready        (intel_onchip_memory_0_axi_s1_awready),                                           //   input,   width = 1,          .awready
		.m0_wdata          (intel_onchip_memory_0_axi_s1_wdata),                                             //  output,  width = 32,          .wdata
		.m0_wstrb          (intel_onchip_memory_0_axi_s1_wstrb),                                             //  output,   width = 4,          .wstrb
		.m0_wlast          (intel_onchip_memory_0_axi_s1_wlast),                                             //  output,   width = 1,          .wlast
		.m0_wvalid         (intel_onchip_memory_0_axi_s1_wvalid),                                            //  output,   width = 1,          .wvalid
		.m0_wready         (intel_onchip_memory_0_axi_s1_wready),                                            //   input,   width = 1,          .wready
		.m0_bid            (intel_onchip_memory_0_axi_s1_bid),                                               //   input,   width = 4,          .bid
		.m0_bresp          (intel_onchip_memory_0_axi_s1_bresp),                                             //   input,   width = 2,          .bresp
		.m0_bvalid         (intel_onchip_memory_0_axi_s1_bvalid),                                            //   input,   width = 1,          .bvalid
		.m0_bready         (intel_onchip_memory_0_axi_s1_bready),                                            //  output,   width = 1,          .bready
		.m0_arid           (intel_onchip_memory_0_axi_s1_arid),                                              //  output,   width = 4,          .arid
		.m0_araddr         (intel_onchip_memory_0_axi_s1_araddr),                                            //  output,  width = 12,          .araddr
		.m0_arlen          (intel_onchip_memory_0_axi_s1_arlen),                                             //  output,   width = 8,          .arlen
		.m0_arsize         (intel_onchip_memory_0_axi_s1_arsize),                                            //  output,   width = 3,          .arsize
		.m0_arburst        (intel_onchip_memory_0_axi_s1_arburst),                                           //  output,   width = 2,          .arburst
		.m0_arvalid        (intel_onchip_memory_0_axi_s1_arvalid),                                           //  output,   width = 1,          .arvalid
		.m0_arready        (intel_onchip_memory_0_axi_s1_arready),                                           //   input,   width = 1,          .arready
		.m0_rid            (intel_onchip_memory_0_axi_s1_rid),                                               //   input,   width = 4,          .rid
		.m0_rdata          (intel_onchip_memory_0_axi_s1_rdata),                                             //   input,  width = 32,          .rdata
		.m0_rresp          (intel_onchip_memory_0_axi_s1_rresp),                                             //   input,   width = 2,          .rresp
		.m0_rlast          (intel_onchip_memory_0_axi_s1_rlast),                                             //   input,   width = 1,          .rlast
		.m0_rvalid         (intel_onchip_memory_0_axi_s1_rvalid),                                            //   input,   width = 1,          .rvalid
		.m0_rready         (intel_onchip_memory_0_axi_s1_rready),                                            //  output,   width = 1,          .rready
		.s0_awid           (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awid),                             //   input,   width = 4,        s0.awid
		.s0_awaddr         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awaddr),                           //   input,  width = 24,          .awaddr
		.s0_awlen          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awlen),                            //   input,   width = 8,          .awlen
		.s0_awsize         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awsize),                           //   input,   width = 3,          .awsize
		.s0_awburst        (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awburst),                          //   input,   width = 2,          .awburst
		.s0_awlock         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awlock),                           //   input,   width = 1,          .awlock
		.s0_awcache        (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awcache),                          //   input,   width = 4,          .awcache
		.s0_awprot         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awprot),                           //   input,   width = 3,          .awprot
		.s0_awuser         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awuser),                           //   input,   width = 1,          .awuser
		.s0_awqos          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awqos),                            //   input,   width = 4,          .awqos
		.s0_awregion       (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awregion),                         //   input,   width = 4,          .awregion
		.s0_awvalid        (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awvalid),                          //   input,   width = 1,          .awvalid
		.s0_awready        (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_awready),                          //  output,   width = 1,          .awready
		.s0_wdata          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_wdata),                            //   input,  width = 32,          .wdata
		.s0_wstrb          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_wstrb),                            //   input,   width = 4,          .wstrb
		.s0_wlast          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_wlast),                            //   input,   width = 1,          .wlast
		.s0_wvalid         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_wvalid),                           //   input,   width = 1,          .wvalid
		.s0_wuser          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_wuser),                            //   input,   width = 1,          .wuser
		.s0_wready         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_wready),                           //  output,   width = 1,          .wready
		.s0_bid            (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_bid),                              //  output,   width = 4,          .bid
		.s0_bresp          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_bresp),                            //  output,   width = 2,          .bresp
		.s0_buser          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_buser),                            //  output,   width = 1,          .buser
		.s0_bvalid         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_bvalid),                           //  output,   width = 1,          .bvalid
		.s0_bready         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_bready),                           //   input,   width = 1,          .bready
		.s0_arid           (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arid),                             //   input,   width = 4,          .arid
		.s0_araddr         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_araddr),                           //   input,  width = 24,          .araddr
		.s0_arlen          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arlen),                            //   input,   width = 8,          .arlen
		.s0_arsize         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arsize),                           //   input,   width = 3,          .arsize
		.s0_arburst        (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arburst),                          //   input,   width = 2,          .arburst
		.s0_arlock         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arlock),                           //   input,   width = 1,          .arlock
		.s0_arcache        (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arcache),                          //   input,   width = 4,          .arcache
		.s0_arprot         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arprot),                           //   input,   width = 3,          .arprot
		.s0_aruser         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_aruser),                           //   input,   width = 1,          .aruser
		.s0_arqos          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arqos),                            //   input,   width = 4,          .arqos
		.s0_arregion       (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arregion),                         //   input,   width = 4,          .arregion
		.s0_arvalid        (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arvalid),                          //   input,   width = 1,          .arvalid
		.s0_arready        (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_arready),                          //  output,   width = 1,          .arready
		.s0_rid            (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_rid),                              //  output,   width = 4,          .rid
		.s0_rdata          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_rdata),                            //  output,  width = 32,          .rdata
		.s0_rresp          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_rresp),                            //  output,   width = 2,          .rresp
		.s0_rlast          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_rlast),                            //  output,   width = 1,          .rlast
		.s0_rvalid         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_rvalid),                           //  output,   width = 1,          .rvalid
		.s0_rready         (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_rready),                           //   input,   width = 1,          .rready
		.s0_ruser          (intel_agilex_5_soc_0_lwhps2fpga_translator_m0_ruser),                            //  output,   width = 1,          .ruser
		.m0_awlock         (),                                                                               // (terminated),                        
		.m0_awcache        (),                                                                               // (terminated),                        
		.m0_awprot         (),                                                                               // (terminated),                        
		.m0_awuser         (),                                                                               // (terminated),                        
		.m0_awuser_addrchk (),                                                                               // (terminated),                        
		.m0_awuser_sai     (),                                                                               // (terminated),                        
		.m0_awqos          (),                                                                               // (terminated),                        
		.m0_awregion       (),                                                                               // (terminated),                        
		.m0_wuser          (),                                                                               // (terminated),                        
		.m0_wuser_datachk  (),                                                                               // (terminated),                        
		.m0_wuser_data     (),                                                                               // (terminated),                        
		.m0_wuser_poison   (),                                                                               // (terminated),                        
		.m0_buser          (1'b0),                                                                           // (terminated),                        
		.m0_arlock         (),                                                                               // (terminated),                        
		.m0_arcache        (),                                                                               // (terminated),                        
		.m0_arprot         (),                                                                               // (terminated),                        
		.m0_aruser         (),                                                                               // (terminated),                        
		.m0_aruser_addrchk (),                                                                               // (terminated),                        
		.m0_aruser_sai     (),                                                                               // (terminated),                        
		.m0_arqos          (),                                                                               // (terminated),                        
		.m0_arregion       (),                                                                               // (terminated),                        
		.m0_ruser          (1'b0),                                                                           // (terminated),                        
		.m0_ruser_datachk  (4'b0000),                                                                        // (terminated),                        
		.m0_ruser_data     (1'b0),                                                                           // (terminated),                        
		.m0_ruser_poison   (1'b0),                                                                           // (terminated),                        
		.s0_awuser_addrchk (1'b0),                                                                           // (terminated),                        
		.s0_awuser_sai     (1'b0),                                                                           // (terminated),                        
		.s0_wuser_datachk  (4'b0000),                                                                        // (terminated),                        
		.s0_wuser_data     (1'b0),                                                                           // (terminated),                        
		.s0_wuser_poison   (1'b0),                                                                           // (terminated),                        
		.s0_aruser_addrchk (1'b0),                                                                           // (terminated),                        
		.s0_aruser_sai     (1'b0),                                                                           // (terminated),                        
		.s0_ruser_datachk  (),                                                                               // (terminated),                        
		.s0_ruser_data     (),                                                                               // (terminated),                        
		.s0_ruser_poison   (),                                                                               // (terminated),                        
		.m0_wid            (),                                                                               // (terminated),                        
		.m0_arbar          (),                                                                               // (terminated),                        
		.m0_awbar          (),                                                                               // (terminated),                        
		.m0_awunique       (),                                                                               // (terminated),                        
		.m0_ardomain       (),                                                                               // (terminated),                        
		.m0_awdomain       (),                                                                               // (terminated),                        
		.m0_arsnoop        (),                                                                               // (terminated),                        
		.m0_awsnoop        (),                                                                               // (terminated),                        
		.s0_awakeup        (1'b0),                                                                           // (terminated),                        
		.s0_awtrace        (1'b0),                                                                           // (terminated),                        
		.s0_artrace        (1'b0),                                                                           // (terminated),                        
		.s0_wpoison        (1'b0),                                                                           // (terminated),                        
		.s0_wdatachk       (4'b0000),                                                                        // (terminated),                        
		.s0_wtrace         (1'b0),                                                                           // (terminated),                        
		.s0_btrace         (),                                                                               // (terminated),                        
		.s0_rpoison        (),                                                                               // (terminated),                        
		.s0_rdatachk       (),                                                                               // (terminated),                        
		.s0_rtrace         (),                                                                               // (terminated),                        
		.s0_awatop         (6'b000000),                                                                      // (terminated),                        
		.s0_awstashnid     (11'b00000000000),                                                                // (terminated),                        
		.s0_awstashniden   (1'b0),                                                                           // (terminated),                        
		.s0_awstashlpid    (5'b00000),                                                                       // (terminated),                        
		.s0_awstashlpiden  (1'b0),                                                                           // (terminated),                        
		.s0_awmmusecsid    (1'b0),                                                                           // (terminated),                        
		.s0_awmmusid       (16'b0000000000000000),                                                           // (terminated),                        
		.s0_armmusecsid    (1'b0),                                                                           // (terminated),                        
		.s0_armmusid       (16'b0000000000000000),                                                           // (terminated),                        
		.s0_awaddrchk      (1'b0),                                                                           // (terminated),                        
		.s0_araddrchk      (1'b0),                                                                           // (terminated),                        
		.m0_awakeup        (),                                                                               // (terminated),                        
		.m0_awtrace        (),                                                                               // (terminated),                        
		.m0_artrace        (),                                                                               // (terminated),                        
		.m0_wpoison        (),                                                                               // (terminated),                        
		.m0_wdatachk       (),                                                                               // (terminated),                        
		.m0_wtrace         (),                                                                               // (terminated),                        
		.m0_btrace         (1'b0),                                                                           // (terminated),                        
		.m0_rpoison        (1'b0),                                                                           // (terminated),                        
		.m0_rdatachk       (4'b0000),                                                                        // (terminated),                        
		.m0_rtrace         (1'b0),                                                                           // (terminated),                        
		.m0_awatop         (),                                                                               // (terminated),                        
		.m0_awstashnid     (),                                                                               // (terminated),                        
		.m0_awstashniden   (),                                                                               // (terminated),                        
		.m0_awstashlpid    (),                                                                               // (terminated),                        
		.m0_awstashlpiden  (),                                                                               // (terminated),                        
		.m0_awmmusecsid    (),                                                                               // (terminated),                        
		.m0_awmmusid       (),                                                                               // (terminated),                        
		.m0_armmusecsid    (),                                                                               // (terminated),                        
		.m0_armmusid       (),                                                                               // (terminated),                        
		.m0_awaddrchk      (),                                                                               // (terminated),                        
		.m0_araddrchk      (),                                                                               // (terminated),                        
		.s0_wid            (4'b0000),                                                                        // (terminated),                        
		.s0_arbar          (2'b00),                                                                          // (terminated),                        
		.s0_awbar          (2'b00),                                                                          // (terminated),                        
		.s0_awunique       (1'b0),                                                                           // (terminated),                        
		.s0_ardomain       (2'b00),                                                                          // (terminated),                        
		.s0_awdomain       (2'b00),                                                                          // (terminated),                        
		.s0_arsnoop        (4'b0000),                                                                        // (terminated),                        
		.s0_awsnoop        (3'b000)                                                                          // (terminated),                        
	);

endmodule
