// altera_ace5lite_cache_coherency_translator_0.v

// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module altera_ace5lite_cache_coherency_translator_0 #(
		parameter WSTRB_WIDTH = 16,
		parameter USER_WIDTH  = 8
	) (
		input  wire         clk,                      //        clk.clk
		input  wire         reset,                    //      reset.reset
		output wire [3:0]   m_ace5lite_awid,          // m_ace5lite.awid
		output wire [31:0]  m_ace5lite_awaddr,        //           .awaddr
		output wire [1:0]   m_ace5lite_awdomain,      //           .awdomain
		output wire [3:0]   m_ace5lite_awsnoop,       //           .awsnoop
		output wire [7:0]   m_ace5lite_awlen,         //           .awlen
		output wire [2:0]   m_ace5lite_awsize,        //           .awsize
		output wire [2:0]   m_ace5lite_arsize,        //           .arsize
		output wire [1:0]   m_ace5lite_awburst,       //           .awburst
		output wire         m_ace5lite_awlock,        //           .awlock
		output wire [3:0]   m_ace5lite_awcache,       //           .awcache
		output wire [2:0]   m_ace5lite_awprot,        //           .awprot
		output wire [3:0]   m_ace5lite_awqos,         //           .awqos
		output wire [10:0]  m_ace5lite_awstashnid,    //           .awstashnid
		output wire         m_ace5lite_awstashniden,  //           .awstashniden
		output wire [4:0]   m_ace5lite_awstashlpid,   //           .awstashlpid
		output wire         m_ace5lite_awstashlpiden, //           .awstashlpiden
		output wire [5:0]   m_ace5lite_awatop,        //           .awatop
		output wire         m_ace5lite_awvalid,       //           .awvalid
		input  wire         m_ace5lite_awready,       //           .awready
		output wire [127:0] m_ace5lite_wdata,         //           .wdata
		output wire [15:0]  m_ace5lite_wstrb,         //           .wstrb
		output wire         m_ace5lite_wlast,         //           .wlast
		output wire         m_ace5lite_wvalid,        //           .wvalid
		input  wire         m_ace5lite_wready,        //           .wready
		input  wire [3:0]   m_ace5lite_bid,           //           .bid
		input  wire [1:0]   m_ace5lite_bresp,         //           .bresp
		input  wire         m_ace5lite_bvalid,        //           .bvalid
		output wire         m_ace5lite_bready,        //           .bready
		output wire [3:0]   m_ace5lite_arid,          //           .arid
		output wire [31:0]  m_ace5lite_araddr,        //           .araddr
		output wire [1:0]   m_ace5lite_ardomain,      //           .ardomain
		output wire [3:0]   m_ace5lite_arsnoop,       //           .arsnoop
		output wire [7:0]   m_ace5lite_arlen,         //           .arlen
		output wire [1:0]   m_ace5lite_arburst,       //           .arburst
		output wire         m_ace5lite_arlock,        //           .arlock
		output wire [3:0]   m_ace5lite_arcache,       //           .arcache
		output wire [2:0]   m_ace5lite_arprot,        //           .arprot
		output wire [3:0]   m_ace5lite_arqos,         //           .arqos
		output wire         m_ace5lite_arvalid,       //           .arvalid
		input  wire         m_ace5lite_arready,       //           .arready
		input  wire [3:0]   m_ace5lite_rid,           //           .rid
		input  wire [127:0] m_ace5lite_rdata,         //           .rdata
		input  wire [1:0]   m_ace5lite_rresp,         //           .rresp
		input  wire         m_ace5lite_rlast,         //           .rlast
		input  wire         m_ace5lite_rvalid,        //           .rvalid
		output wire         m_ace5lite_rready,        //           .rready
		output wire [7:0]   m_ace5lite_aruser,        //           .aruser
		output wire [7:0]   m_ace5lite_awuser,        //           .awuser
		output wire [3:0]   m_ace5lite_arregion,      //           .arregion
		output wire [3:0]   m_ace5lite_awregion,      //           .awregion
		output wire [7:0]   m_ace5lite_wuser,         //           .wuser
		input  wire [7:0]   m_ace5lite_buser,         //           .buser
		input  wire [7:0]   m_ace5lite_ruser,         //           .ruser
		input  wire [3:0]   s_axi_awid,               //      s_axi.awid
		input  wire [31:0]  s_axi_awaddr,             //           .awaddr
		input  wire [7:0]   s_axi_awlen,              //           .awlen
		input  wire [2:0]   s_axi_awsize,             //           .awsize
		input  wire [1:0]   s_axi_awburst,            //           .awburst
		input  wire         s_axi_awlock,             //           .awlock
		input  wire [3:0]   s_axi_awcache,            //           .awcache
		input  wire [2:0]   s_axi_awprot,             //           .awprot
		input  wire [3:0]   s_axi_awqos,              //           .awqos
		input  wire         s_axi_awvalid,            //           .awvalid
		output wire         s_axi_awready,            //           .awready
		input  wire [3:0]   s_axi_awregion,           //           .awregion
		input  wire [127:0] s_axi_wdata,              //           .wdata
		input  wire [15:0]  s_axi_wstrb,              //           .wstrb
		input  wire         s_axi_wlast,              //           .wlast
		input  wire         s_axi_wvalid,             //           .wvalid
		output wire         s_axi_wready,             //           .wready
		input  wire [7:0]   s_axi_wuser,              //           .wuser
		output wire [3:0]   s_axi_bid,                //           .bid
		output wire [1:0]   s_axi_bresp,              //           .bresp
		output wire         s_axi_bvalid,             //           .bvalid
		input  wire         s_axi_bready,             //           .bready
		output wire [7:0]   s_axi_buser,              //           .buser
		input  wire [3:0]   s_axi_arid,               //           .arid
		input  wire [31:0]  s_axi_araddr,             //           .araddr
		input  wire [7:0]   s_axi_arlen,              //           .arlen
		input  wire [2:0]   s_axi_arsize,             //           .arsize
		input  wire [1:0]   s_axi_arburst,            //           .arburst
		input  wire         s_axi_arlock,             //           .arlock
		input  wire [3:0]   s_axi_arcache,            //           .arcache
		input  wire [2:0]   s_axi_arprot,             //           .arprot
		input  wire [3:0]   s_axi_arqos,              //           .arqos
		input  wire         s_axi_arvalid,            //           .arvalid
		output wire         s_axi_arready,            //           .arready
		input  wire [3:0]   s_axi_arregion,           //           .arregion
		output wire [3:0]   s_axi_rid,                //           .rid
		output wire [127:0] s_axi_rdata,              //           .rdata
		output wire [1:0]   s_axi_rresp,              //           .rresp
		output wire         s_axi_rlast,              //           .rlast
		output wire         s_axi_rvalid,             //           .rvalid
		input  wire         s_axi_rready,             //           .rready
		output wire [7:0]   s_axi_ruser               //           .ruser
	);

	altera_ace5lite_cache_coherency_translator #(
		.CONTROL_INTERFACE_EN   (0),
		.AXI_INTERFACE_TYPE     (0),
		.ARDOMAIN_OVERRIDE      (2'b10),
		.ARSNOOP_OVERRIDE       (4'b0000),
		.ARCACHE_OVERRIDE_EN    (0),
		.ARCACHE_OVERRIDE       (4'b1111),
		.AWDOMAIN_OVERRIDE      (2'b00),
		.AWSNOOP_OVERRIDE       (3'b000),
		.AWCACHE_OVERRIDE_EN    (0),
		.AWCACHE_OVERRIDE       (4'b1111),
		.AxPROT_OVERRIDE_EN     (0),
		.AxPROT_OVERRIDE        (3'b011),
		.AWSTASHNIDEN_OVERRIDE  (1'b0),
		.AWSTASHNID_OVERRIDE    (11'b00000000000),
		.AWSTASHLPIDEN_OVERRIDE (1'b0),
		.AWSTASHLPID_OVERRIDE   (5'b00000),
		.AWATOP_OVERRIDE        (6'b000000),
		.ENABLE_MMU             (0),
		.AWMMUSECSID_OVERRIDE   (0),
		.AWMMUSID_OVERRIDE      (16'b0000000000000000),
		.ARMMUSECSID_OVERRIDE   (0),
		.ARMMUSID_OVERRIDE      (16'b0000000000000000),
		.SID_WIDTH              (16'b0000000000010000),
		.ADDR_WIDTH             (32),
		.AXM_ID_WIDTH           (4),
		.AXS_ID_WIDTH           (4),
		.DATA_WIDTH             (128),
		.ARUSER_OVERRIDE        (8'b00001100),
		.AWUSER_OVERRIDE        (8'b00001100),
		.WSTRB_WIDTH            (WSTRB_WIDTH),
		.USER_WIDTH             (USER_WIDTH)
	) altera_ace5lite_cache_coherency_translator_inst (
		.clk                      (clk),                                  //   input,    width = 1,        clk.clk
		.reset                    (reset),                                //   input,    width = 1,      reset.reset
		.m_ace5lite_awid          (m_ace5lite_awid),                      //  output,    width = 4, m_ace5lite.awid
		.m_ace5lite_awaddr        (m_ace5lite_awaddr),                    //  output,   width = 32,           .awaddr
		.m_ace5lite_awdomain      (m_ace5lite_awdomain),                  //  output,    width = 2,           .awdomain
		.m_ace5lite_awsnoop       (m_ace5lite_awsnoop),                   //  output,    width = 4,           .awsnoop
		.m_ace5lite_awlen         (m_ace5lite_awlen),                     //  output,    width = 8,           .awlen
		.m_ace5lite_awsize        (m_ace5lite_awsize),                    //  output,    width = 3,           .awsize
		.m_ace5lite_arsize        (m_ace5lite_arsize),                    //  output,    width = 3,           .arsize
		.m_ace5lite_awburst       (m_ace5lite_awburst),                   //  output,    width = 2,           .awburst
		.m_ace5lite_awlock        (m_ace5lite_awlock),                    //  output,    width = 1,           .awlock
		.m_ace5lite_awcache       (m_ace5lite_awcache),                   //  output,    width = 4,           .awcache
		.m_ace5lite_awprot        (m_ace5lite_awprot),                    //  output,    width = 3,           .awprot
		.m_ace5lite_awqos         (m_ace5lite_awqos),                     //  output,    width = 4,           .awqos
		.m_ace5lite_awstashnid    (m_ace5lite_awstashnid),                //  output,   width = 11,           .awstashnid
		.m_ace5lite_awstashniden  (m_ace5lite_awstashniden),              //  output,    width = 1,           .awstashniden
		.m_ace5lite_awstashlpid   (m_ace5lite_awstashlpid),               //  output,    width = 5,           .awstashlpid
		.m_ace5lite_awstashlpiden (m_ace5lite_awstashlpiden),             //  output,    width = 1,           .awstashlpiden
		.m_ace5lite_awatop        (m_ace5lite_awatop),                    //  output,    width = 6,           .awatop
		.m_ace5lite_awvalid       (m_ace5lite_awvalid),                   //  output,    width = 1,           .awvalid
		.m_ace5lite_awready       (m_ace5lite_awready),                   //   input,    width = 1,           .awready
		.m_ace5lite_wdata         (m_ace5lite_wdata),                     //  output,  width = 128,           .wdata
		.m_ace5lite_wstrb         (m_ace5lite_wstrb),                     //  output,   width = 16,           .wstrb
		.m_ace5lite_wlast         (m_ace5lite_wlast),                     //  output,    width = 1,           .wlast
		.m_ace5lite_wvalid        (m_ace5lite_wvalid),                    //  output,    width = 1,           .wvalid
		.m_ace5lite_wready        (m_ace5lite_wready),                    //   input,    width = 1,           .wready
		.m_ace5lite_bid           (m_ace5lite_bid),                       //   input,    width = 4,           .bid
		.m_ace5lite_bresp         (m_ace5lite_bresp),                     //   input,    width = 2,           .bresp
		.m_ace5lite_bvalid        (m_ace5lite_bvalid),                    //   input,    width = 1,           .bvalid
		.m_ace5lite_bready        (m_ace5lite_bready),                    //  output,    width = 1,           .bready
		.m_ace5lite_arid          (m_ace5lite_arid),                      //  output,    width = 4,           .arid
		.m_ace5lite_araddr        (m_ace5lite_araddr),                    //  output,   width = 32,           .araddr
		.m_ace5lite_ardomain      (m_ace5lite_ardomain),                  //  output,    width = 2,           .ardomain
		.m_ace5lite_arsnoop       (m_ace5lite_arsnoop),                   //  output,    width = 4,           .arsnoop
		.m_ace5lite_arlen         (m_ace5lite_arlen),                     //  output,    width = 8,           .arlen
		.m_ace5lite_arburst       (m_ace5lite_arburst),                   //  output,    width = 2,           .arburst
		.m_ace5lite_arlock        (m_ace5lite_arlock),                    //  output,    width = 1,           .arlock
		.m_ace5lite_arcache       (m_ace5lite_arcache),                   //  output,    width = 4,           .arcache
		.m_ace5lite_arprot        (m_ace5lite_arprot),                    //  output,    width = 3,           .arprot
		.m_ace5lite_arqos         (m_ace5lite_arqos),                     //  output,    width = 4,           .arqos
		.m_ace5lite_arvalid       (m_ace5lite_arvalid),                   //  output,    width = 1,           .arvalid
		.m_ace5lite_arready       (m_ace5lite_arready),                   //   input,    width = 1,           .arready
		.m_ace5lite_rid           (m_ace5lite_rid),                       //   input,    width = 4,           .rid
		.m_ace5lite_rdata         (m_ace5lite_rdata),                     //   input,  width = 128,           .rdata
		.m_ace5lite_rresp         (m_ace5lite_rresp),                     //   input,    width = 2,           .rresp
		.m_ace5lite_rlast         (m_ace5lite_rlast),                     //   input,    width = 1,           .rlast
		.m_ace5lite_rvalid        (m_ace5lite_rvalid),                    //   input,    width = 1,           .rvalid
		.m_ace5lite_rready        (m_ace5lite_rready),                    //  output,    width = 1,           .rready
		.m_ace5lite_aruser        (m_ace5lite_aruser),                    //  output,    width = 8,           .aruser
		.m_ace5lite_awuser        (m_ace5lite_awuser),                    //  output,    width = 8,           .awuser
		.m_ace5lite_arregion      (m_ace5lite_arregion),                  //  output,    width = 4,           .arregion
		.m_ace5lite_awregion      (m_ace5lite_awregion),                  //  output,    width = 4,           .awregion
		.m_ace5lite_wuser         (m_ace5lite_wuser),                     //  output,    width = 8,           .wuser
		.m_ace5lite_buser         (m_ace5lite_buser),                     //   input,    width = 8,           .buser
		.m_ace5lite_ruser         (m_ace5lite_ruser),                     //   input,    width = 8,           .ruser
		.s_axi_awid               (s_axi_awid),                           //   input,    width = 4,      s_axi.awid
		.s_axi_awaddr             (s_axi_awaddr),                         //   input,   width = 32,           .awaddr
		.s_axi_awlen              (s_axi_awlen),                          //   input,    width = 8,           .awlen
		.s_axi_awsize             (s_axi_awsize),                         //   input,    width = 3,           .awsize
		.s_axi_awburst            (s_axi_awburst),                        //   input,    width = 2,           .awburst
		.s_axi_awlock             (s_axi_awlock),                         //   input,    width = 1,           .awlock
		.s_axi_awcache            (s_axi_awcache),                        //   input,    width = 4,           .awcache
		.s_axi_awprot             (s_axi_awprot),                         //   input,    width = 3,           .awprot
		.s_axi_awqos              (s_axi_awqos),                          //   input,    width = 4,           .awqos
		.s_axi_awvalid            (s_axi_awvalid),                        //   input,    width = 1,           .awvalid
		.s_axi_awready            (s_axi_awready),                        //  output,    width = 1,           .awready
		.s_axi_awregion           (s_axi_awregion),                       //   input,    width = 4,           .awregion
		.s_axi_wdata              (s_axi_wdata),                          //   input,  width = 128,           .wdata
		.s_axi_wstrb              (s_axi_wstrb),                          //   input,   width = 16,           .wstrb
		.s_axi_wlast              (s_axi_wlast),                          //   input,    width = 1,           .wlast
		.s_axi_wvalid             (s_axi_wvalid),                         //   input,    width = 1,           .wvalid
		.s_axi_wready             (s_axi_wready),                         //  output,    width = 1,           .wready
		.s_axi_wuser              (s_axi_wuser),                          //   input,    width = 8,           .wuser
		.s_axi_bid                (s_axi_bid),                            //  output,    width = 4,           .bid
		.s_axi_bresp              (s_axi_bresp),                          //  output,    width = 2,           .bresp
		.s_axi_bvalid             (s_axi_bvalid),                         //  output,    width = 1,           .bvalid
		.s_axi_bready             (s_axi_bready),                         //   input,    width = 1,           .bready
		.s_axi_buser              (s_axi_buser),                          //  output,    width = 8,           .buser
		.s_axi_arid               (s_axi_arid),                           //   input,    width = 4,           .arid
		.s_axi_araddr             (s_axi_araddr),                         //   input,   width = 32,           .araddr
		.s_axi_arlen              (s_axi_arlen),                          //   input,    width = 8,           .arlen
		.s_axi_arsize             (s_axi_arsize),                         //   input,    width = 3,           .arsize
		.s_axi_arburst            (s_axi_arburst),                        //   input,    width = 2,           .arburst
		.s_axi_arlock             (s_axi_arlock),                         //   input,    width = 1,           .arlock
		.s_axi_arcache            (s_axi_arcache),                        //   input,    width = 4,           .arcache
		.s_axi_arprot             (s_axi_arprot),                         //   input,    width = 3,           .arprot
		.s_axi_arqos              (s_axi_arqos),                          //   input,    width = 4,           .arqos
		.s_axi_arvalid            (s_axi_arvalid),                        //   input,    width = 1,           .arvalid
		.s_axi_arready            (s_axi_arready),                        //  output,    width = 1,           .arready
		.s_axi_arregion           (s_axi_arregion),                       //   input,    width = 4,           .arregion
		.s_axi_rid                (s_axi_rid),                            //  output,    width = 4,           .rid
		.s_axi_rdata              (s_axi_rdata),                          //  output,  width = 128,           .rdata
		.s_axi_rresp              (s_axi_rresp),                          //  output,    width = 2,           .rresp
		.s_axi_rlast              (s_axi_rlast),                          //  output,    width = 1,           .rlast
		.s_axi_rvalid             (s_axi_rvalid),                         //  output,    width = 1,           .rvalid
		.s_axi_rready             (s_axi_rready),                         //   input,    width = 1,           .rready
		.s_axi_ruser              (s_axi_ruser),                          //  output,    width = 8,           .ruser
		.s_axi_awatop             (6'b000000),                            // (terminated),                          
		.s_axi_awmmusecsid        (1'b0),                                 // (terminated),                          
		.s_axi_awmmusid           (16'b0000000000000000),                 // (terminated),                          
		.s_axi_armmusecsid        (1'b0),                                 // (terminated),                          
		.s_axi_armmusid           (16'b0000000000000000),                 // (terminated),                          
		.m_ace5lite_awmmusecsid   (),                                     // (terminated),                          
		.m_ace5lite_awmmusid      (),                                     // (terminated),                          
		.m_ace5lite_armmusecsid   (),                                     // (terminated),                          
		.m_ace5lite_armmusid      (),                                     // (terminated),                          
		.csr_clk                  (1'b0),                                 // (terminated),                          
		.csr_reset                (1'b0),                                 // (terminated),                          
		.s_csr_awaddr             (6'b000000),                            // (terminated),                          
		.s_csr_awvalid            (1'b0),                                 // (terminated),                          
		.s_csr_awready            (),                                     // (terminated),                          
		.s_csr_wdata              (32'b00000000000000000000000000000000), // (terminated),                          
		.s_csr_wstrb              (4'b0000),                              // (terminated),                          
		.s_csr_wvalid             (1'b0),                                 // (terminated),                          
		.s_csr_wready             (),                                     // (terminated),                          
		.s_csr_bresp              (),                                     // (terminated),                          
		.s_csr_bvalid             (),                                     // (terminated),                          
		.s_csr_bready             (1'b0),                                 // (terminated),                          
		.s_csr_araddr             (6'b000000),                            // (terminated),                          
		.s_csr_arvalid            (1'b0),                                 // (terminated),                          
		.s_csr_arready            (),                                     // (terminated),                          
		.s_csr_rdata              (),                                     // (terminated),                          
		.s_csr_rresp              (),                                     // (terminated),                          
		.s_csr_rvalid             (),                                     // (terminated),                          
		.s_csr_rready             (1'b0)                                  // (terminated),                          
	);

endmodule
