-- HPS_QSYS_intel_onchip_memory_0.vhd

-- Generated using ACDS version 25.3.1 100

library IEEE;
library intel_onchip_memory_1410;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity HPS_QSYS_intel_onchip_memory_0 is
	port (
		clk        : in  std_logic                     := '0';             --   clk1.clk
		s1_arid    : in  std_logic_vector(3 downto 0)  := (others => '0'); -- axi_s1.arid
		s1_araddr  : in  std_logic_vector(11 downto 0) := (others => '0'); --       .araddr
		s1_arlen   : in  std_logic_vector(7 downto 0)  := (others => '0'); --       .arlen
		s1_arsize  : in  std_logic_vector(2 downto 0)  := (others => '0'); --       .arsize
		s1_arburst : in  std_logic_vector(1 downto 0)  := (others => '0'); --       .arburst
		s1_arready : out std_logic;                                        --       .arready
		s1_arvalid : in  std_logic                     := '0';             --       .arvalid
		s1_awid    : in  std_logic_vector(3 downto 0)  := (others => '0'); --       .awid
		s1_awaddr  : in  std_logic_vector(11 downto 0) := (others => '0'); --       .awaddr
		s1_awlen   : in  std_logic_vector(7 downto 0)  := (others => '0'); --       .awlen
		s1_awsize  : in  std_logic_vector(2 downto 0)  := (others => '0'); --       .awsize
		s1_awburst : in  std_logic_vector(1 downto 0)  := (others => '0'); --       .awburst
		s1_awready : out std_logic;                                        --       .awready
		s1_awvalid : in  std_logic                     := '0';             --       .awvalid
		s1_rid     : out std_logic_vector(3 downto 0);                     --       .rid
		s1_rdata   : out std_logic_vector(31 downto 0);                    --       .rdata
		s1_rlast   : out std_logic;                                        --       .rlast
		s1_rready  : in  std_logic                     := '0';             --       .rready
		s1_rvalid  : out std_logic;                                        --       .rvalid
		s1_rresp   : out std_logic_vector(1 downto 0);                     --       .rresp
		s1_wdata   : in  std_logic_vector(31 downto 0) := (others => '0'); --       .wdata
		s1_wstrb   : in  std_logic_vector(3 downto 0)  := (others => '0'); --       .wstrb
		s1_wlast   : in  std_logic                     := '0';             --       .wlast
		s1_wready  : out std_logic;                                        --       .wready
		s1_wvalid  : in  std_logic                     := '0';             --       .wvalid
		s1_bid     : out std_logic_vector(3 downto 0);                     --       .bid
		s1_bresp   : out std_logic_vector(1 downto 0);                     --       .bresp
		s1_bready  : in  std_logic                     := '0';             --       .bready
		s1_bvalid  : out std_logic;                                        --       .bvalid
		reset      : in  std_logic                     := '0'              -- reset1.reset
	);
end entity HPS_QSYS_intel_onchip_memory_0;

architecture rtl of HPS_QSYS_intel_onchip_memory_0 is
	component HPS_QSYS_intel_onchip_memory_0_intel_onchip_memory_1410_rrnzwby_cmp is
		generic (
			deviceFamily : string := "NONE";
			INIT_FILE    : string := ""
		);
		port (
			clk        : in  std_logic                     := 'X';             -- clk
			s1_arid    : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- arid
			s1_araddr  : in  std_logic_vector(11 downto 0) := (others => 'X'); -- araddr
			s1_arlen   : in  std_logic_vector(7 downto 0)  := (others => 'X'); -- arlen
			s1_arsize  : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- arsize
			s1_arburst : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- arburst
			s1_arready : out std_logic;                                        -- arready
			s1_arvalid : in  std_logic                     := 'X';             -- arvalid
			s1_awid    : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- awid
			s1_awaddr  : in  std_logic_vector(11 downto 0) := (others => 'X'); -- awaddr
			s1_awlen   : in  std_logic_vector(7 downto 0)  := (others => 'X'); -- awlen
			s1_awsize  : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- awsize
			s1_awburst : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- awburst
			s1_awready : out std_logic;                                        -- awready
			s1_awvalid : in  std_logic                     := 'X';             -- awvalid
			s1_rid     : out std_logic_vector(3 downto 0);                     -- rid
			s1_rdata   : out std_logic_vector(31 downto 0);                    -- rdata
			s1_rlast   : out std_logic;                                        -- rlast
			s1_rready  : in  std_logic                     := 'X';             -- rready
			s1_rvalid  : out std_logic;                                        -- rvalid
			s1_rresp   : out std_logic_vector(1 downto 0);                     -- rresp
			s1_wdata   : in  std_logic_vector(31 downto 0) := (others => 'X'); -- wdata
			s1_wstrb   : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- wstrb
			s1_wlast   : in  std_logic                     := 'X';             -- wlast
			s1_wready  : out std_logic;                                        -- wready
			s1_wvalid  : in  std_logic                     := 'X';             -- wvalid
			s1_bid     : out std_logic_vector(3 downto 0);                     -- bid
			s1_bresp   : out std_logic_vector(1 downto 0);                     -- bresp
			s1_bready  : in  std_logic                     := 'X';             -- bready
			s1_bvalid  : out std_logic;                                        -- bvalid
			reset      : in  std_logic                     := 'X';             -- reset
			reset_req  : in  std_logic                     := 'X'              -- reset_req
		);
	end component HPS_QSYS_intel_onchip_memory_0_intel_onchip_memory_1410_rrnzwby_cmp;

	for intel_onchip_memory_0 : HPS_QSYS_intel_onchip_memory_0_intel_onchip_memory_1410_rrnzwby_cmp
		use entity intel_onchip_memory_1410.HPS_QSYS_intel_onchip_memory_0_intel_onchip_memory_1410_rrnzwby;
begin

	intel_onchip_memory_0 : component HPS_QSYS_intel_onchip_memory_0_intel_onchip_memory_1410_rrnzwby_cmp
		generic map (
			deviceFamily => "Agilex 5",
			INIT_FILE    => "HPS_QSYS_intel_onchip_memory_0_intel_onchip_memory_0.hex"
		)
		port map (
			clk        => clk,        --   clk1.clk
			s1_arid    => s1_arid,    -- axi_s1.arid
			s1_araddr  => s1_araddr,  --       .araddr
			s1_arlen   => s1_arlen,   --       .arlen
			s1_arsize  => s1_arsize,  --       .arsize
			s1_arburst => s1_arburst, --       .arburst
			s1_arready => s1_arready, --       .arready
			s1_arvalid => s1_arvalid, --       .arvalid
			s1_awid    => s1_awid,    --       .awid
			s1_awaddr  => s1_awaddr,  --       .awaddr
			s1_awlen   => s1_awlen,   --       .awlen
			s1_awsize  => s1_awsize,  --       .awsize
			s1_awburst => s1_awburst, --       .awburst
			s1_awready => s1_awready, --       .awready
			s1_awvalid => s1_awvalid, --       .awvalid
			s1_rid     => s1_rid,     --       .rid
			s1_rdata   => s1_rdata,   --       .rdata
			s1_rlast   => s1_rlast,   --       .rlast
			s1_rready  => s1_rready,  --       .rready
			s1_rvalid  => s1_rvalid,  --       .rvalid
			s1_rresp   => s1_rresp,   --       .rresp
			s1_wdata   => s1_wdata,   --       .wdata
			s1_wstrb   => s1_wstrb,   --       .wstrb
			s1_wlast   => s1_wlast,   --       .wlast
			s1_wready  => s1_wready,  --       .wready
			s1_wvalid  => s1_wvalid,  --       .wvalid
			s1_bid     => s1_bid,     --       .bid
			s1_bresp   => s1_bresp,   --       .bresp
			s1_bready  => s1_bready,  --       .bready
			s1_bvalid  => s1_bvalid,  --       .bvalid
			reset      => reset,      -- reset1.reset
			reset_req  => '0'         -- (terminated)
		);

end architecture rtl; -- of HPS_QSYS_intel_onchip_memory_0
