# TCL File Generated by Component Editor 25.3.1
# Thu Jun 04 18:45:21 CEST 2026
# DO NOT MODIFY


# 
# test_lpddr4b "test_lpddr4b" v1.0
#  2026.06.04.18:45:21
# 
# 

# 
# request TCL package from ACDS 25.3.1
# 
package require -exact qsys 25.3.1


# 
# module test_lpddr4b
# 
set_module_property DESCRIPTION ""
set_module_property NAME test_lpddr4b
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME test_lpddr4b
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false
set_module_property DISPLAY_ICON ""


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL test_lpddr4b
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file test_lpddr4b.vhd VHDL PATH ../vhdl/test_lpddr4b.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter AXI_ADDR_WIDTH INTEGER 30
set_parameter_property AXI_ADDR_WIDTH DEFAULT_VALUE 30
set_parameter_property AXI_ADDR_WIDTH DISPLAY_NAME AXI_ADDR_WIDTH
set_parameter_property AXI_ADDR_WIDTH UNITS None
set_parameter_property AXI_ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property AXI_ADDR_WIDTH HDL_PARAMETER true
set_parameter_property AXI_ADDR_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AXI_ADDR_WIDTH EXPORT true
set_parameter_property AXI_ADDR_WIDTH READ_ONLY false
add_parameter AXI_DATA_WIDTH INTEGER 256
set_parameter_property AXI_DATA_WIDTH DEFAULT_VALUE 256
set_parameter_property AXI_DATA_WIDTH DISPLAY_NAME AXI_DATA_WIDTH
set_parameter_property AXI_DATA_WIDTH UNITS None
set_parameter_property AXI_DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property AXI_DATA_WIDTH HDL_PARAMETER true
set_parameter_property AXI_DATA_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AXI_DATA_WIDTH EXPORT true
set_parameter_property AXI_DATA_WIDTH READ_ONLY false
add_parameter AXI_ID_WIDTH INTEGER 6
set_parameter_property AXI_ID_WIDTH DEFAULT_VALUE 6
set_parameter_property AXI_ID_WIDTH DISPLAY_NAME AXI_ID_WIDTH
set_parameter_property AXI_ID_WIDTH UNITS None
set_parameter_property AXI_ID_WIDTH AFFECTS_GENERATION false
set_parameter_property AXI_ID_WIDTH HDL_PARAMETER true
set_parameter_property AXI_ID_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AXI_ID_WIDTH EXPORT true
set_parameter_property AXI_ID_WIDTH READ_ONLY false


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""
set_interface_property clock IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clock SV_INTERFACE_TYPE ""
set_interface_property clock SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""
set_interface_property reset IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property reset SV_INTERFACE_TYPE ""
set_interface_property reset SV_INTERFACE_MODPORT_TYPE ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point conduit_end_0
# 
add_interface conduit_end_0 conduit end
set_interface_property conduit_end_0 associatedClock clock
set_interface_property conduit_end_0 associatedReset ""
set_interface_property conduit_end_0 ENABLED true
set_interface_property conduit_end_0 EXPORT_OF ""
set_interface_property conduit_end_0 PORT_NAME_MAP ""
set_interface_property conduit_end_0 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_0 SVD_ADDRESS_GROUP ""
set_interface_property conduit_end_0 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property conduit_end_0 SV_INTERFACE_TYPE ""
set_interface_property conduit_end_0 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port conduit_end_0 coe_test_complete export Output 1


# 
# connection point altera_axi4_master
# 
add_interface altera_axi4_master axi4 start
set_interface_property altera_axi4_master associatedClock clock
set_interface_property altera_axi4_master associatedReset reset
set_interface_property altera_axi4_master optionalAssociatedReset false
set_interface_property altera_axi4_master poison false
set_interface_property altera_axi4_master dataCheck false
set_interface_property altera_axi4_master addressCheck false
set_interface_property altera_axi4_master securityAttribute false
set_interface_property altera_axi4_master userData false
set_interface_property altera_axi4_master readIssuingCapability 1
set_interface_property altera_axi4_master writeIssuingCapability 1
set_interface_property altera_axi4_master combinedIssuingCapability 1
set_interface_property altera_axi4_master enableConcurrentSubordinateAccess 0
set_interface_property altera_axi4_master noRepeatedIdsBetweenSubordinates 0
set_interface_property altera_axi4_master issuesINCRBursts true
set_interface_property altera_axi4_master issuesWRAPBursts true
set_interface_property altera_axi4_master issuesFIXEDBursts true
set_interface_property altera_axi4_master ENABLED true
set_interface_property altera_axi4_master EXPORT_OF ""
set_interface_property altera_axi4_master PORT_NAME_MAP ""
set_interface_property altera_axi4_master CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4_master SVD_ADDRESS_GROUP ""
set_interface_property altera_axi4_master IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property altera_axi4_master SV_INTERFACE_TYPE ""
set_interface_property altera_axi4_master SV_INTERFACE_MODPORT_TYPE ""

add_interface_port altera_axi4_master axi_m_awaddr awaddr Output "((axi_addr_width - 1)) - (0) + 1"
add_interface_port altera_axi4_master axi_m_awburst awburst Output 2
add_interface_port altera_axi4_master axi_m_awcache awcache Output 4
add_interface_port altera_axi4_master axi_m_awid awid Output "((axi_id_width - 1)) - (0) + 1"
add_interface_port altera_axi4_master axi_m_awlen awlen Output 8
add_interface_port altera_axi4_master axi_m_awlock awlock Output 1
add_interface_port altera_axi4_master axi_m_awqos awqos Output 4
add_interface_port altera_axi4_master axi_m_awsize awsize Output 3
add_interface_port altera_axi4_master axi_m_awvalid awvalid Output 1
add_interface_port altera_axi4_master axi_m_awuser awuser Output 14
add_interface_port altera_axi4_master axi_m_awprot awprot Output 3
add_interface_port altera_axi4_master axi_m_awready awready Input 1
add_interface_port altera_axi4_master axi_m_araddr araddr Output "((axi_addr_width - 1)) - (0) + 1"
add_interface_port altera_axi4_master axi_m_arburst arburst Output 2
add_interface_port altera_axi4_master axi_m_arcache arcache Output 4
add_interface_port altera_axi4_master axi_m_arid arid Output "((axi_id_width - 1)) - (0) + 1"
add_interface_port altera_axi4_master axi_m_arlen arlen Output 8
add_interface_port altera_axi4_master axi_m_arlock arlock Output 1
add_interface_port altera_axi4_master axi_m_arqos arqos Output 4
add_interface_port altera_axi4_master axi_m_arsize arsize Output 3
add_interface_port altera_axi4_master axi_m_arvalid arvalid Output 1
add_interface_port altera_axi4_master axi_m_aruser aruser Output 14
add_interface_port altera_axi4_master axi_m_arprot arprot Output 3
add_interface_port altera_axi4_master axi_m_arready arready Input 1
add_interface_port altera_axi4_master axi_m_wdata wdata Output "((axi_data_width - 1)) - (0) + 1"
add_interface_port altera_axi4_master axi_m_wstrb wstrb Output "(((axi_data_width / 8) - 1)) - (0) + 1"
add_interface_port altera_axi4_master axi_m_wlast wlast Output 1
add_interface_port altera_axi4_master axi_m_wvalid wvalid Output 1
add_interface_port altera_axi4_master axi_m_wready wready Input 1
add_interface_port altera_axi4_master axi_m_bready bready Output 1
add_interface_port altera_axi4_master axi_m_bid bid Input "((axi_id_width - 1)) - (0) + 1"
add_interface_port altera_axi4_master axi_m_bresp bresp Input 2
add_interface_port altera_axi4_master axi_m_bvalid bvalid Input 1
add_interface_port altera_axi4_master axi_m_rready rready Output 1
add_interface_port altera_axi4_master axi_m_rdata rdata Input "((axi_data_width - 1)) - (0) + 1"
add_interface_port altera_axi4_master axi_m_rid rid Input "((axi_id_width - 1)) - (0) + 1"
add_interface_port altera_axi4_master axi_m_rlast rlast Input 1
add_interface_port altera_axi4_master axi_m_rresp rresp Input 2
add_interface_port altera_axi4_master axi_m_rvalid rvalid Input 1

