-- HPS_QSYS_emif_io96b_lpddr4b.vhd

-- Generated using ACDS version 25.3.1 100

library IEEE;
library emif_io96b_lpddr4_411;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity HPS_QSYS_emif_io96b_lpddr4b is
	port (
		s0_axi4_clock_in    : in    std_logic                      := '0';             --    s0_axi4_clock_in.clk,         User clock for mainband axi. Input clock to the EMIF IP, no relationship to PHY clock.
		core_init_n         : in    std_logic                      := '0';             --         core_init_n.reset_n,     Core init signal going into EMIF. Used to generate the reset signal on the core-EMIF interface in fabric modes. When high, indicates core initialization is complete. The Reset Release IP should be used to generate the core initialization complete signal.
		s0_axi4_reset_n     : out   std_logic;                                         --  s0_axi4_ctrl_ready.reset_n,     Output signal from EMIF IP (primary I/O bank), indicating that Calibration of the channels in this I/O bank is complete, and controllers in this I/O bank are ready for use.
		s0_axi4_awaddr      : in    std_logic_vector(29 downto 0)  := (others => '0'); --             s0_axi4.awaddr,      Write Address , channel 0.
		s0_axi4_awburst     : in    std_logic_vector(1 downto 0)   := (others => '0'); --                    .awburst,     Write Burst Type, channel 0.
		s0_axi4_awid        : in    std_logic_vector(6 downto 0)   := (others => '0'); --                    .awid,        Write Address ID, channel 0.
		s0_axi4_awlen       : in    std_logic_vector(7 downto 0)   := (others => '0'); --                    .awlen,       Write Burst Length, channel 0.
		s0_axi4_awlock      : in    std_logic                      := '0';             --                    .awlock,      Write Lock Type, channel 0.
		s0_axi4_awqos       : in    std_logic_vector(3 downto 0)   := (others => '0'); --                    .awqos,       Write Quality of Service, channel 0.
		s0_axi4_awsize      : in    std_logic_vector(2 downto 0)   := (others => '0'); --                    .awsize,      Write Burst Size, channel 0.
		s0_axi4_awvalid     : in    std_logic                      := '0';             --                    .awvalid,     Write Address Valid, channel 0.
		s0_axi4_awuser      : in    std_logic_vector(13 downto 0)  := (others => '0'); --                    .awuser,      Write Address User Signal, channel 0.
		s0_axi4_awprot      : in    std_logic_vector(2 downto 0)   := (others => '0'); --                    .awprot,      Write Protection Type, channel 0.
		s0_axi4_awready     : out   std_logic;                                         --                    .awready,     Write Address Ready, channel 0.
		s0_axi4_araddr      : in    std_logic_vector(29 downto 0)  := (others => '0'); --                    .araddr,      Read Address , channel 0.
		s0_axi4_arburst     : in    std_logic_vector(1 downto 0)   := (others => '0'); --                    .arburst,     Read Burst Type, channel 0.
		s0_axi4_arid        : in    std_logic_vector(6 downto 0)   := (others => '0'); --                    .arid,        Read Address ID, channel 0.
		s0_axi4_arlen       : in    std_logic_vector(7 downto 0)   := (others => '0'); --                    .arlen,       Read Burst Length, channel 0.
		s0_axi4_arlock      : in    std_logic                      := '0';             --                    .arlock,      Read Lock Type, channel 0.
		s0_axi4_arqos       : in    std_logic_vector(3 downto 0)   := (others => '0'); --                    .arqos,       Read Quality of Service, channel 0.
		s0_axi4_arsize      : in    std_logic_vector(2 downto 0)   := (others => '0'); --                    .arsize,      Read Burst Size, channel 0.
		s0_axi4_arvalid     : in    std_logic                      := '0';             --                    .arvalid,     Read Address Valid, channel 0.
		s0_axi4_aruser      : in    std_logic_vector(13 downto 0)  := (others => '0'); --                    .aruser,      Read Address User Signal, channel 0.
		s0_axi4_arprot      : in    std_logic_vector(2 downto 0)   := (others => '0'); --                    .arprot,      Read Protection Type, channel 0.
		s0_axi4_arready     : out   std_logic;                                         --                    .arready,     Read Address Ready, channel 0.
		s0_axi4_wdata       : in    std_logic_vector(255 downto 0) := (others => '0'); --                    .wdata,       Write Data , channel 0.
		s0_axi4_wstrb       : in    std_logic_vector(31 downto 0)  := (others => '0'); --                    .wstrb,       Write Strobes, channel 0.
		s0_axi4_wlast       : in    std_logic                      := '0';             --                    .wlast,       Write Last, channel 0.
		s0_axi4_wvalid      : in    std_logic                      := '0';             --                    .wvalid,      Write Valid, channel 0.
		s0_axi4_wready      : out   std_logic;                                         --                    .wready,      Write Ready, channel 0.
		s0_axi4_bready      : in    std_logic                      := '0';             --                    .bready,      Write Response Ready, channel 0.
		s0_axi4_bid         : out   std_logic_vector(6 downto 0);                      --                    .bid,         Write Response ID, channel 0.
		s0_axi4_bresp       : out   std_logic_vector(1 downto 0);                      --                    .bresp,       Write Response , channel 0.
		s0_axi4_bvalid      : out   std_logic;                                         --                    .bvalid,      Write Response Valid, channel 0.
		s0_axi4_rready      : in    std_logic                      := '0';             --                    .rready,      Read Ready, channel 0.
		s0_axi4_rdata       : out   std_logic_vector(255 downto 0);                    --                    .rdata,       Read Data, channel 0.
		s0_axi4_rid         : out   std_logic_vector(6 downto 0);                      --                    .rid,         Read ID , channel 0.
		s0_axi4_rlast       : out   std_logic;                                         --                    .rlast,       Read Last, channel 0.
		s0_axi4_rresp       : out   std_logic_vector(1 downto 0);                      --                    .rresp,       Read Response, channel 0.
		s0_axi4_rvalid      : out   std_logic;                                         --                    .rvalid,      Read Valid, channel 0.
		s0_axi4lite_clock   : in    std_logic                      := '0';             --   s0_axi4lite_clock.clk,         Axi-Lite clock, to primary IOSSM.
		s0_axi4lite_reset_n : in    std_logic                      := '0';             -- s0_axi4lite_reset_n.reset_n,     Axi-Lite reset_n, to primary IOSSM.
		s0_axi4lite_awaddr  : in    std_logic_vector(26 downto 0)  := (others => '0'); --         s0_axi4lite.awaddr,      Axi-Lite Write Address, to primary IOSSM.
		s0_axi4lite_awprot  : in    std_logic_vector(2 downto 0)   := (others => '0'); --                    .awprot,      Axi-Lite Write Address Protection Signal, to primary IOSSM.
		s0_axi4lite_awvalid : in    std_logic                      := '0';             --                    .awvalid,     Axi-Lite Write Address Valid, to primary IOSSM.
		s0_axi4lite_awready : out   std_logic;                                         --                    .awready,     Axi-Lite Write Address Ready, to primary IOSSM.
		s0_axi4lite_araddr  : in    std_logic_vector(26 downto 0)  := (others => '0'); --                    .araddr,      Axi-Lite Read Address, to primary IOSSM.
		s0_axi4lite_arprot  : in    std_logic_vector(2 downto 0)   := (others => '0'); --                    .arprot,      Axi-Lite Read Address Protection Signal, to primary IOSSM.
		s0_axi4lite_arvalid : in    std_logic                      := '0';             --                    .arvalid,     Axi-Lite Read Address Valid, to primary IOSSM.
		s0_axi4lite_arready : out   std_logic;                                         --                    .arready,     Axi-Lite Read Address Ready, to primary IOSSM.
		s0_axi4lite_wdata   : in    std_logic_vector(31 downto 0)  := (others => '0'); --                    .wdata,       Axi-Lite Write Data, to primary IOSSM.
		s0_axi4lite_wstrb   : in    std_logic_vector(3 downto 0)   := (others => '0'); --                    .wstrb,       Axi-Lite Write Strobe, to primary IOSSM.
		s0_axi4lite_wvalid  : in    std_logic                      := '0';             --                    .wvalid,      Axi-Lite Write Valid, to primary IOSSM.
		s0_axi4lite_wready  : out   std_logic;                                         --                    .wready,      Axi-Lite Write Ready, to primary IOSSM.
		s0_axi4lite_bready  : in    std_logic                      := '0';             --                    .bready,      Axi-Lite Write Response Ready, to primary IOSSM.
		s0_axi4lite_bresp   : out   std_logic_vector(1 downto 0);                      --                    .bresp,       Axi-Lite Write Response, to primary IOSSM.
		s0_axi4lite_bvalid  : out   std_logic;                                         --                    .bvalid,      Axi-Lite Write Response Valid, to primary IOSSM.
		s0_axi4lite_rready  : in    std_logic                      := '0';             --                    .rready,      Axi-Lite Read Ready, to primary IOSSM.
		s0_axi4lite_rdata   : out   std_logic_vector(31 downto 0);                     --                    .rdata,       Axi-Lite Read Data, to primary IOSSM.
		s0_axi4lite_rresp   : out   std_logic_vector(1 downto 0);                      --                    .rresp,       Axi-Lite Read Response, to primary IOSSM.
		s0_axi4lite_rvalid  : out   std_logic;                                         --                    .rvalid,      Axi-Lite Read Valid, to primary IOSSM.
		mem_0_cs            : out   std_logic_vector(0 downto 0);                      --               mem_0.mem_cs,      Chip Select channel 0.
		mem_0_ca            : out   std_logic_vector(5 downto 0);                      --                    .mem_ca,      Command/Address Bus channel 0.
		mem_0_cke           : out   std_logic_vector(0 downto 0);                      --                    .mem_cke,     Clock Enable channel 0.
		mem_0_dq            : inout std_logic_vector(31 downto 0)  := (others => '0'); --                    .mem_dq,      Data (read/write) channel 0.
		mem_0_dqs_t         : inout std_logic_vector(3 downto 0)   := (others => '0'); --                    .mem_dqs_t,   Data Strobe (true) channel 0.
		mem_0_dqs_c         : inout std_logic_vector(3 downto 0)   := (others => '0'); --                    .mem_dqs_c,   Data Strobe (complement) channel 0.
		mem_0_dmi           : inout std_logic_vector(3 downto 0)   := (others => '0'); --                    .mem_dmi,     Data Mask/Data Inversion channel 0.
		mem_0_ck_t          : out   std_logic_vector(0 downto 0);                      --            mem_ck_0.mem_ck_t,    CK Clock (true) channel 0.
		mem_0_ck_c          : out   std_logic_vector(0 downto 0);                      --                    .mem_ck_c,    CK Clock (complement) channel 0.
		mem_0_reset_n       : out   std_logic;                                         --         mem_reset_n.mem_reset_n, Asynchronous Reset channel 0.
		oct_rzqin_0         : in    std_logic                      := '0';             --               oct_0.oct_rzqin,   Calibrated On-Chip Termination (OCT) input pin channel 0.
		ref_clk             : in    std_logic                      := '0'              --             ref_clk.clk,         PLL reference clock input.
	);
end entity HPS_QSYS_emif_io96b_lpddr4b;

architecture rtl of HPS_QSYS_emif_io96b_lpddr4b is
	component HPS_QSYS_emif_io96b_lpddr4b_emif_io96b_lpddr4_411_xfxzd4y_cmp is
		port (
			s0_axi4_clock_in    : in    std_logic                      := 'X';             -- clk
			core_init_n         : in    std_logic                      := 'X';             -- reset_n
			s0_axi4_reset_n     : out   std_logic;                                         -- reset_n
			s0_axi4_awaddr      : in    std_logic_vector(29 downto 0)  := (others => 'X'); -- awaddr
			s0_axi4_awburst     : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- awburst
			s0_axi4_awid        : in    std_logic_vector(6 downto 0)   := (others => 'X'); -- awid
			s0_axi4_awlen       : in    std_logic_vector(7 downto 0)   := (others => 'X'); -- awlen
			s0_axi4_awlock      : in    std_logic                      := 'X';             -- awlock
			s0_axi4_awqos       : in    std_logic_vector(3 downto 0)   := (others => 'X'); -- awqos
			s0_axi4_awsize      : in    std_logic_vector(2 downto 0)   := (others => 'X'); -- awsize
			s0_axi4_awvalid     : in    std_logic                      := 'X';             -- awvalid
			s0_axi4_awuser      : in    std_logic_vector(13 downto 0)  := (others => 'X'); -- awuser
			s0_axi4_awprot      : in    std_logic_vector(2 downto 0)   := (others => 'X'); -- awprot
			s0_axi4_awready     : out   std_logic;                                         -- awready
			s0_axi4_araddr      : in    std_logic_vector(29 downto 0)  := (others => 'X'); -- araddr
			s0_axi4_arburst     : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- arburst
			s0_axi4_arid        : in    std_logic_vector(6 downto 0)   := (others => 'X'); -- arid
			s0_axi4_arlen       : in    std_logic_vector(7 downto 0)   := (others => 'X'); -- arlen
			s0_axi4_arlock      : in    std_logic                      := 'X';             -- arlock
			s0_axi4_arqos       : in    std_logic_vector(3 downto 0)   := (others => 'X'); -- arqos
			s0_axi4_arsize      : in    std_logic_vector(2 downto 0)   := (others => 'X'); -- arsize
			s0_axi4_arvalid     : in    std_logic                      := 'X';             -- arvalid
			s0_axi4_aruser      : in    std_logic_vector(13 downto 0)  := (others => 'X'); -- aruser
			s0_axi4_arprot      : in    std_logic_vector(2 downto 0)   := (others => 'X'); -- arprot
			s0_axi4_arready     : out   std_logic;                                         -- arready
			s0_axi4_wdata       : in    std_logic_vector(255 downto 0) := (others => 'X'); -- wdata
			s0_axi4_wstrb       : in    std_logic_vector(31 downto 0)  := (others => 'X'); -- wstrb
			s0_axi4_wlast       : in    std_logic                      := 'X';             -- wlast
			s0_axi4_wvalid      : in    std_logic                      := 'X';             -- wvalid
			s0_axi4_wready      : out   std_logic;                                         -- wready
			s0_axi4_bready      : in    std_logic                      := 'X';             -- bready
			s0_axi4_bid         : out   std_logic_vector(6 downto 0);                      -- bid
			s0_axi4_bresp       : out   std_logic_vector(1 downto 0);                      -- bresp
			s0_axi4_bvalid      : out   std_logic;                                         -- bvalid
			s0_axi4_rready      : in    std_logic                      := 'X';             -- rready
			s0_axi4_rdata       : out   std_logic_vector(255 downto 0);                    -- rdata
			s0_axi4_rid         : out   std_logic_vector(6 downto 0);                      -- rid
			s0_axi4_rlast       : out   std_logic;                                         -- rlast
			s0_axi4_rresp       : out   std_logic_vector(1 downto 0);                      -- rresp
			s0_axi4_rvalid      : out   std_logic;                                         -- rvalid
			s0_axi4lite_clock   : in    std_logic                      := 'X';             -- clk
			s0_axi4lite_reset_n : in    std_logic                      := 'X';             -- reset_n
			s0_axi4lite_awaddr  : in    std_logic_vector(26 downto 0)  := (others => 'X'); -- awaddr
			s0_axi4lite_awprot  : in    std_logic_vector(2 downto 0)   := (others => 'X'); -- awprot
			s0_axi4lite_awvalid : in    std_logic                      := 'X';             -- awvalid
			s0_axi4lite_awready : out   std_logic;                                         -- awready
			s0_axi4lite_araddr  : in    std_logic_vector(26 downto 0)  := (others => 'X'); -- araddr
			s0_axi4lite_arprot  : in    std_logic_vector(2 downto 0)   := (others => 'X'); -- arprot
			s0_axi4lite_arvalid : in    std_logic                      := 'X';             -- arvalid
			s0_axi4lite_arready : out   std_logic;                                         -- arready
			s0_axi4lite_wdata   : in    std_logic_vector(31 downto 0)  := (others => 'X'); -- wdata
			s0_axi4lite_wstrb   : in    std_logic_vector(3 downto 0)   := (others => 'X'); -- wstrb
			s0_axi4lite_wvalid  : in    std_logic                      := 'X';             -- wvalid
			s0_axi4lite_wready  : out   std_logic;                                         -- wready
			s0_axi4lite_bready  : in    std_logic                      := 'X';             -- bready
			s0_axi4lite_bresp   : out   std_logic_vector(1 downto 0);                      -- bresp
			s0_axi4lite_bvalid  : out   std_logic;                                         -- bvalid
			s0_axi4lite_rready  : in    std_logic                      := 'X';             -- rready
			s0_axi4lite_rdata   : out   std_logic_vector(31 downto 0);                     -- rdata
			s0_axi4lite_rresp   : out   std_logic_vector(1 downto 0);                      -- rresp
			s0_axi4lite_rvalid  : out   std_logic;                                         -- rvalid
			mem_0_cs            : out   std_logic_vector(0 downto 0);                      -- mem_cs
			mem_0_ca            : out   std_logic_vector(5 downto 0);                      -- mem_ca
			mem_0_cke           : out   std_logic_vector(0 downto 0);                      -- mem_cke
			mem_0_dq            : inout std_logic_vector(31 downto 0)  := (others => 'X'); -- mem_dq
			mem_0_dqs_t         : inout std_logic_vector(3 downto 0)   := (others => 'X'); -- mem_dqs_t
			mem_0_dqs_c         : inout std_logic_vector(3 downto 0)   := (others => 'X'); -- mem_dqs_c
			mem_0_dmi           : inout std_logic_vector(3 downto 0)   := (others => 'X'); -- mem_dmi
			mem_0_ck_t          : out   std_logic_vector(0 downto 0);                      -- mem_ck_t
			mem_0_ck_c          : out   std_logic_vector(0 downto 0);                      -- mem_ck_c
			mem_0_reset_n       : out   std_logic;                                         -- mem_reset_n
			oct_rzqin_0         : in    std_logic                      := 'X';             -- oct_rzqin
			ref_clk             : in    std_logic                      := 'X'              -- clk
		);
	end component HPS_QSYS_emif_io96b_lpddr4b_emif_io96b_lpddr4_411_xfxzd4y_cmp;

	for emif_io96b_lpddr4b : HPS_QSYS_emif_io96b_lpddr4b_emif_io96b_lpddr4_411_xfxzd4y_cmp
		use entity emif_io96b_lpddr4_411.HPS_QSYS_emif_io96b_lpddr4b_emif_io96b_lpddr4_411_xfxzd4y;
begin

	emif_io96b_lpddr4b : component HPS_QSYS_emif_io96b_lpddr4b_emif_io96b_lpddr4_411_xfxzd4y_cmp
		port map (
			s0_axi4_clock_in    => s0_axi4_clock_in,    --    s0_axi4_clock_in.clk
			core_init_n         => core_init_n,         --         core_init_n.reset_n
			s0_axi4_reset_n     => s0_axi4_reset_n,     --  s0_axi4_ctrl_ready.reset_n
			s0_axi4_awaddr      => s0_axi4_awaddr,      --             s0_axi4.awaddr
			s0_axi4_awburst     => s0_axi4_awburst,     --                    .awburst
			s0_axi4_awid        => s0_axi4_awid,        --                    .awid
			s0_axi4_awlen       => s0_axi4_awlen,       --                    .awlen
			s0_axi4_awlock      => s0_axi4_awlock,      --                    .awlock
			s0_axi4_awqos       => s0_axi4_awqos,       --                    .awqos
			s0_axi4_awsize      => s0_axi4_awsize,      --                    .awsize
			s0_axi4_awvalid     => s0_axi4_awvalid,     --                    .awvalid
			s0_axi4_awuser      => s0_axi4_awuser,      --                    .awuser
			s0_axi4_awprot      => s0_axi4_awprot,      --                    .awprot
			s0_axi4_awready     => s0_axi4_awready,     --                    .awready
			s0_axi4_araddr      => s0_axi4_araddr,      --                    .araddr
			s0_axi4_arburst     => s0_axi4_arburst,     --                    .arburst
			s0_axi4_arid        => s0_axi4_arid,        --                    .arid
			s0_axi4_arlen       => s0_axi4_arlen,       --                    .arlen
			s0_axi4_arlock      => s0_axi4_arlock,      --                    .arlock
			s0_axi4_arqos       => s0_axi4_arqos,       --                    .arqos
			s0_axi4_arsize      => s0_axi4_arsize,      --                    .arsize
			s0_axi4_arvalid     => s0_axi4_arvalid,     --                    .arvalid
			s0_axi4_aruser      => s0_axi4_aruser,      --                    .aruser
			s0_axi4_arprot      => s0_axi4_arprot,      --                    .arprot
			s0_axi4_arready     => s0_axi4_arready,     --                    .arready
			s0_axi4_wdata       => s0_axi4_wdata,       --                    .wdata
			s0_axi4_wstrb       => s0_axi4_wstrb,       --                    .wstrb
			s0_axi4_wlast       => s0_axi4_wlast,       --                    .wlast
			s0_axi4_wvalid      => s0_axi4_wvalid,      --                    .wvalid
			s0_axi4_wready      => s0_axi4_wready,      --                    .wready
			s0_axi4_bready      => s0_axi4_bready,      --                    .bready
			s0_axi4_bid         => s0_axi4_bid,         --                    .bid
			s0_axi4_bresp       => s0_axi4_bresp,       --                    .bresp
			s0_axi4_bvalid      => s0_axi4_bvalid,      --                    .bvalid
			s0_axi4_rready      => s0_axi4_rready,      --                    .rready
			s0_axi4_rdata       => s0_axi4_rdata,       --                    .rdata
			s0_axi4_rid         => s0_axi4_rid,         --                    .rid
			s0_axi4_rlast       => s0_axi4_rlast,       --                    .rlast
			s0_axi4_rresp       => s0_axi4_rresp,       --                    .rresp
			s0_axi4_rvalid      => s0_axi4_rvalid,      --                    .rvalid
			s0_axi4lite_clock   => s0_axi4lite_clock,   --   s0_axi4lite_clock.clk
			s0_axi4lite_reset_n => s0_axi4lite_reset_n, -- s0_axi4lite_reset_n.reset_n
			s0_axi4lite_awaddr  => s0_axi4lite_awaddr,  --         s0_axi4lite.awaddr
			s0_axi4lite_awprot  => s0_axi4lite_awprot,  --                    .awprot
			s0_axi4lite_awvalid => s0_axi4lite_awvalid, --                    .awvalid
			s0_axi4lite_awready => s0_axi4lite_awready, --                    .awready
			s0_axi4lite_araddr  => s0_axi4lite_araddr,  --                    .araddr
			s0_axi4lite_arprot  => s0_axi4lite_arprot,  --                    .arprot
			s0_axi4lite_arvalid => s0_axi4lite_arvalid, --                    .arvalid
			s0_axi4lite_arready => s0_axi4lite_arready, --                    .arready
			s0_axi4lite_wdata   => s0_axi4lite_wdata,   --                    .wdata
			s0_axi4lite_wstrb   => s0_axi4lite_wstrb,   --                    .wstrb
			s0_axi4lite_wvalid  => s0_axi4lite_wvalid,  --                    .wvalid
			s0_axi4lite_wready  => s0_axi4lite_wready,  --                    .wready
			s0_axi4lite_bready  => s0_axi4lite_bready,  --                    .bready
			s0_axi4lite_bresp   => s0_axi4lite_bresp,   --                    .bresp
			s0_axi4lite_bvalid  => s0_axi4lite_bvalid,  --                    .bvalid
			s0_axi4lite_rready  => s0_axi4lite_rready,  --                    .rready
			s0_axi4lite_rdata   => s0_axi4lite_rdata,   --                    .rdata
			s0_axi4lite_rresp   => s0_axi4lite_rresp,   --                    .rresp
			s0_axi4lite_rvalid  => s0_axi4lite_rvalid,  --                    .rvalid
			mem_0_cs            => mem_0_cs,            --               mem_0.mem_cs
			mem_0_ca            => mem_0_ca,            --                    .mem_ca
			mem_0_cke           => mem_0_cke,           --                    .mem_cke
			mem_0_dq            => mem_0_dq,            --                    .mem_dq
			mem_0_dqs_t         => mem_0_dqs_t,         --                    .mem_dqs_t
			mem_0_dqs_c         => mem_0_dqs_c,         --                    .mem_dqs_c
			mem_0_dmi           => mem_0_dmi,           --                    .mem_dmi
			mem_0_ck_t          => mem_0_ck_t,          --            mem_ck_0.mem_ck_t
			mem_0_ck_c          => mem_0_ck_c,          --                    .mem_ck_c
			mem_0_reset_n       => mem_0_reset_n,       --         mem_reset_n.mem_reset_n
			oct_rzqin_0         => oct_rzqin_0,         --               oct_0.oct_rzqin
			ref_clk             => ref_clk              --             ref_clk.clk
		);

end architecture rtl; -- of HPS_QSYS_emif_io96b_lpddr4b
